
import pytest
from playwright.sync_api import sync_playwright
import os

MOCK_HTML_PATH = os.path.join(os.getcwd(), 'verification/mock_structures.html')

def test_screenshot_structure_search():
    # We use the same mock file generated by the previous test, or we can generate it again.
    # The previous test generated verification/mock_structures.html

    if not os.path.exists(MOCK_HTML_PATH):
        print(f"Error: {MOCK_HTML_PATH} does not exist. Run verify_structure_search.py first.")
        return

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        page.goto(f'file://{MOCK_HTML_PATH}')

        # Inject the JS logic
        with open('ai-post-scheduler/assets/js/admin.js', 'r') as f:
            js_content = f.read()

        page.add_script_tag(content="""
            window.aipsAjax = { ajaxUrl: '/wp-admin/admin-ajax.php', nonce: '123' };
            window.aipsAdminL10n = {};
            window.wp = { media: function() {} };
        """)

        page.add_script_tag(content=js_content)

        # Take a screenshot of the initial state
        page.screenshot(path='verification/structures_initial.png')

        # Filter for "Listicle"
        page.fill('#aips-structure-search', 'Listicle')
        page.keyboard.up('e')

        # Take a screenshot of the filtered state
        page.screenshot(path='verification/structures_filtered.png')

        # Filter for "Nothing"
        page.fill('#aips-structure-search', 'Nothing')
        page.keyboard.up('g')

        # Take a screenshot of the empty state
        page.screenshot(path='verification/structures_empty.png')

        browser.close()
        print("Screenshots generated!")

if __name__ == "__main__":
    test_screenshot_structure_search()
