from playwright.sync_api import sync_playwright, expect
import os

def test_planner_accessibility(page):
    # Load the mock HTML file
    cwd = os.getcwd()
    page.goto(f"file://{cwd}/verification/mock_planner.html")

    # Reveal the hidden section for testing
    page.evaluate("document.getElementById('planner-results').style.display = 'block'")

    # 1. Verify Frequency Label (Should only be one label for bulk-frequency)
    frequency_col = page.locator(".aips-col").filter(has_text="Frequency")
    labels = frequency_col.locator("label", has_text="Frequency")
    count = labels.count()
    print(f"Frequency labels found: {count}")

    # We expect exactly 1 label now (generated by the helper)
    if count != 1:
        print(f"FAILURE: Expected 1 Frequency label, found {count}")
    else:
        print("SUCCESS: Duplicate label check passed.")

    # 2. Verify Search Input Accessibility
    # It should have an accessible name "Filter topics"
    search_input = page.get_by_label("Filter topics")
    expect(search_input).to_be_visible()
    print("SUCCESS: Search input accessible by label.")

    # 3. Verify Template Description Association
    # The select should be described by the paragraph
    template_select = page.locator("#bulk-template")
    described_by = template_select.get_attribute("aria-describedby")

    if described_by == "bulk-template-desc":
         print("SUCCESS: Template select has correct aria-describedby.")
    else:
         print(f"FAILURE: Template select missing aria-describedby. Found: {described_by}")

    # Take a screenshot
    page.screenshot(path="verification/verification.png", full_page=True)

if __name__ == "__main__":
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        try:
            test_planner_accessibility(page)
        finally:
            browser.close()
