<?php
/**
 * Generated Posts Admin Template
 *
 * Displays all posts generated by the AI Post Scheduler plugin with tabbed interface.
 * 
 * Tab 1: Generated Posts - Shows published posts
 * Tab 2: Partial Generations - Shows posts with one or more missing components
 * Tab 3: Pending Review - Shows draft posts awaiting review
 *
 * @package AI_Post_Scheduler
 * @since 2.0.0
 */

if (!defined('ABSPATH')) {
	exit;
}

/** @var AIPS_Generated_Posts_Controller $controller */
?>

<div class="wrap aips-wrap">
	<div class="aips-page-container">
		<!-- Page Header -->
		<div class="aips-page-header">
			<div class="aips-page-header-top">
				<div>
					<h1 class="aips-page-title"><?php esc_html_e('Generated Posts', 'ai-post-scheduler'); ?></h1>
					<p class="aips-page-description"><?php esc_html_e('View and manage all AI-generated posts including published articles and drafts pending review.', 'ai-post-scheduler'); ?></p>
				</div>
			</div>
		</div>

		<!-- Tabs navigation -->
		<div class="aips-tab-nav">
			<a href="#aips-generated-posts" class="aips-tab-link active" data-tab="aips-generated-posts"><?php esc_html_e('Generated Posts', 'ai-post-scheduler'); ?></a>
			<a href="#aips-partial-generations" class="aips-tab-link" data-tab="aips-partial-generations"><?php esc_html_e('Partial Generations', 'ai-post-scheduler'); ?></a>
			<a href="#aips-pending-review" class="aips-tab-link" data-tab="aips-pending-review"><?php esc_html_e('Pending Review', 'ai-post-scheduler'); ?></a>
		</div>

		<!-- Tab 1 panel -->
		<div id="aips-generated-posts-tab" class="aips-tab-content active" role="tabpanel" aria-hidden="false">
			<div class="aips-content-panel">
				<!-- Filter Bar -->
				<div class="aips-filter-bar">
					<form method="get" class="search-form aips-filter-form">
						<input type="hidden" name="page" value="aips-generated-posts">
						<div class="aips-filter-left">
							<?php if (!empty($authors)): ?>
							<label class="screen-reader-text" for="aips-filter-author"><?php esc_html_e('Filter by Author:', 'ai-post-scheduler'); ?></label>
							<select name="author_id" id="aips-filter-author" class="aips-form-select">
								<option value=""><?php esc_html_e('All Authors', 'ai-post-scheduler'); ?></option>
								<?php foreach ($authors as $a): ?>
								<option value="<?php echo esc_attr($a->id); ?>" <?php selected($author_id, $a->id); ?>>
									<?php echo esc_html($a->name); ?>
								</option>
								<?php endforeach; ?>
							</select>
							<?php endif; ?>
							<?php if (!empty($templates)): ?>
							<label class="screen-reader-text" for="aips-filter-template-generated"><?php esc_html_e('Filter by Template:', 'ai-post-scheduler'); ?></label>
							<select name="template_id" id="aips-filter-template-generated" class="aips-form-select">
								<option value=""><?php esc_html_e('All Templates', 'ai-post-scheduler'); ?></option>
								<?php foreach ($templates as $template): ?>
								<option value="<?php echo esc_attr($template->id); ?>" <?php selected($template_id, $template->id); ?>>
									<?php echo esc_html($template->name); ?>
								</option>
								<?php endforeach; ?>
							</select>
							<?php endif; ?>
							<button type="submit" id="aips-filter-submit" class="aips-btn aips-btn-sm aips-btn-secondary">
								<span class="dashicons dashicons-filter"></span>
								<?php esc_html_e('Filter', 'ai-post-scheduler'); ?>
							</button>
						</div>
						<div class="aips-filter-right">
							<label class="screen-reader-text" for="post-search-input"><?php esc_html_e('Search Posts:', 'ai-post-scheduler'); ?></label>
							<input type="search" id="post-search-input" name="s" value="<?php echo esc_attr($search_query); ?>" class="aips-form-input" placeholder="<?php esc_attr_e('Search posts...', 'ai-post-scheduler'); ?>">
							<button type="submit" class="aips-btn aips-btn-sm aips-btn-secondary">
								<span class="dashicons dashicons-search"></span>
								<?php esc_html_e('Search', 'ai-post-scheduler'); ?>
							</button>
							<?php if (!empty($search_query)): ?>
							<a href="<?php echo esc_url(remove_query_arg('s')); ?>" class="aips-btn aips-btn-sm aips-btn-secondary"><?php esc_html_e('Clear', 'ai-post-scheduler'); ?></a>
							<?php endif; ?>
						</div>
					</form>
				</div>

				<!-- Generated posts table -->
				<div class="aips-panel-body no-padding">
					<?php if (!empty($posts_data)): ?>
					<table class="aips-table">
						<thead>
							<tr>
								<th scope="col"><?php esc_html_e('Title', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Source', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Scheduled', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Published', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Generated', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Actions', 'ai-post-scheduler'); ?></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($posts_data as $post_data): ?>
							<tr>
								<td>
									<a href="<?php echo esc_url($post_data['edit_link']); ?>" class="cell-primary">
										<?php echo esc_html($post_data['title']); ?>
									</a>
								</td>
								<td>
									<span class="aips-badge aips-badge-neutral">
										<?php echo esc_html($post_data['source']); ?>
									</span>
								</td>
								<td>
									<div class="cell-meta">
										<?php 
										if ($post_data['date_scheduled']) {
											echo esc_html(date_i18n(get_option('date_format') . ' ' . get_option('time_format'), strtotime($post_data['date_scheduled'])));
										} else {
											echo '—';
										}
										?>
									</div>
								</td>
								<td>
									<div class="cell-meta">
										<?php echo esc_html(date_i18n(get_option('date_format') . ' ' . get_option('time_format'), strtotime($post_data['date_published']))); ?>
									</div>
								</td>
								<td>
									<div class="cell-meta">
										<?php echo esc_html(date_i18n(get_option('date_format') . ' ' . get_option('time_format'), strtotime($post_data['date_generated']))); ?>
									</div>
								</td>
								<td>
									<div class="cell-actions">
										<a href="<?php echo esc_url($post_data['edit_link']); ?>" class="aips-btn aips-btn-sm aips-btn-secondary">
											<span class="dashicons dashicons-edit"></span>
											<?php esc_html_e('Edit', 'ai-post-scheduler'); ?>
										</a>
										<button class="aips-btn aips-btn-sm aips-btn-secondary aips-ai-edit-btn" 
										        data-post-id="<?php echo esc_attr($post_data['post_id']); ?>"
										        data-history-id="<?php echo esc_attr($post_data['history_id']); ?>"
										        title="<?php esc_attr_e('AI Edit', 'ai-post-scheduler'); ?>">
											<span class="dashicons dashicons-admin-customizer"></span>
											<?php esc_html_e('AI Edit', 'ai-post-scheduler'); ?>
										</button>
								<button class="aips-btn aips-btn-sm aips-btn-secondary aips-view-session" 
								        data-history-id="<?php echo esc_attr($post_data['history_id']); ?>"
								        title="<?php esc_attr_e('View Session', 'ai-post-scheduler'); ?>">
									<span class="dashicons dashicons-visibility"></span>
									<?php esc_html_e('View Session', 'ai-post-scheduler'); ?>
										</button>
									</div>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<?php else: ?>
					<div class="aips-empty-state">
						<div class="dashicons dashicons-admin-post aips-empty-state-icon" aria-hidden="true"></div>
						<h3 class="aips-empty-state-title"><?php esc_html_e('No Generated Posts', 'ai-post-scheduler'); ?></h3>
						<p class="aips-empty-state-description"><?php esc_html_e('No generated posts found. Start creating content by setting up templates and schedules.', 'ai-post-scheduler'); ?></p>
						<div class="aips-empty-state-actions">
							<a href="<?php echo esc_url(AIPS_Admin_Menu_Helper::get_page_url('templates')); ?>" class="aips-btn aips-btn-primary">
								<span class="dashicons dashicons-plus-alt"></span>
								<?php esc_html_e('Create Template', 'ai-post-scheduler'); ?>
							</a>
							<a href="<?php echo esc_url(AIPS_Admin_Menu_Helper::get_page_url('schedule')); ?>" class="aips-btn aips-btn-secondary">
								<span class="dashicons dashicons-calendar-alt"></span>
								<?php esc_html_e('Manage Schedules', 'ai-post-scheduler'); ?>
							</a>
						</div>
					</div>
					<?php endif; ?>
				</div>

				<!-- Table footer -->
				<div class="tablenav">
					<span class="aips-table-footer-count">
						<?php printf( esc_html( _n( '%s post', '%s posts', $history['total'], 'ai-post-scheduler' ) ), number_format_i18n( $history['total'] ) ); ?>
					</span>
					<?php if ($history['pages'] > 1): ?>
					<?php
					$current = (int) $current_page;
					$pages = (int) $history['pages'];
					$start = max(1, $current - 3);
					$end = min($pages, $current + 3);
					$base_url = AIPS_Admin_Menu_Helper::get_page_url('generated_posts');
					$build_generated_posts_page_url = static function($page_number) use ($base_url, $author_id, $template_id, $search_query) {
						return add_query_arg(array_filter(array(
							'generated_paged' => absint($page_number),
							'author_id' => $author_id ? $author_id : false,
							'template_id' => $template_id ? $template_id : false,
							's' => $search_query ? $search_query : false,
						)), $base_url);
					};
					?>
					<div class="aips-history-pagination-links">
						<?php if ($current > 1): ?>
							<a class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-prev" href="<?php echo esc_url($build_generated_posts_page_url($current - 1)); ?>" aria-label="<?php esc_attr_e('Previous page', 'ai-post-scheduler'); ?>">
								<span class="dashicons dashicons-arrow-left-alt2"></span>
							</a>
						<?php else: ?>
							<button type="button" class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-prev" disabled aria-label="<?php esc_attr_e('Previous page', 'ai-post-scheduler'); ?>">
								<span class="dashicons dashicons-arrow-left-alt2"></span>
							</button>
						<?php endif; ?>

						<span class="aips-history-page-numbers">
							<?php if ($start > 1): ?>
								<a class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-link" href="<?php echo esc_url($build_generated_posts_page_url(1)); ?>">1</a>
								<?php if ($start > 2): ?><span class="aips-history-page-ellipsis">…</span><?php endif; ?>
							<?php endif; ?>

							<?php for ($p = $start; $p <= $end; $p++): ?>
								<?php if ($p === $current): ?>
									<span class="aips-btn aips-btn-sm aips-btn-primary" aria-current="page"><?php echo esc_html($p); ?></span>
								<?php else: ?>
									<a class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-link" href="<?php echo esc_url($build_generated_posts_page_url($p)); ?>"><?php echo esc_html($p); ?></a>
								<?php endif; ?>
							<?php endfor; ?>

							<?php if ($end < $pages): ?>
								<?php if ($end < $pages - 1): ?><span class="aips-history-page-ellipsis">…</span><?php endif; ?>
								<a class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-link" href="<?php echo esc_url($build_generated_posts_page_url($pages)); ?>"><?php echo esc_html($pages); ?></a>
							<?php endif; ?>
						</span>

						<?php if ($current < $pages): ?>
							<a class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-next" href="<?php echo esc_url($build_generated_posts_page_url($current + 1)); ?>" aria-label="<?php esc_attr_e('Next page', 'ai-post-scheduler'); ?>">
								<span class="dashicons dashicons-arrow-right-alt2"></span>
							</a>
						<?php else: ?>
							<button type="button" class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-next" disabled aria-label="<?php esc_attr_e('Next page', 'ai-post-scheduler'); ?>">
								<span class="dashicons dashicons-arrow-right-alt2"></span>
							</button>
						<?php endif; ?>
					</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<!-- Tab 2 panel -->
		<div id="aips-partial-generations-tab" class="aips-tab-content" style="display:none;" role="tabpanel" aria-hidden="true">
			<div class="aips-content-panel">
				<!-- Filter Bar -->
				<div class="aips-filter-bar">
					<form method="get" class="search-form aips-filter-form">
						<input type="hidden" name="page" value="aips-generated-posts">
						<div class="aips-filter-left">
							<?php if (!empty($authors)): ?>
							<label class="screen-reader-text" for="aips-filter-author-partial"><?php esc_html_e('Filter by Author:', 'ai-post-scheduler'); ?></label>
							<select name="author_id" id="aips-filter-author-partial" class="aips-form-select">
								<option value=""><?php esc_html_e('All Authors', 'ai-post-scheduler'); ?></option>
								<?php foreach ($authors as $a): ?>
								<option value="<?php echo esc_attr($a->id); ?>" <?php selected($author_id, $a->id); ?>>
									<?php echo esc_html($a->name); ?>
								</option>
								<?php endforeach; ?>
							</select>
							<?php endif; ?>
							<?php if (!empty($templates)): ?>
							<label class="screen-reader-text" for="aips-filter-template-partial"><?php esc_html_e('Filter by Template:', 'ai-post-scheduler'); ?></label>
							<select name="template_id" id="aips-filter-template-partial" class="aips-form-select">
								<option value=""><?php esc_html_e('All Templates', 'ai-post-scheduler'); ?></option>
								<?php foreach ($templates as $template): ?>
								<option value="<?php echo esc_attr($template->id); ?>" <?php selected($template_id, $template->id); ?>>
									<?php echo esc_html($template->name); ?>
								</option>
								<?php endforeach; ?>
							</select>
							<?php endif; ?>
							<button type="submit" class="aips-btn aips-btn-sm aips-btn-secondary">
								<span class="dashicons dashicons-filter"></span>
								<?php esc_html_e('Filter', 'ai-post-scheduler'); ?>
							</button>
						</div>
						<div class="aips-filter-right">
							<label class="screen-reader-text" for="aips-partial-search-input"><?php esc_html_e('Search Posts:', 'ai-post-scheduler'); ?></label>
							<input type="search" id="aips-partial-search-input" name="s" value="<?php echo esc_attr($search_query); ?>" class="aips-form-input" placeholder="<?php esc_attr_e('Search posts...', 'ai-post-scheduler'); ?>">
							<button type="submit" class="aips-btn aips-btn-sm aips-btn-secondary">
								<span class="dashicons dashicons-search"></span>
								<?php esc_html_e('Search', 'ai-post-scheduler'); ?>
							</button>
							<?php if (!empty($search_query)): ?>
							<a href="<?php echo esc_url(remove_query_arg('s')); ?>" class="aips-btn aips-btn-sm aips-btn-secondary"><?php esc_html_e('Clear', 'ai-post-scheduler'); ?></a>
							<?php endif; ?>
						</div>
					</form>
				</div>

				<!-- Partial Generations table -->
				<div class="aips-panel-body no-padding">
					<?php if (!empty($partial_posts_data)): ?>
					<table class="aips-table">
						<thead>
							<tr>
								<th scope="col"><?php esc_html_e('Title', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Missing Components', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('State', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Source', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Status', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Updated', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Generated', 'ai-post-scheduler'); ?></th>
								<th scope="col"><?php esc_html_e('Actions', 'ai-post-scheduler'); ?></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($partial_posts_data as $post_data): ?>
							<tr>
								<td>
									<a href="<?php echo esc_url($post_data['edit_link']); ?>" class="cell-primary">
										<?php echo esc_html($post_data['title']); ?>
									</a>
								</td>
								<td>
									<?php if (!empty($post_data['missing_components'])): ?>
										<?php foreach ($post_data['missing_components'] as $component_label): ?>
										<span class="aips-badge aips-badge-warning"><?php echo esc_html($component_label); ?></span>
										<?php endforeach; ?>
									<?php else: ?>
										<span class="aips-badge aips-badge-success"><?php esc_html_e('Resolved', 'ai-post-scheduler'); ?></span>
									<?php endif; ?>
								</td>
								<td>
									<?php if (!empty($post_data['is_currently_incomplete'])): ?>
										<span class="aips-badge aips-badge-warning"><?php esc_html_e('Incomplete', 'ai-post-scheduler'); ?></span>
									<?php else: ?>
										<span class="aips-badge aips-badge-success"><?php esc_html_e('Resolved', 'ai-post-scheduler'); ?></span>
									<?php endif; ?>
								</td>
								<td>
									<span class="aips-badge aips-badge-neutral">
										<?php echo esc_html($post_data['source']); ?>
									</span>
								</td>
								<td>
									<div class="cell-meta"><?php echo esc_html($controller->format_post_status($post_data['post_status'])); ?></div>
								</td>
								<td>
									<div class="cell-meta"><?php echo esc_html(date_i18n(get_option('date_format') . ' ' . get_option('time_format'), strtotime($post_data['date_updated']))); ?></div>
								</td>
								<td>
									<div class="cell-meta"><?php echo esc_html(date_i18n(get_option('date_format') . ' ' . get_option('time_format'), strtotime($post_data['date_generated']))); ?></div>
								</td>
								<td>
									<div class="cell-actions">
										<a href="<?php echo esc_url($post_data['edit_link']); ?>" class="aips-btn aips-btn-sm aips-btn-secondary">
											<span class="dashicons dashicons-edit"></span>
											<?php esc_html_e('Edit', 'ai-post-scheduler'); ?>
										</a>
										<button class="aips-btn aips-btn-sm aips-btn-secondary aips-ai-edit-btn"
											data-post-id="<?php echo esc_attr($post_data['post_id']); ?>"
											data-history-id="<?php echo esc_attr($post_data['history_id']); ?>"
											title="<?php esc_attr_e('AI Edit', 'ai-post-scheduler'); ?>">
											<span class="dashicons dashicons-admin-customizer"></span>
											<?php esc_html_e('AI Edit', 'ai-post-scheduler'); ?>
										</button>
								<button class="aips-btn aips-btn-sm aips-btn-secondary aips-view-session"
									data-history-id="<?php echo esc_attr($post_data['history_id']); ?>"
									title="<?php esc_attr_e('View Session', 'ai-post-scheduler'); ?>">
									<span class="dashicons dashicons-visibility"></span>
									<?php esc_html_e('View Session', 'ai-post-scheduler'); ?>
										</button>
									</div>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<?php else: ?>
					<div class="aips-empty-state">
						<div class="dashicons dashicons-saved aips-empty-state-icon" aria-hidden="true"></div>
						<h3 class="aips-empty-state-title"><?php esc_html_e('No Partial Generations', 'ai-post-scheduler'); ?></h3>
						<p class="aips-empty-state-description"><?php esc_html_e('Posts with missing generated components will appear here so you can review and repair them.', 'ai-post-scheduler'); ?></p>
					</div>
					<?php endif; ?>
				</div>

				<!-- Table footer -->
				<div class="tablenav">
					<span class="aips-table-footer-count">
						<?php printf( esc_html( _n( '%s post', '%s posts', $partial_generations['total'], 'ai-post-scheduler' ) ), number_format_i18n( $partial_generations['total'] ) ); ?>
					</span>
					<?php if ($partial_generations['pages'] > 1): ?>
					<div class="tablenav-pages">
						<?php
						$page_links = paginate_links(array(
							'base' => add_query_arg('partial_paged', '%#%'),
							'format' => '',
							'prev_text' => '&laquo;',
							'next_text' => '&raquo;',
							'total' => $partial_generations['pages'],
							'current' => $partial_current_page,
							'add_fragment' => '#aips-partial-generations',
							'add_args' => array_filter(array(
								'author_id' => $author_id ? $author_id : false,
								'template_id' => $template_id ? $template_id : false,
								's' => $search_query ? $search_query : false,
							)),
						));
						if ($page_links) {
							echo wp_kses_post($page_links);
						}
						?>
					</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<!-- Tab 3 panel -->
		<div id="aips-pending-review-tab" class="aips-tab-content" style="display:none;" role="tabpanel" aria-hidden="true">
			<div class="aips-content-panel">
				<!-- Filter Bar -->
				<div class="aips-filter-bar">
					<form method="get" class="aips-post-review-filters aips-filter-form">
						<input type="hidden" name="page" value="aips-generated-posts">
						<div class="aips-filter-left">
								<?php if (!empty($templates)): ?>
							<label class="screen-reader-text" for="aips-filter-template"><?php esc_html_e('Filter by Template:', 'ai-post-scheduler'); ?></label>
							<select name="template_id" id="aips-filter-template" class="aips-form-select">
								<option value=""><?php esc_html_e('All Templates', 'ai-post-scheduler'); ?></option>
								<?php foreach ($templates as $template): ?>
								<option value="<?php echo esc_attr($template->id); ?>" <?php selected($template_id, $template->id); ?>>
									<?php echo esc_html($template->name); ?>
								</option>
								<?php endforeach; ?>
							</select>
							<button type="submit" class="aips-btn aips-btn-sm aips-btn-secondary">
								<span class="dashicons dashicons-filter"></span>
								<?php esc_html_e('Filter', 'ai-post-scheduler'); ?>
							</button>
							<?php endif; ?>
						</div>
						<div class="aips-filter-right">
							<label class="screen-reader-text" for="aips-post-search-input"><?php esc_html_e('Search Posts:', 'ai-post-scheduler'); ?></label>
							<input type="search" id="aips-post-search-input" name="s" value="<?php echo esc_attr($search_query); ?>" class="aips-form-input" placeholder="<?php esc_attr_e('Search posts...', 'ai-post-scheduler'); ?>">
							<button type="submit" id="aips-post-search-btn" class="aips-btn aips-btn-sm aips-btn-secondary">
								<span class="dashicons dashicons-search"></span>
								<?php esc_html_e('Search', 'ai-post-scheduler'); ?>
							</button>
							<?php if (!empty($search_query)): ?>
							<a href="<?php echo esc_url(remove_query_arg('s')); ?>" class="aips-btn aips-btn-sm aips-btn-secondary"><?php esc_html_e('Clear', 'ai-post-scheduler'); ?></a>
							<?php endif; ?>
						</div>
					</form>
				</div>

				<?php if (!empty($draft_posts['items'])): ?>
				<form id="aips-post-review-form" method="post">
					<!-- Bulk Actions Toolbar -->
					<div class="aips-panel-toolbar">
						<div class="aips-toolbar-left aips-btn-group aips-btn-group-inline">
							<select name="bulk_action" id="bulk-action-selector-top" class="aips-form-select" style="width: auto;">
								<option value=""><?php esc_html_e('Bulk Actions', 'ai-post-scheduler'); ?></option>
								<option value="publish"><?php esc_html_e('Publish', 'ai-post-scheduler'); ?></option>
								<option value="delete"><?php esc_html_e('Delete', 'ai-post-scheduler'); ?></option>
							</select>
							<button type="button" id="aips-bulk-action-btn" class="aips-btn aips-btn-sm aips-btn-secondary"><?php esc_html_e('Apply', 'ai-post-scheduler'); ?></button>
						</div>
						<div class="aips-toolbar-right">
							<button type="button" id="aips-reload-posts-btn" class="aips-btn aips-btn-sm aips-btn-secondary">
								<span class="dashicons dashicons-update"></span>
								<?php esc_html_e('Reload', 'ai-post-scheduler'); ?>
							</button>
						</div>
					</div>

					<div class="aips-panel-body no-padding">
						<table class="aips-table">
							<thead>
								<tr>
									<th scope="col" style="width: 30px;">
										<label class="screen-reader-text" for="cb-select-all-1"><?php esc_html_e('Select All', 'ai-post-scheduler'); ?></label>
										<input id="cb-select-all-1" type="checkbox">
									</th>
									<th scope="col"><?php esc_html_e('Post', 'ai-post-scheduler'); ?></th>
									<th scope="col"><?php esc_html_e('Source', 'ai-post-scheduler'); ?></th>
									<th scope="col"><?php esc_html_e('Created', 'ai-post-scheduler'); ?></th>
									<th scope="col"><?php esc_html_e('Modified', 'ai-post-scheduler'); ?></th>
									<th scope="col"><?php esc_html_e('Actions', 'ai-post-scheduler'); ?></th>
								</tr>
							</thead>
							<tbody>
								<?php foreach ($draft_posts['items'] as $item): ?>
								<tr data-post-id="<?php echo esc_attr($item->post_id); ?>" data-history-id="<?php echo esc_attr($item->id); ?>">
									<td>
										<label class="screen-reader-text" for="cb-select-<?php echo esc_attr($item->post_id); ?>"><?php esc_html_e('Select Post', 'ai-post-scheduler'); ?></label>
										<input id="cb-select-<?php echo esc_attr($item->post_id); ?>" type="checkbox" class="aips-post-checkbox"
											value="<?php echo esc_attr($item->post_id); ?>"
											data-post-id="<?php echo esc_attr($item->post_id); ?>"
											data-history-id="<?php echo esc_attr($item->id); ?>">
									</td>
									<td>
										<a href="<?php echo esc_url(get_edit_post_link($item->post_id)); ?>" class="cell-primary" target="_blank">
											<?php echo esc_html($item->post_title ?: $item->generated_title ?: __('Untitled', 'ai-post-scheduler')); ?>
										</a>
									</td>
									<td>
										<span class="aips-badge aips-badge-neutral">
											<?php echo esc_html($controller->format_source($item)); ?>
										</span>
									</td>
									<td>
										<div class="cell-meta">
											<?php echo esc_html(date_i18n(get_option('date_format') . ' ' . get_option('time_format'), strtotime($item->created_at))); ?>
										</div>
									</td>
									<td>
										<div class="cell-meta">
											<?php echo esc_html(date_i18n(get_option('date_format') . ' ' . get_option('time_format'), strtotime($item->post_modified))); ?>
										</div>
									</td>
									<td>
										<div class="cell-actions">
											<a href="<?php echo esc_url(get_edit_post_link($item->post_id)); ?>"
												class="aips-btn aips-btn-sm aips-btn-secondary"
												target="_blank"
												title="<?php esc_attr_e('Edit this post', 'ai-post-scheduler'); ?>">
												<span class="dashicons dashicons-edit"></span>
												<?php esc_html_e('Edit', 'ai-post-scheduler'); ?>
											</a>
											<button type="button"
												class="aips-btn aips-btn-sm aips-btn-secondary aips-preview-post"
												data-post-id="<?php echo esc_attr($item->post_id); ?>"
												title="<?php esc_attr_e('Preview this post', 'ai-post-scheduler'); ?>">
												<span class="dashicons dashicons-visibility"></span>
												<?php esc_html_e('Preview', 'ai-post-scheduler'); ?>
											</button>
											<button type="button"
												class="aips-btn aips-btn-sm aips-btn-secondary aips-ai-edit-btn"
												data-post-id="<?php echo esc_attr($item->post_id); ?>"
												data-history-id="<?php echo esc_attr($item->id); ?>"
												title="<?php esc_attr_e('AI Edit - Regenerate components', 'ai-post-scheduler'); ?>">
												<span class="dashicons dashicons-admin-customizer"></span>
												<?php esc_html_e('AI Edit', 'ai-post-scheduler'); ?>
											</button>
											<button type="button"
												class="aips-btn aips-btn-sm aips-btn-secondary aips-view-session"
												data-history-id="<?php echo esc_attr($item->id); ?>"
												title="<?php esc_attr_e('View generation session', 'ai-post-scheduler'); ?>">
												<span class="dashicons dashicons-visibility"></span>
												<?php esc_html_e('View Session', 'ai-post-scheduler'); ?>
											</button>
											<button type="button"
												class="aips-btn aips-btn-sm aips-btn-primary aips-publish-post"
												data-post-id="<?php echo esc_attr($item->post_id); ?>"
												title="<?php esc_attr_e('Publish this post', 'ai-post-scheduler'); ?>">
												<span class="dashicons dashicons-upload"></span>
												<?php esc_html_e('Publish', 'ai-post-scheduler'); ?>
											</button>
											<button type="button"
												class="aips-btn aips-btn-sm aips-btn-secondary aips-regenerate-post"
												data-history-id="<?php echo esc_attr($item->id); ?>"
												data-post-id="<?php echo esc_attr($item->post_id); ?>"
												title="<?php esc_attr_e('Regenerate this post', 'ai-post-scheduler'); ?>">
												<span class="dashicons dashicons-update"></span>
												<?php esc_html_e('Re-generate', 'ai-post-scheduler'); ?>
											</button>
											<button type="button"
												class="aips-btn aips-btn-sm aips-btn-danger aips-delete-post"
												data-post-id="<?php echo esc_attr($item->post_id); ?>"
												data-history-id="<?php echo esc_attr($item->id); ?>"
												title="<?php esc_attr_e('Delete this post', 'ai-post-scheduler'); ?>">
												<span class="dashicons dashicons-trash"></span>
												<?php esc_html_e('Delete', 'ai-post-scheduler'); ?>
											</button>
										</div>
									</td>
								</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					</div><!-- .aips-panel-body -->
				</form>
				<?php else: ?>
				<div class="aips-panel-body">
					<div class="aips-empty-state">
						<div class="dashicons dashicons-yes-alt aips-empty-state-icon" aria-hidden="true"></div>
						<h3 class="aips-empty-state-title"><?php esc_html_e('No Draft Posts', 'ai-post-scheduler'); ?></h3>
						<p class="aips-empty-state-description"><?php esc_html_e('There are no draft posts waiting for review. All generated posts have been published or deleted.', 'ai-post-scheduler'); ?></p>
						<div class="aips-empty-state-actions">
							<a href="<?php echo esc_url(AIPS_Admin_Menu_Helper::get_page_url('schedule')); ?>" class="aips-btn aips-btn-secondary">
								<span class="dashicons dashicons-calendar-alt"></span>
								<?php esc_html_e('Manage Schedules', 'ai-post-scheduler'); ?>
							</a>
						</div>
					</div>
				</div>
				<?php endif; ?>
				
				<!-- Table footer -->
				<div class="tablenav">
					<span class="aips-table-footer-count">
						<?php printf( esc_html( _n( '%d draft', '%d drafts', $draft_posts['total'], 'ai-post-scheduler' ) ), $draft_posts['total'] ); ?>
					</span>
					<?php if ($draft_posts['pages'] > 1): ?>
					<?php
					$review_base_url = AIPS_Admin_Menu_Helper::get_page_url('generated_posts');
					$build_review_page_url = static function($page_number) use ($review_base_url, $template_id, $search_query) {
						return add_query_arg(array_filter(array(
							'review_paged' => absint($page_number),
							'template_id'  => $template_id ? $template_id : false,
							's'            => $search_query ? $search_query : false,
						)), $review_base_url) . '#aips-pending-review';
					};
					$review_start = max(1, $review_current_page - 3);
					$review_end   = min($draft_posts['pages'], $review_current_page + 3);
					?>
					<div class="aips-history-pagination-links">
						<?php if ($review_current_page > 1): ?>
							<a class="aips-btn aips-btn-sm aips-btn-secondary" href="<?php echo esc_url($build_review_page_url($review_current_page - 1)); ?>" aria-label="<?php esc_attr_e('Previous page', 'ai-post-scheduler'); ?>">
								<span class="dashicons dashicons-arrow-left-alt2"></span>
							</a>
						<?php else: ?>
							<button type="button" class="aips-btn aips-btn-sm aips-btn-secondary" disabled aria-label="<?php esc_attr_e('Previous page', 'ai-post-scheduler'); ?>">
								<span class="dashicons dashicons-arrow-left-alt2"></span>
							</button>
						<?php endif; ?>

						<span class="aips-history-page-numbers">
							<?php if ($review_start > 1): ?>
								<a class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-link" href="<?php echo esc_url($build_review_page_url(1)); ?>">1</a>
								<?php if ($review_start > 2): ?><span class="aips-history-page-ellipsis">…</span><?php endif; ?>
							<?php endif; ?>

							<?php for ($p = $review_start; $p <= $review_end; $p++): ?>
								<?php if ($p === $review_current_page): ?>
									<span class="aips-btn aips-btn-sm aips-btn-primary" aria-current="page"><?php echo esc_html($p); ?></span>
								<?php else: ?>
									<a class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-link" href="<?php echo esc_url($build_review_page_url($p)); ?>"><?php echo esc_html($p); ?></a>
								<?php endif; ?>
							<?php endfor; ?>

							<?php if ($review_end < $draft_posts['pages']): ?>
								<?php if ($review_end < $draft_posts['pages'] - 1): ?><span class="aips-history-page-ellipsis">…</span><?php endif; ?>
								<a class="aips-btn aips-btn-sm aips-btn-secondary aips-history-page-link" href="<?php echo esc_url($build_review_page_url($draft_posts['pages'])); ?>"><?php echo esc_html($draft_posts['pages']); ?></a>
							<?php endif; ?>
						</span>

						<?php if ($review_current_page < $draft_posts['pages']): ?>
							<a class="aips-btn aips-btn-sm aips-btn-secondary" href="<?php echo esc_url($build_review_page_url($review_current_page + 1)); ?>" aria-label="<?php esc_attr_e('Next page', 'ai-post-scheduler'); ?>">
								<span class="dashicons dashicons-arrow-right-alt2"></span>
							</a>
						<?php else: ?>
							<button type="button" class="aips-btn aips-btn-sm aips-btn-secondary" disabled aria-label="<?php esc_attr_e('Next page', 'ai-post-scheduler'); ?>">
								<span class="dashicons dashicons-arrow-right-alt2"></span>
							</button>
						<?php endif; ?>
					</div>
					<?php endif; ?>
				</div>
			</div><!-- .aips-content-panel -->
		</div><!-- .aips-tab-content -->
	</div>
</div>

<!-- Post Preview Modal -->
<div id="aips-post-preview-modal" class="aips-modal" style="display: none;">
	<div class="aips-modal-overlay"></div>
	<div class="aips-modal-content" style="width: 90%; max-width: 1200px; height: 90vh;">
		<div class="aips-modal-header">
			<h2><?php esc_html_e('Post Preview', 'ai-post-scheduler'); ?></h2>
			<button type="button" class="aips-modal-close" aria-label="<?php esc_attr_e('Close', 'ai-post-scheduler'); ?>">
				<span class="dashicons dashicons-no-alt"></span>
			</button>
		</div>
		<div class="aips-modal-body" style="height: calc(100% - 60px); padding: 0;">
			<div id="aips-preview-content-container" style="padding: 30px; height: 100%; overflow-y: auto; box-sizing: border-box; display: none;"></div>
			<iframe id="aips-post-preview-iframe" src="" style="width: 100%; height: 100%; border: none; display: none;"></iframe>
		</div>
	</div>
</div>

<?php
// Include the View Session modal partial
include AIPS_PLUGIN_DIR . 'templates/partials/view-session-modal.php';

// Include the AI Edit modal partial
include AIPS_PLUGIN_DIR . 'templates/partials/ai-edit-modal.php';
?>