<?php
/**
 * Generated Posts Admin Template
 *
 * Displays all posts generated by the AI Post Scheduler plugin with status filtering.
 *
 * @package AI_Post_Scheduler
 * @since 2.0.0
 */

if (!defined('ABSPATH')) {
	exit;
}
?>

<div class="wrap aips-wrap">
	<h1><?php esc_html_e('Generated Posts', 'ai-post-scheduler'); ?></h1>
	<p><?php esc_html_e('View and manage all posts generated by the AI Post Scheduler plugin.', 'ai-post-scheduler'); ?></p>

	<!-- Status Filter Pills -->
	<div class="aips-status-filters" style="margin: 20px 0;">
		<?php
		$base_url = admin_url('admin.php?page=aips-generated-posts');
		$filters = array(
			'all' => sprintf(__('All (%d)', 'ai-post-scheduler'), $all_count),
			'draft' => sprintf(__('Draft (%d)', 'ai-post-scheduler'), $draft_count),
			'published' => sprintf(__('Published (%d)', 'ai-post-scheduler'), $published_count),
		);
		
		foreach ($filters as $filter_key => $filter_label) {
			$filter_url = add_query_arg('status', $filter_key, $base_url);
			if ($search_query) {
				$filter_url = add_query_arg('s', $search_query, $filter_url);
			}
			if ($template_id) {
				$filter_url = add_query_arg('template_id', $template_id, $filter_url);
			}
			
			$active_class = ($status_filter === $filter_key) ? 'current' : '';
			?>
			<a href="<?php echo esc_url($filter_url); ?>" class="<?php echo esc_attr($active_class); ?>">
				<?php echo esc_html($filter_label); ?>
			</a>
			<?php
		}
		?>
	</div>

	<!-- Filters and Search -->
	<div class="tablenav top">
		<div class="alignleft actions">
			<?php if (!empty($templates) && $status_filter === 'draft'): ?>
			<form method="get" style="display: inline-block;">
				<input type="hidden" name="page" value="aips-generated-posts">
				<input type="hidden" name="status" value="<?php echo esc_attr($status_filter); ?>">
				<?php if ($search_query): ?>
				<input type="hidden" name="s" value="<?php echo esc_attr($search_query); ?>">
				<?php endif; ?>
				<select name="template_id" id="aips-filter-template">
					<option value=""><?php esc_html_e('All Templates', 'ai-post-scheduler'); ?></option>
					<?php foreach ($templates as $template): ?>
					<option value="<?php echo esc_attr($template->id); ?>" <?php selected($template_id, $template->id); ?>>
						<?php echo esc_html($template->name); ?>
					</option>
					<?php endforeach; ?>
				</select>
				<input type="submit" class="button" value="<?php esc_attr_e('Filter', 'ai-post-scheduler'); ?>">
			</form>
			<?php endif; ?>
		</div>
		<div class="alignright actions">
			<form method="get" style="display: inline-block;">
				<input type="hidden" name="page" value="aips-generated-posts">
				<input type="hidden" name="status" value="<?php echo esc_attr($status_filter); ?>">
				<?php if ($template_id): ?>
				<input type="hidden" name="template_id" value="<?php echo esc_attr($template_id); ?>">
				<?php endif; ?>
				<p class="search-box" style="margin: 0;">
					<label class="screen-reader-text" for="post-search-input"><?php esc_html_e('Search Posts:', 'ai-post-scheduler'); ?></label>
					<input type="search" id="post-search-input" name="s" value="<?php echo esc_attr($search_query); ?>" placeholder="<?php esc_attr_e('Search posts...', 'ai-post-scheduler'); ?>">
					<input type="submit" id="search-submit" class="button" value="<?php esc_attr_e('Search', 'ai-post-scheduler'); ?>">
				</p>
			</form>
		</div>
	</div>
	
	<!-- Posts Table -->
	<?php if (!empty($posts_data)): ?>
	<form id="aips-posts-form" method="post">
		<?php if ($status_filter === 'draft'): ?>
		<div class="tablenav top">
			<div class="alignleft actions bulkactions">
				<select name="bulk_action" id="bulk-action-selector-top">
					<option value=""><?php esc_html_e('Bulk Actions', 'ai-post-scheduler'); ?></option>
					<option value="publish"><?php esc_html_e('Publish', 'ai-post-scheduler'); ?></option>
					<option value="delete"><?php esc_html_e('Delete', 'ai-post-scheduler'); ?></option>
				</select>
				<button type="button" id="aips-bulk-action-btn" class="button action"><?php esc_html_e('Apply', 'ai-post-scheduler'); ?></button>
			</div>
		</div>
		<?php endif; ?>
		
		<table class="wp-list-table widefat fixed striped">
			<thead>
				<tr>
					<?php if ($status_filter === 'draft'): ?>
					<th id="cb" class="manage-column column-cb check-column">
						<label class="screen-reader-text" for="cb-select-all-1"><?php esc_html_e('Select All', 'ai-post-scheduler'); ?></label>
						<input id="cb-select-all-1" type="checkbox">
					</th>
					<?php endif; ?>
					<th scope="col"><?php esc_html_e('Title', 'ai-post-scheduler'); ?></th>
					<th scope="col"><?php esc_html_e('Status', 'ai-post-scheduler'); ?></th>
					<th scope="col"><?php esc_html_e('Source', 'ai-post-scheduler'); ?></th>
					<?php if ($status_filter === 'draft'): ?>
					<th scope="col" style="width: 60px; text-align: center;"><?php esc_html_e('Preview', 'ai-post-scheduler'); ?></th>
					<?php endif; ?>
					<th scope="col"><?php esc_html_e('Date Created', 'ai-post-scheduler'); ?></th>
					<?php if ($status_filter !== 'draft'): ?>
					<th scope="col"><?php esc_html_e('Date Published', 'ai-post-scheduler'); ?></th>
					<?php endif; ?>
					<th scope="col"><?php esc_html_e('Actions', 'ai-post-scheduler'); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($posts_data as $post): ?>
				<tr data-post-id="<?php echo esc_attr($post['post_id']); ?>" data-history-id="<?php echo esc_attr($post['history_id']); ?>">
					<?php if ($status_filter === 'draft'): ?>
					<th scope="row" class="check-column">
						<label class="screen-reader-text" for="cb-select-<?php echo esc_attr($post['post_id']); ?>"><?php esc_html_e('Select Post', 'ai-post-scheduler'); ?></label>
						<input id="cb-select-<?php echo esc_attr($post['post_id']); ?>" type="checkbox" class="aips-post-checkbox" 
							   value="<?php echo esc_attr($post['post_id']); ?>" 
							   data-post-id="<?php echo esc_attr($post['post_id']); ?>"
							   data-history-id="<?php echo esc_attr($post['history_id']); ?>">
					</th>
					<?php endif; ?>
					<td class="column-title">
						<strong>
							<a href="<?php echo esc_url($post['edit_link']); ?>" target="_blank">
								<?php echo esc_html($post['title']); ?>
							</a>
						</strong>
					</td>
					<td class="column-status">
						<?php
						$status_label = $post['status'];
						$status_class = 'aips-status-badge';
						if ($post['status'] === 'publish') {
							$status_label = __('Published', 'ai-post-scheduler');
							$status_class .= ' aips-status-published';
						} elseif ($post['status'] === 'draft') {
							$status_label = __('Draft', 'ai-post-scheduler');
							$status_class .= ' aips-status-draft';
						} elseif ($post['status'] === 'pending') {
							$status_label = __('Pending', 'ai-post-scheduler');
							$status_class .= ' aips-status-pending';
						}
						?>
						<span class="<?php echo esc_attr($status_class); ?>"><?php echo esc_html($status_label); ?></span>
					</td>
					<td class="column-source">
						<?php echo esc_html($post['source']); ?>
					</td>
					<?php if ($status_filter === 'draft'): ?>
					<td class="column-preview" style="text-align: center;">
						<span class="aips-preview-trigger dashicons dashicons-visibility" 
							  data-post-id="<?php echo esc_attr($post['post_id']); ?>"
							  title="<?php esc_attr_e('Preview this post', 'ai-post-scheduler'); ?>"
							  style="cursor: pointer; font-size: 20px; color: #2271b1;">
						</span>
					</td>
					<?php endif; ?>
					<td class="column-date">
						<?php echo esc_html(date_i18n(get_option('date_format'), strtotime($post['date_generated']))); ?>
					</td>
					<?php if ($status_filter !== 'draft'): ?>
					<td class="column-date-published">
						<?php 
						if ($post['status'] === 'publish') {
							echo esc_html(date_i18n(get_option('date_format'), strtotime($post['date_published'])));
						} else {
							echo '—';
						}
						?>
					</td>
					<?php endif; ?>
					<td class="column-actions">
						<div class="aips-action-buttons">
							<a href="<?php echo esc_url($post['edit_link']); ?>" 
							   class="button button-small" 
							   target="_blank"
							   title="<?php esc_attr_e('Edit this post', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('Edit', 'ai-post-scheduler'); ?>
							</a>
							<button type="button" 
									class="button button-small aips-view-session" 
									data-history-id="<?php echo esc_attr($post['history_id']); ?>"
									title="<?php esc_attr_e('View generation session', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('View Session', 'ai-post-scheduler'); ?>
							</button>
							<?php if ($status_filter === 'draft'): ?>
							<button type="button" 
									class="button button-primary button-small aips-publish-post" 
									data-post-id="<?php echo esc_attr($post['post_id']); ?>"
									title="<?php esc_attr_e('Publish this post', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('Publish', 'ai-post-scheduler'); ?>
							</button>
							<button type="button" 
									class="button button-small aips-regenerate-post" 
									data-history-id="<?php echo esc_attr($post['history_id']); ?>"
									data-post-id="<?php echo esc_attr($post['post_id']); ?>"
									title="<?php esc_attr_e('Regenerate this post', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('Re-generate', 'ai-post-scheduler'); ?>
							</button>
							<button type="button" 
									class="button button-small button-link-delete aips-delete-post" 
									data-post-id="<?php echo esc_attr($post['post_id']); ?>"
									data-history-id="<?php echo esc_attr($post['history_id']); ?>"
									title="<?php esc_attr_e('Delete this post', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('Delete', 'ai-post-scheduler'); ?>
							</button>
							<?php endif; ?>
						</div>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		
		<!-- Pagination -->
		<?php if ($total_pages > 1): ?>
		<div class="tablenav bottom">
			<div class="tablenav-pages">
				<span class="displaying-num">
					<?php printf(
						esc_html(_n('%d item', '%d items', $total_items, 'ai-post-scheduler')),
						$total_items
					); ?>
				</span>
				<span class="pagination-links">
					<?php
					$page_links = paginate_links(array(
						'base' => add_query_arg('paged', '%#%'),
						'format' => '',
						'prev_text' => '&laquo;',
						'next_text' => '&raquo;',
						'total' => $total_pages,
						'current' => $current_page,
					));
					if ($page_links) {
						echo wp_kses_post($page_links);
					}
					?>
				</span>
			</div>
		</div>
		<?php endif; ?>
	</form>
	
	<?php else: ?>
	<div class="aips-empty-state" style="text-align: center; padding: 40px; background: #fff; border: 1px solid #c3c4c7; margin-top: 20px;">
		<span class="dashicons dashicons-yes-alt" aria-hidden="true" style="font-size: 48px; color: #2271b1;"></span>
		<h3><?php esc_html_e('No Posts Found', 'ai-post-scheduler'); ?></h3>
		<p>
			<?php 
			if ($status_filter === 'draft') {
				esc_html_e('There are no draft posts. All generated posts have been published or deleted.', 'ai-post-scheduler');
			} elseif ($status_filter === 'published') {
				esc_html_e('No published posts found.', 'ai-post-scheduler');
			} else {
				esc_html_e('No posts have been generated yet.', 'ai-post-scheduler');
			}
			?>
		</p>
	</div>
	<?php endif; ?>
</div>

<!-- Post Preview Modal -->
<div id="aips-post-preview-modal" class="aips-modal" style="display: none;">
	<div class="aips-modal-overlay"></div>
	<div class="aips-modal-content" style="width: 90%; max-width: 1200px; height: 90vh;">
		<div class="aips-modal-header">
			<h2><?php esc_html_e('Post Preview', 'ai-post-scheduler'); ?></h2>
			<button type="button" class="aips-modal-close" aria-label="<?php esc_attr_e('Close', 'ai-post-scheduler'); ?>">
				<span class="dashicons dashicons-no-alt"></span>
			</button>
		</div>
		<div class="aips-modal-body" style="height: calc(100% - 60px); padding: 0;">
			<iframe id="aips-post-preview-iframe" src="" style="width: 100%; height: 100%; border: none;"></iframe>
		</div>
	</div>
</div>

<?php
// Include the View Session modal partial
include AIPS_PLUGIN_DIR . 'templates/partials/view-session-modal.php';
?>

<style>
.aips-status-filters a {
	display: inline-block;
	padding: 8px 15px;
	margin-right: 5px;
	background: #f0f0f1;
	border: 1px solid #c3c4c7;
	border-radius: 3px;
	text-decoration: none;
	color: #2c3338;
}

.aips-status-filters a.current {
	background: #2271b1;
	color: #fff;
	border-color: #2271b1;
	font-weight: 600;
}

.aips-status-filters a:hover:not(.current) {
	background: #e5e5e5;
}

.aips-status-badge {
	display: inline-block;
	padding: 3px 8px;
	border-radius: 3px;
	font-size: 12px;
	font-weight: 600;
}

.aips-status-draft {
	background: #fcf9e8;
	color: #8a6116;
	border: 1px solid #f0e5c3;
}

.aips-status-published {
	background: #edfaef;
	color: #1e6927;
	border: 1px solid #c6e9c9;
}

.aips-status-pending {
	background: #f0f6fc;
	color: #2c5f8d;
	border: 1px solid #c5d9ed;
}
</style>