<?php
if (!defined('ABSPATH')) {
	exit;
}

// Use the globally-initialized Post Review handler to avoid duplicate AJAX registration
global $aips_post_review_handler;
if (!isset($aips_post_review_handler) && !isset($post_review_handler)) {
	// Fallback: use repository directly (AJAX handlers already registered in main init)
	$post_review_data_source = new AIPS_Post_Review_Repository();
} elseif (isset($post_review_handler)) {
	// Use the handler passed from render method
	$post_review_data_source = $post_review_handler;
} else {
	// Use the global handler
	$post_review_data_source = $aips_post_review_handler;
}

// Get filter parameters
$current_page = isset($_GET['paged']) ? absint($_GET['paged']) : 1;
$search_query = isset($_GET['s']) ? sanitize_text_field($_GET['s']) : '';
$template_id = isset($_GET['template_id']) ? absint($_GET['template_id']) : 0;

// Get draft posts
$draft_posts = $post_review_data_source->get_draft_posts(array(
	'page' => $current_page,
	'search' => $search_query,
	'template_id' => $template_id,
));

// Get templates for filter dropdown
$template_repository = new AIPS_Template_Repository();
$templates = $template_repository->get_all();
?>

<div class="wrap aips-wrap">
	<div class="aips-page-container">
		<!-- Page Header -->
		<div class="aips-page-header">
			<div class="aips-page-header-top">
				<div>
					<h1 class="aips-page-title"><?php esc_html_e('Post Review', 'ai-post-scheduler'); ?></h1>
					<p class="aips-page-description">
						<?php esc_html_e('Review and manage draft posts generated by AI Post Scheduler before publishing.', 'ai-post-scheduler'); ?>
					</p>
				</div>
			</div>
		</div>

		<!-- Stats Summary -->
		<?php if (!empty($draft_posts['items'])): ?>
		<div class="aips-stats-grid aips-stats-grid-4">
			<div class="aips-stat-card">
				<div class="aips-stat-icon aips-stat-icon-info">
					<span class="dashicons dashicons-media-document"></span>
				</div>
				<div class="aips-stat-content">
					<div class="aips-stat-value" id="aips-draft-count"><?php echo esc_html($draft_posts['total']); ?></div>
					<div class="aips-stat-label"><?php esc_html_e('Draft Posts', 'ai-post-scheduler'); ?></div>
				</div>
			</div>
		</div>
		<?php endif; ?>

		<!-- Content Panel -->
		<div class="aips-content-panel">
			<!-- Filter Bar -->
			<form method="get" class="aips-filter-bar">
				<input type="hidden" name="page" value="aips-post-review">
				
				<div class="aips-filter-left">
					<?php if (!empty($templates)): ?>
					<select name="template_id" id="aips-filter-template" class="aips-form-select">
						<option value=""><?php esc_html_e('All Templates', 'ai-post-scheduler'); ?></option>
						<?php foreach ($templates as $template): ?>
						<option value="<?php echo esc_attr($template->id); ?>" <?php selected($template_id, $template->id); ?>>
							<?php echo esc_html($template->name); ?>
						</option>
						<?php endforeach; ?>
					</select>
					<button type="submit" class="aips-btn aips-btn-secondary"><?php esc_html_e('Filter', 'ai-post-scheduler'); ?></button>
					<?php endif; ?>
				</div>
				
				<div class="aips-filter-right">
					<label class="screen-reader-text" for="aips-post-search-input"><?php esc_html_e('Search Posts:', 'ai-post-scheduler'); ?></label>
					<input type="search" id="aips-post-search-input" name="s" class="aips-form-input" value="<?php echo esc_attr($search_query); ?>" placeholder="<?php esc_attr_e('Search posts...', 'ai-post-scheduler'); ?>">
					<button type="submit" id="aips-post-search-btn" class="aips-btn aips-btn-secondary"><?php esc_html_e('Search', 'ai-post-scheduler'); ?></button>
					<?php if (!empty($search_query)): ?>
						<a href="<?php echo esc_url(remove_query_arg('s')); ?>" class="aips-btn aips-btn-secondary"><?php esc_html_e('Clear', 'ai-post-scheduler'); ?></a>
					<?php endif; ?>
				</div>
			</form>
	
			<?php if (!empty($draft_posts['items'])): ?>
			<!-- Bulk Actions Toolbar -->
			<form id="aips-post-review-form" method="post">
				<div class="aips-bulk-actions-bar">
					<div class="aips-bulk-actions-left">
						<select name="bulk_action" id="bulk-action-selector-top" class="aips-form-select">
							<option value=""><?php esc_html_e('Bulk Actions', 'ai-post-scheduler'); ?></option>
							<option value="publish"><?php esc_html_e('Publish', 'ai-post-scheduler'); ?></option>
							<option value="delete"><?php esc_html_e('Delete', 'ai-post-scheduler'); ?></option>
						</select>
						<button type="button" id="aips-bulk-action-btn" class="aips-btn aips-btn-secondary"><?php esc_html_e('Apply', 'ai-post-scheduler'); ?></button>
					</div>
					<div class="aips-bulk-actions-right">
						<button type="button" class="aips-btn aips-btn-secondary" id="aips-reload-posts-btn">
							<span class="dashicons dashicons-update"></span>
							<?php esc_html_e('Reload', 'ai-post-scheduler'); ?>
						</button>
					</div>
				</div>
				
				<!-- Table -->
				<div class="aips-panel-body no-padding">
					<table class="aips-table aips-post-review-table">
						<thead>
							<tr>
								<td id="cb" class="column-cb check-column">
									<label class="screen-reader-text" for="cb-select-all-1"><?php esc_html_e('Select All', 'ai-post-scheduler'); ?></label>
									<input id="cb-select-all-1" type="checkbox">
								</td>
								<th class="column-title"><?php esc_html_e('Post Title', 'ai-post-scheduler'); ?></th>
								<th class="column-template"><?php esc_html_e('Template', 'ai-post-scheduler'); ?></th>
								<th class="column-date"><?php esc_html_e('Created', 'ai-post-scheduler'); ?></th>
								<th class="column-actions"><?php esc_html_e('Actions', 'ai-post-scheduler'); ?></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($draft_posts['items'] as $item): ?>
							<tr data-post-id="<?php echo esc_attr($item->post_id); ?>" data-history-id="<?php echo esc_attr($item->id); ?>">
								<th scope="row" class="check-column">
									<label class="screen-reader-text" for="cb-select-<?php echo esc_attr($item->post_id); ?>"><?php esc_html_e('Select Post', 'ai-post-scheduler'); ?></label>
									<input id="cb-select-<?php echo esc_attr($item->post_id); ?>" type="checkbox" class="aips-post-checkbox" 
										   value="<?php echo esc_attr($item->post_id); ?>" 
										   data-post-id="<?php echo esc_attr($item->post_id); ?>"
										   data-history-id="<?php echo esc_attr($item->id); ?>">
								</th>
								<td class="column-title">
									<div class="aips-table-primary">
										<strong>
											<a href="<?php echo esc_url(get_edit_post_link($item->post_id)); ?>" target="_blank">
												<?php echo esc_html($item->post_title ?: $item->generated_title ?: __('Untitled', 'ai-post-scheduler')); ?>
											</a>
										</strong>
									</div>
									<div class="aips-table-meta">
										<?php printf(
											esc_html__('Modified: %s', 'ai-post-scheduler'),
											esc_html(date_i18n(get_option('date_format'), strtotime($item->post_modified)))
										); ?>
									</div>
								</td>
								<td class="column-template">
									<?php if ($item->template_name): ?>
										<span class="aips-badge aips-badge-info"><?php echo esc_html($item->template_name); ?></span>
									<?php else: ?>
										<span class="aips-table-meta">-</span>
									<?php endif; ?>
								</td>
								<td class="column-date">
									<div class="aips-table-meta">
										<?php echo esc_html(date_i18n(get_option('date_format'), strtotime($item->created_at))); ?>
									</div>
								</td>
								<td class="column-actions">
									<div class="aips-action-buttons">
										<a href="<?php echo esc_url(get_edit_post_link($item->post_id)); ?>" 
										   class="aips-btn aips-btn-sm" 
										   target="_blank"
										   title="<?php esc_attr_e('Edit this post', 'ai-post-scheduler'); ?>">
											<span class="dashicons dashicons-edit"></span>
										</a>
										<button type="button" 
												class="aips-btn aips-btn-sm aips-view-session" 
												data-history-id="<?php echo esc_attr($item->id); ?>"
												title="<?php esc_attr_e('View generation session', 'ai-post-scheduler'); ?>">
											<span class="dashicons dashicons-visibility"></span>
										</button>
										<button type="button" 
												class="aips-btn aips-btn-sm aips-btn-primary aips-publish-post" 
												data-post-id="<?php echo esc_attr($item->post_id); ?>"
												title="<?php esc_attr_e('Publish this post', 'ai-post-scheduler'); ?>">
											<span class="dashicons dashicons-yes"></span>
										</button>
										<button type="button" 
												class="aips-btn aips-btn-sm aips-regenerate-post" 
												data-history-id="<?php echo esc_attr($item->id); ?>"
												data-post-id="<?php echo esc_attr($item->post_id); ?>"
												title="<?php esc_attr_e('Regenerate this post', 'ai-post-scheduler'); ?>">
											<span class="dashicons dashicons-update"></span>
										</button>
										<button type="button" 
												class="aips-btn aips-btn-sm aips-btn-danger aips-delete-post" 
												data-post-id="<?php echo esc_attr($item->post_id); ?>"
												data-history-id="<?php echo esc_attr($item->id); ?>"
												title="<?php esc_attr_e('Delete this post', 'ai-post-scheduler'); ?>">
											<span class="dashicons dashicons-trash"></span>
										</button>
									</div>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
		
				<?php if ($draft_posts['pages'] > 1): ?>
				<!-- Pagination -->
				<div class="aips-pagination">
					<span class="aips-pagination-info">
						<?php printf(
							esc_html(_n('%d item', '%d items', $draft_posts['total'], 'ai-post-scheduler')),
							$draft_posts['total']
						); ?>
					</span>
					<div class="aips-pagination-links">
						<?php
						$base_url = admin_url('admin.php?page=aips-post-review');
						if ($template_id) {
							$base_url .= '&template_id=' . $template_id;
						}
						if ($search_query) {
							$base_url .= '&s=' . urlencode($search_query);
						}
						
						if ($current_page > 1): ?>
						<a class="aips-btn aips-btn-sm" href="<?php echo esc_url($base_url . '&paged=' . ($current_page - 1)); ?>">
							<span class="screen-reader-text"><?php esc_html_e('Previous page', 'ai-post-scheduler'); ?></span>
							<span aria-hidden="true">&lsaquo;</span>
						</a>
						<?php endif; ?>
						
						<span class="aips-pagination-current">
							<?php echo esc_html($current_page); ?>
							<?php esc_html_e('of', 'ai-post-scheduler'); ?>
							<?php echo esc_html($draft_posts['pages']); ?>
						</span>
						
						<?php if ($current_page < $draft_posts['pages']): ?>
						<a class="aips-btn aips-btn-sm" href="<?php echo esc_url($base_url . '&paged=' . ($current_page + 1)); ?>">
							<span class="screen-reader-text"><?php esc_html_e('Next page', 'ai-post-scheduler'); ?></span>
							<span aria-hidden="true">&rsaquo;</span>
						</a>
						<?php endif; ?>
					</div>
				</div>
				<?php endif; ?>
			</form>
			
			<?php else: ?>
			<!-- Empty State -->
			<div class="aips-empty-state">
				<div class="aips-empty-icon">
					<span class="dashicons dashicons-yes-alt"></span>
				</div>
				<h3 class="aips-empty-title"><?php esc_html_e('No Draft Posts', 'ai-post-scheduler'); ?></h3>
				<p class="aips-empty-description"><?php esc_html_e('There are no draft posts waiting for review. All generated posts have been published or deleted.', 'ai-post-scheduler'); ?></p>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>

<?php
// Include the View Session modal partial
include AIPS_PLUGIN_DIR . 'templates/partials/view-session-modal.php';
?>
