<?php
if (!defined('ABSPATH')) {
	exit;
}

// Use the globally-initialized Post Review handler to avoid duplicate AJAX registration
global $aips_post_review_handler;
if (!isset($aips_post_review_handler) && !isset($post_review_handler)) {
	// Fallback: use repository directly (AJAX handlers already registered in main init)
	$post_review_data_source = new AIPS_Post_Review_Repository();
} elseif (isset($post_review_handler)) {
	// Use the handler passed from render method
	$post_review_data_source = $post_review_handler;
} else {
	// Use the global handler
	$post_review_data_source = $aips_post_review_handler;
}

// Get filter parameters
$current_page = isset($_GET['paged']) ? absint($_GET['paged']) : 1;
$search_query = isset($_GET['s']) ? sanitize_text_field($_GET['s']) : '';
$template_id = isset($_GET['template_id']) ? absint($_GET['template_id']) : 0;

// Get draft posts
$draft_posts = $post_review_data_source->get_draft_posts(array(
	'page' => $current_page,
	'search' => $search_query,
	'template_id' => $template_id,
));

// Get templates for filter dropdown
$template_repository = new AIPS_Template_Repository();
$templates = $template_repository->get_all();
?>

<div class="wrap">
	<h1 class="wp-heading-inline"><?php esc_html_e('Post Review', 'ai-post-scheduler'); ?></h1>
	<hr class="wp-header-end">
	
	<p class="description">
		<?php esc_html_e('Review and manage draft posts generated by AI Post Scheduler before publishing them.', 'ai-post-scheduler'); ?>
	</p>
	
	<div class="aips-post-review-stats">
		<div class="aips-stat-inline">
			<span class="aips-stat-label"><?php esc_html_e('Draft Posts:', 'ai-post-scheduler'); ?></span>
			<span class="aips-stat-value" id="aips-draft-count"><?php echo esc_html($draft_posts['total']); ?></span>
		</div>
	</div>
	
	<form method="get" class="aips-post-review-filters">
		<input type="hidden" name="page" value="aips-post-review">
		
		<p class="search-box">
			<label class="screen-reader-text" for="aips-post-search-input"><?php esc_html_e('Search Posts:', 'ai-post-scheduler'); ?></label>
			<input type="search" id="aips-post-search-input" name="s" value="<?php echo esc_attr($search_query); ?>" placeholder="<?php esc_attr_e('Search posts...', 'ai-post-scheduler'); ?>">
			<input type="submit" id="aips-post-search-btn" class="button" value="<?php esc_attr_e('Search', 'ai-post-scheduler'); ?>">
			<?php if (!empty($search_query)): ?>
				<a href="<?php echo esc_url(remove_query_arg('s')); ?>" class="button"><?php esc_html_e('Clear', 'ai-post-scheduler'); ?></a>
			<?php endif; ?>
		</p>
		
		<?php if (!empty($templates)): ?>
		<div class="alignleft actions">
			<select name="template_id" id="aips-filter-template">
				<option value=""><?php esc_html_e('All Templates', 'ai-post-scheduler'); ?></option>
				<?php foreach ($templates as $template): ?>
				<option value="<?php echo esc_attr($template->id); ?>" <?php selected($template_id, $template->id); ?>>
					<?php echo esc_html($template->name); ?>
				</option>
				<?php endforeach; ?>
			</select>
			<input type="submit" class="button" value="<?php esc_attr_e('Filter', 'ai-post-scheduler'); ?>">
		</div>
		<?php endif; ?>
	</form>
	
	<?php if (!empty($draft_posts['items'])): ?>
	<form id="aips-post-review-form" method="post">
		<div class="tablenav top">
			<div class="alignleft actions bulkactions">
				<select name="bulk_action" id="bulk-action-selector-top">
					<option value=""><?php esc_html_e('Bulk Actions', 'ai-post-scheduler'); ?></option>
					<option value="publish"><?php esc_html_e('Publish', 'ai-post-scheduler'); ?></option>
					<option value="delete"><?php esc_html_e('Delete', 'ai-post-scheduler'); ?></option>
				</select>
				<button type="button" id="aips-bulk-action-btn" class="button action"><?php esc_html_e('Apply', 'ai-post-scheduler'); ?></button>
			</div>
			<div class="alignright">
				<button type="button" class="button" id="aips-reload-posts-btn"><?php esc_html_e('Reload', 'ai-post-scheduler'); ?></button>
			</div>
		</div>
		
		<table class="wp-list-table widefat fixed striped aips-post-review-table">
			<thead>
				<tr>
					<td id="cb" class="manage-column column-cb check-column">
						<label class="screen-reader-text" for="cb-select-all-1"><?php esc_html_e('Select All', 'ai-post-scheduler'); ?></label>
						<input id="cb-select-all-1" type="checkbox">
					</td>
					<th class="column-title"><?php esc_html_e('Post Title', 'ai-post-scheduler'); ?></th>
					<th class="column-template"><?php esc_html_e('Template', 'ai-post-scheduler'); ?></th>
					<th class="column-date"><?php esc_html_e('Created', 'ai-post-scheduler'); ?></th>
					<th class="column-modified"><?php esc_html_e('Modified', 'ai-post-scheduler'); ?></th>
					<th class="column-actions"><?php esc_html_e('Actions', 'ai-post-scheduler'); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($draft_posts['items'] as $item): ?>
				<tr data-post-id="<?php echo esc_attr($item->post_id); ?>" data-history-id="<?php echo esc_attr($item->id); ?>">
					<th scope="row" class="check-column">
						<label class="screen-reader-text" for="cb-select-<?php echo esc_attr($item->post_id); ?>"><?php esc_html_e('Select Post', 'ai-post-scheduler'); ?></label>
						<input id="cb-select-<?php echo esc_attr($item->post_id); ?>" type="checkbox" class="aips-post-checkbox" 
							   value="<?php echo esc_attr($item->post_id); ?>" 
							   data-post-id="<?php echo esc_attr($item->post_id); ?>"
							   data-history-id="<?php echo esc_attr($item->id); ?>">
					</th>
					<td class="column-title">
						<strong>
							<a href="<?php echo esc_url(get_edit_post_link($item->post_id)); ?>" target="_blank">
								<?php echo esc_html($item->post_title ?: $item->generated_title ?: __('Untitled', 'ai-post-scheduler')); ?>
							</a>
						</strong>
					</td>
					<td class="column-template">
						<?php echo esc_html($item->template_name ?: '-'); ?>
					</td>
					<td class="column-date">
						<?php echo esc_html(date_i18n(get_option('date_format'), strtotime($item->created_at))); ?>
					</td>
					<td class="column-modified">
						<?php echo esc_html(date_i18n(get_option('date_format'), strtotime($item->post_modified))); ?>
					</td>
					<td class="column-actions">
						<div class="aips-action-buttons">
							<a href="<?php echo esc_url(get_edit_post_link($item->post_id)); ?>" 
							   class="button button-small" 
							   target="_blank"
							   title="<?php esc_attr_e('Edit this post', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('Edit', 'ai-post-scheduler'); ?>
							</a>
							<button type="button" 
									class="button button-small aips-view-session" 
									data-history-id="<?php echo esc_attr($item->id); ?>"
									title="<?php esc_attr_e('View generation session', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('View Session', 'ai-post-scheduler'); ?>
							</button>
							<button type="button" 
									class="button button-primary button-small aips-publish-post" 
									data-post-id="<?php echo esc_attr($item->post_id); ?>"
									title="<?php esc_attr_e('Publish this post', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('Publish', 'ai-post-scheduler'); ?>
							</button>
							<button type="button" 
									class="button button-small aips-regenerate-post" 
									data-history-id="<?php echo esc_attr($item->id); ?>"
									data-post-id="<?php echo esc_attr($item->post_id); ?>"
									title="<?php esc_attr_e('Regenerate this post', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('Re-generate', 'ai-post-scheduler'); ?>
							</button>
							<button type="button" 
									class="button button-small button-link-delete aips-delete-post" 
									data-post-id="<?php echo esc_attr($item->post_id); ?>"
									data-history-id="<?php echo esc_attr($item->id); ?>"
									title="<?php esc_attr_e('Delete this post', 'ai-post-scheduler'); ?>">
								<?php esc_html_e('Delete', 'ai-post-scheduler'); ?>
							</button>
						</div>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		
		<?php if ($draft_posts['pages'] > 1): ?>
		<div class="tablenav bottom">
			<div class="tablenav-pages">
				<span class="displaying-num">
					<?php printf(
						esc_html(_n('%d item', '%d items', $draft_posts['total'], 'ai-post-scheduler')),
						$draft_posts['total']
					); ?>
				</span>
				<span class="pagination-links">
					<?php
					$base_url = admin_url('admin.php?page=aips-post-review');
					if ($template_id) {
						$base_url .= '&template_id=' . $template_id;
					}
					if ($search_query) {
						$base_url .= '&s=' . urlencode($search_query);
					}
					
					if ($current_page > 1): ?>
					<a class="prev-page button" href="<?php echo esc_url($base_url . '&paged=' . ($current_page - 1)); ?>">
						<span class="screen-reader-text"><?php esc_html_e('Previous page', 'ai-post-scheduler'); ?></span>
						<span aria-hidden="true">&lsaquo;</span>
					</a>
					<?php endif; ?>
					
					<span class="paging-input">
						<span class="tablenav-paging-text">
							<?php echo esc_html($current_page); ?>
							<?php esc_html_e('of', 'ai-post-scheduler'); ?>
							<span class="total-pages"><?php echo esc_html($draft_posts['pages']); ?></span>
						</span>
					</span>
					
					<?php if ($current_page < $draft_posts['pages']): ?>
					<a class="next-page button" href="<?php echo esc_url($base_url . '&paged=' . ($current_page + 1)); ?>">
						<span class="screen-reader-text"><?php esc_html_e('Next page', 'ai-post-scheduler'); ?></span>
						<span aria-hidden="true">&rsaquo;</span>
					</a>
					<?php endif; ?>
				</span>
			</div>
		</div>
		<?php endif; ?>
	</form>
	
	<?php else: ?>
	<div class="aips-empty-state">
		<span class="dashicons dashicons-yes-alt" aria-hidden="true"></span>
		<h3><?php esc_html_e('No Draft Posts', 'ai-post-scheduler'); ?></h3>
		<p><?php esc_html_e('There are no draft posts waiting for review. All generated posts have been published or deleted.', 'ai-post-scheduler'); ?></p>
	</div>
	<?php endif; ?>
</div>

<!-- Session View Modal -->
<div id="aips-session-modal" class="aips-modal" style="display: none;">
	<div class="aips-modal-overlay"></div>
	<div class="aips-modal-content">
		<div class="aips-modal-header">
			<h2><?php esc_html_e('View Session', 'ai-post-scheduler'); ?></h2>
			<div class="aips-modal-header-actions">
				<button class="button button-primary aips-copy-session-json">
					<?php esc_html_e('Copy Session JSON', 'ai-post-scheduler'); ?>
				</button>
				<button class="button aips-download-session-json">
					<?php esc_html_e('Download Session JSON', 'ai-post-scheduler'); ?>
				</button>
				<button class="aips-modal-close" aria-label="<?php esc_attr_e('Close', 'ai-post-scheduler'); ?>">
					<span class="dashicons dashicons-no"></span>
				</button>
			</div>
		</div>
		<div class="aips-modal-body">
			<div class="aips-session-info">
				<p><strong><?php esc_html_e('Post:', 'ai-post-scheduler'); ?></strong> <span id="aips-session-title"></span></p>
				<p><strong><?php esc_html_e('Generated:', 'ai-post-scheduler'); ?></strong> <span id="aips-session-created"></span></p>
				<p><strong><?php esc_html_e('Completed:', 'ai-post-scheduler'); ?></strong> <span id="aips-session-completed"></span></p>
			</div>
			
			<div class="aips-tabs">
				<ul class="aips-tab-nav">
					<li><a href="#aips-tab-logs" class="active"><?php esc_html_e('Logs', 'ai-post-scheduler'); ?></a></li>
					<li><a href="#aips-tab-ai"><?php esc_html_e('AI', 'ai-post-scheduler'); ?></a></li>
				</ul>
				
				<div id="aips-tab-logs" class="aips-tab-content active">
					<div id="aips-logs-list"></div>
				</div>
				
				<div id="aips-tab-ai" class="aips-tab-content" style="display: none;">
					<div id="aips-ai-list"></div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
// Make history type constants available to the JS file
window.AIPS_History_Type = {
	LOG: <?php echo AIPS_History_Type::LOG; ?>,
	ERROR: <?php echo AIPS_History_Type::ERROR; ?>,
	WARNING: <?php echo AIPS_History_Type::WARNING; ?>,
	INFO: <?php echo AIPS_History_Type::INFO; ?>,
	AI_REQUEST: <?php echo AIPS_History_Type::AI_REQUEST; ?>,
	AI_RESPONSE: <?php echo AIPS_History_Type::AI_RESPONSE; ?>,
	DEBUG: <?php echo AIPS_History_Type::DEBUG; ?>,
	ACTIVITY: <?php echo AIPS_History_Type::ACTIVITY; ?>,
	SESSION_METADATA: <?php echo AIPS_History_Type::SESSION_METADATA; ?>
};

// Make AJAX nonce available to the JS file
// Note: The nonce should always be available from localization (aipsPostReviewL10n.nonce)
// This fallback is only for edge cases where localization fails
if (typeof window.aipsAjaxNonce === 'undefined') {
	window.aipsAjaxNonce = window.aipsPostReviewL10n && window.aipsPostReviewL10n.nonce ? window.aipsPostReviewL10n.nonce : '<?php echo esc_js(wp_create_nonce('aips_ajax_nonce')); ?>';
}

</script>
