<div class="wrap">
    <h1><?php esc_html_e('AI Post Scheduler - Seeder', 'ai-post-scheduler'); ?></h1>

    <div class="card" style="max-width: 800px; margin-top: 20px;">
        <h2><?php esc_html_e('Generate Seed Data', 'ai-post-scheduler'); ?></h2>
        <p><?php esc_html_e('Use this tool to populate your database with test data generated by AI.', 'ai-post-scheduler'); ?></p>

        <form id="aips-seeder-form">
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="seeder-keywords"><?php esc_html_e('Seeder Keywords', 'ai-post-scheduler'); ?></label></th>
                    <td>
                        <textarea id="seeder-keywords" name="keywords" rows="3" class="large-text code" placeholder="<?php esc_attr_e('e.g., technology, fitness, vegan recipes', 'ai-post-scheduler'); ?>"></textarea>
                        <p class="description"><?php esc_html_e('Comma-separated keywords to guide the AI generation (optional).', 'ai-post-scheduler'); ?></p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="seeder-voices"><?php esc_html_e('Voices', 'ai-post-scheduler'); ?></label></th>
                    <td>
                        <input type="number" id="seeder-voices" name="voices" value="0" min="0" max="50" class="small-text">
                        <p class="description"><?php esc_html_e('Number of personas to create.', 'ai-post-scheduler'); ?></p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="seeder-templates"><?php esc_html_e('Templates', 'ai-post-scheduler'); ?></label></th>
                    <td>
                        <input type="number" id="seeder-templates" name="templates" value="0" min="0" max="50" class="small-text">
                        <p class="description"><?php esc_html_e('Number of post templates to create.', 'ai-post-scheduler'); ?></p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="seeder-schedule"><?php esc_html_e('Scheduled Templates', 'ai-post-scheduler'); ?></label></th>
                    <td>
                        <input type="number" id="seeder-schedule" name="schedule" value="0" min="0" max="100" class="small-text">
                        <p class="description"><?php esc_html_e('Recurring schedules (Daily, Weekly, etc.) using existing templates.', 'ai-post-scheduler'); ?></p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="seeder-planner"><?php esc_html_e('Planner Entries', 'ai-post-scheduler'); ?></label></th>
                    <td>
                        <input type="number" id="seeder-planner" name="planner" value="0" min="0" max="100" class="small-text">
                        <p class="description"><?php esc_html_e('One-time scheduled posts with specific topics (simulating Planner).', 'ai-post-scheduler'); ?></p>
                    </td>
                </tr>
            </table>

            <p class="submit">
                <button type="submit" id="aips-seeder-submit" class="button button-primary"><?php esc_html_e('Run Seeder', 'ai-post-scheduler'); ?></button>
                <span class="spinner" style="float: none; margin-top: 4px;"></span>
            </p>
        </form>
    </div>

    <div id="aips-seeder-results" class="card" style="max-width: 800px; margin-top: 20px; display: none;">
        <h3><?php esc_html_e('Seeder Log', 'ai-post-scheduler'); ?></h3>
        <div id="aips-seeder-log" style="background: #f0f0f1; padding: 10px; border: 1px solid #c3c4c7; max-height: 300px; overflow-y: auto; font-family: monospace;"></div>
    </div>
</div>
