<?php
/**
 * AI Post Scheduler install seeder.
 *
 * Usage examples:
 *   php tools/seed-install.php --wp-load=/path/to/wp-load.php
 *   php tools/seed-install.php --templates=20 --authors=12 --schedules=30 --voices=8 --seed=2026
 */

if (php_sapi_name() !== 'cli') {
	echo "This script must be run from CLI.\n";
	exit(1);
}

$options = getopt('', array(
	'wp-load:',
	'templates::',
	'authors::',
	'schedules::',
	'voices::',
	'seed::',
	'help::',
));

if (isset($options['help'])) {
	echo "AI Post Scheduler Seeder\n";
	echo "--wp-load=<path>   Path to WordPress wp-load.php (required).\n";
	echo "--templates=<int>  Number of templates to create (default: 12).\n";
	echo "--authors=<int>    Number of authors to create (default: 8).\n";
	echo "--schedules=<int>  Number of schedules to create (default: 20).\n";
	echo "--voices=<int>     Number of voices to create (default: 6).\n";
	echo "--seed=<int>       Optional deterministic random seed.\n";
	exit(0);
}

if (empty($options['wp-load'])) {
	echo "Missing required --wp-load argument.\n";
	exit(1);
}

$wp_load = $options['wp-load'];
if (!file_exists($wp_load)) {
	echo "Could not find wp-load.php at: {$wp_load}\n";
	exit(1);
}

require_once $wp_load;

if (!defined('AIPS_PLUGIN_DIR')) {
	$plugin_bootstrap = dirname(__DIR__) . '/ai-post-scheduler.php';
	if (file_exists($plugin_bootstrap)) {
		require_once $plugin_bootstrap;
	}
}

if (!class_exists('AIPS_Templates') || !class_exists('AIPS_Authors_Repository') || !class_exists('AIPS_Schedule_Repository')) {
	echo "AI Post Scheduler classes not available. Ensure plugin files are loaded.\n";
	exit(1);
}

$templates_count = isset($options['templates']) ? max(0, (int) $options['templates']) : 12;
$authors_count = isset($options['authors']) ? max(0, (int) $options['authors']) : 8;
$schedules_count = isset($options['schedules']) ? max(0, (int) $options['schedules']) : 20;
$voices_count = isset($options['voices']) ? max(0, (int) $options['voices']) : 6;

if (isset($options['seed']) && $options['seed'] !== false) {
	mt_srand((int) $options['seed']);
}

$voices = new AIPS_Voices();
$templates = new AIPS_Templates();
$authors_repository = new AIPS_Authors_Repository();
$schedule_repository = new AIPS_Schedule_Repository();

$topics = array('Cybersecurity', 'Cloud FinOps', 'Content Marketing', 'WordPress Performance', 'Remote Work', 'E-commerce SEO', 'AI Productivity', 'B2B SaaS', 'Personal Finance', 'Sustainable Living', 'DevOps', 'Health Tech');
$styles = array('Practical and concise', 'Data-backed and analytical', 'Friendly expert tone', 'Contrarian and insight-driven', 'Step-by-step educator');
$audiences = array('Startup founders', 'Marketing managers', 'Developers', 'Small business owners', 'Operations teams');
$frequencies = array('daily', 'weekly', 'every_12_hours', 'hourly', 'once');
$angles = array('beginner guide', 'advanced playbook', 'mistakes to avoid', '2026 trends', 'real-world checklist');
$levels = array('beginner', 'intermediate', 'advanced');
$lengths = array('short', 'medium', 'long');

$created = array(
	'voices' => 0,
	'templates' => 0,
	'authors' => 0,
	'schedules' => 0,
);

$voice_ids = array();
for ($i = 1; $i <= $voices_count; $i++) {
	$voice_name = sprintf('Seed Voice %02d', $i);
	$tone = $styles[array_rand($styles)];
	$voice_id = $voices->save(array(
		'name' => $voice_name,
		'title_prompt' => 'Create a specific, curiosity-driven SEO title with a clear promise.',
		'content_instructions' => "{$tone}. Use examples and avoid fluff.",
		'excerpt_instructions' => 'Create a one-sentence excerpt under 24 words.',
		'is_active' => 1,
	));
	if ($voice_id) {
		$voice_ids[] = $voice_id;
		$created['voices']++;
	}
}

$template_ids = array();
for ($i = 1; $i <= $templates_count; $i++) {
	$topic = $topics[array_rand($topics)];
	$angle = $angles[array_rand($angles)];
	$generate_featured = (mt_rand(0, 100) <= 55) ? 1 : 0;
	$include_sources = (mt_rand(0, 100) <= 40) ? 1 : 0;
	$template_id = $templates->save(array(
		'name' => sprintf('Seed Template %02d: %s %s', $i, $topic, $angle),
		'description' => "Autogenerated seed template for {$topic}.",
		'prompt_template' => "Write a complete blog post about {{topic}} in the {$styles[array_rand($styles)]} tone. Include actionable examples and one contrarian insight.",
		'title_prompt' => 'Produce an SEO title under 65 characters with one strong benefit.',
		'voice_id' => !empty($voice_ids) ? $voice_ids[array_rand($voice_ids)] : null,
		'post_quantity' => mt_rand(1, 3),
		'image_prompt' => "A clean editorial illustration representing {$topic}.",
		'generate_featured_image' => $generate_featured,
		'post_status' => (mt_rand(0, 100) <= 70) ? 'draft' : 'publish',
		'post_category' => 0,
		'post_tags' => strtolower(str_replace(' ', '-', $topic)) . ',seeded',
		'include_sources' => $include_sources,
		'source_group_ids' => wp_json_encode(array()),
		'is_active' => 1,
	));
	if ($template_id) {
		$template_ids[] = $template_id;
		$created['templates']++;
	}
}

for ($i = 1; $i <= $authors_count; $i++) {
	$niche = $topics[array_rand($topics)];
	$topic_next_run = time() + mt_rand(600, 7200);
	$post_next_run = time() + mt_rand(1200, 10800);
	$author_id = $authors_repository->create(array(
		'name' => sprintf('Seed Author %02d', $i),
		'field_niche' => $niche,
		'description' => "Synthetic author persona focused on {$niche}.",
		'keywords' => implode(', ', array($niche, 'strategy', 'workflow', 'case study')),
		'details' => 'Created by CLI seeder script for development/test data.',
		'topic_generation_prompt' => "Generate 5 high-leverage topics for {$niche} with varied difficulty.",
		'topic_generation_frequency' => $frequencies[array_rand($frequencies)],
		'topic_generation_quantity' => mt_rand(3, 8),
		'topic_generation_next_run' => $topic_next_run,
		'topic_generation_is_active' => 1,
		'post_generation_frequency' => $frequencies[array_rand($frequencies)],
		'post_generation_next_run' => $post_next_run,
		'post_generation_is_active' => 1,
		'post_status' => (mt_rand(0, 100) <= 80) ? 'draft' : 'publish',
		'generate_featured_image' => (mt_rand(0, 100) <= 45) ? 1 : 0,
		'voice_tone' => $styles[array_rand($styles)],
		'writing_style' => $styles[array_rand($styles)],
		'target_audience' => $audiences[array_rand($audiences)],
		'expertise_level' => $levels[array_rand($levels)],
		'preferred_content_length' => $lengths[array_rand($lengths)],
		'max_posts_per_topic' => mt_rand(1, 3),
		'manual_post_generation_quantity' => mt_rand(1, 3),
		'scheduled_post_generation_quantity' => mt_rand(1, 3),
		'include_sources' => (mt_rand(0, 100) <= 40) ? 1 : 0,
		'is_active' => 1,
	));
	if ($author_id) {
		$created['authors']++;
	}
}

for ($i = 1; $i <= $schedules_count; $i++) {
	if (empty($template_ids)) {
		break;
	}
	$template_id = $template_ids[array_rand($template_ids)];
	$frequency = $frequencies[array_rand($frequencies)];
	$next_run = time() + mt_rand(300, 86400 * 7);
	$schedule_id = $schedule_repository->create(array(
		'template_id' => $template_id,
		'title' => sprintf('Seed Schedule %02d', $i),
		'frequency' => $frequency,
		'next_run' => $next_run,
		'is_active' => 1,
		'status' => 'active',
		'topic' => (mt_rand(0, 100) <= 35) ? $topics[array_rand($topics)] . ' practical workflow' : '',
		'schedule_type' => 'post_generation',
	));
	if ($schedule_id) {
		$created['schedules']++;
	}
}

echo "Seed completed.\n";
echo wp_json_encode($created, JSON_PRETTY_PRINT) . "\n";
