<?php
if (!defined('ABSPATH')) {
	exit;
}

$content_page        = AIPS_Admin_Menu_Helper::get_page_url('generated_posts');
$section_title       = __('Content Queue', 'ai-post-scheduler');
$section_description = __('Use the content manager for completed posts, partial generations, and the draft inventory generated by the plugin.', 'ai-post-scheduler');
$cards               = array(
	array(
		'eyebrow'     => __('Primary Workspace', 'ai-post-scheduler'),
		'title'       => __('Generated Content', 'ai-post-scheduler'),
		'description' => __('Inspect completed post runs, open post previews, and move from generation output into WordPress editing or publishing.', 'ai-post-scheduler'),
		'actions'     => array(
			array('label' => __('Open Content Manager', 'ai-post-scheduler'), 'href' => $content_page, 'primary' => true),
			array('label' => __('Open Partial Generations', 'ai-post-scheduler'), 'href' => $content_page . '#aips-partial-generations'),
		),
	),
);

include AIPS_PLUGIN_DIR . 'templates/admin/hub/components/card-grid.php';
