<?php
if (!defined('ABSPATH')) {
	exit;
}

/**
 * Class AIPS_Language_Store
 *
 * Centralized storage for language-specific localization strings.
 * Provides a language layer for multi-language support.
 *
 * @package AI_Post_Scheduler
 */
class AIPS_Language_Store {

	/**
	 * Get available languages.
	 *
	 * @return array Associative array of language codes and labels.
	 */
	public static function get_available_languages() {
		return array(
			'en' => 'English',
		);
	}

	/**
	 * Get localized data array by language and key.
	 *
	 * @param string $language Language code (e.g., 'en').
	 * @param string $key Localization group key.
	 * @return array Localized strings array.
	 */
	public static function get($language, $key) {
		switch ($language) {
			case 'en':
				return self::get_english($key);
			default:
				// Fallback to English for unsupported languages
				return self::get_english($key);
		}
	}

	/**
	 * Get English language strings.
	 *
	 * @param string $key Localization group key.
	 * @return array English strings array.
	 */
	private static function get_english($key) {
		switch ($key) {
			case 'utilities':
				return array(
					'closeLabel'             => 'Close notification',
					'estimatedTimeRemaining' => 'Estimated time remaining: %s',
					'generationComplete'     => 'Generation complete!',
					'takingLonger'           => 'Taking a little bit longer than expected…',
					'seconds'                => 'seconds',
					'minute'                 => '1 minute',
					'minutes'                => '%d minutes',
					'minutesSeconds'         => '%dm %ds',
				);
			case 'admin':
				return array(
					'errorOccurred'       => 'An error occurred.',
					'errorTryAgain'       => 'An error occurred. Please try again.',
					'confirmCancelButton' => 'No, cancel',
					'confirmDeleteButton' => 'Yes, delete',
					'saving'              => 'Saving...',
					'generating'          => 'Generating...',
					'generationFailed'    => 'Generation failed.',
					'activeLabel'         => 'Active',
					'inactiveLabel'       => 'Inactive',
					'defaultLabel'        => 'Default',
					'noVoiceDefault'      => 'No Voice (Use Default)',
					'noneOption'          => 'None',
				);
			case 'authors':
				return array(
					'addNewAuthor'                => 'Add New Author',
					'editAuthor'                  => 'Edit Author',
					'saveAuthor'                  => 'Save Author',
					'loading'                     => 'Loading...',
					'saving'                      => 'Saving...',
					'generating'                  => 'Generating...',
					'confirmDelete'               => 'Are you sure you want to delete this author? This will also delete all associated topics and logs.',
					'confirmDeleteTopic'          => 'Are you sure you want to delete this topic?',
					'confirmGenerateTopics'       => 'Generate topics for this author now?',
					'confirmGeneratePosts'        => 'Generate posts for this author now?',
					'confirmGeneratePost'         => 'Generate a post from this topic now?',
					'authorSaved'                 => 'Author saved successfully.',
					'authorDeleted'               => 'Author deleted successfully.',
					'topicsGenerated'             => 'Topics generated successfully.',
					'postGenerated'               => 'Post generated successfully.',
					'generateTopicsNow'           => 'Generate Topics Now',
					'generatePostNow'             => 'Generate Post Now',
					'errorLoading'                => 'Error loading author data.',
					'errorSaving'                 => 'Error saving author.',
					'errorDeleting'               => 'Error deleting author.',
					'errorGenerating'             => 'Error generating topics.',
					'errorGeneratingPosts'        => 'Error generating posts.',
					'errorLoadingTopics'          => 'Error loading topics.',
					'errorApproving'              => 'Error approving topic.',
					'errorRejecting'              => 'Error rejecting topic.',
					'errorDeletingTopic'          => 'Error deleting topic.',
					'errorSavingTopic'            => 'Error saving topic.',
					'errorGeneratingPost'         => 'Error generating post.',
					'loadingTopics'               => 'Loading topics...',
					'noTopicsFound'               => 'No topics found.',
					'topicTitle'                  => 'Topic Title',
					'topicDetails'                => 'Topic Details',
					'generatedAt'                 => 'Date Topic Generated',
					'actions'                     => 'Actions',
					'approve'                     => 'Approve',
					'reject'                      => 'Reject',
					'edit'                        => 'Edit',
					'delete'                      => 'Delete',
					'save'                        => 'Save',
					'cancel'                      => 'Cancel',
					'topicTitleRequired'          => 'Topic title is required.',
					'viewPosts'                   => 'Click to view posts generated from this topic',
					'loadingPosts'                => 'Loading posts...',
					'errorLoadingPosts'           => 'Error loading posts.',
					'noPostsFound'                => 'No posts have been generated from this topic yet.',
					'postsGeneratedFrom'          => 'Posts Generated from Topic',
					'postId'                      => 'Post ID',
					'postTitle'                   => 'Post Title',
					'dateGenerated'               => 'Date Generated',
					'datePublished'               => 'Date Published',
					'notPublished'                => 'Not published',
					'editPost'                    => 'Edit Post',
					'viewPost'                    => 'View Post',
					'publishPost'                 => 'Publish',
					'publishing'                  => 'Publishing...',
					'postPublished'               => 'Post published successfully.',
					'errorPublishingPost'         => 'Error publishing post.',
					'confirmPublishPost'          => 'Are you sure you want to publish this post?',
					'noFeaturedImage'             => 'No featured image',
					'topic'                       => 'Topic',
					'action'                      => 'Action',
					'reason'                      => 'Reason',
					'user'                        => 'User',
					'date'                        => 'Date',
					'approveTopicTitle'           => 'Approve Topic',
					'rejectTopicTitle'            => 'Reject Topic',
					'approveReasonPlaceholder'    => 'Why are you approving this topic? (optional)',
					'rejectReasonPlaceholder'     => 'Why are you rejecting this topic? (optional)',
					'approvalCategoryLabel'       => 'Approval Reason',
					'rejectionCategoryLabel'      => 'Rejection Reason',
					'approvalCategoryDescription' => 'Select a positive reason to help train future topic generation.',
					'rejectionCategoryDescription' => 'Select a structured reason to improve future topic quality.',
					'approvalCategories'          => array(
						array('value' => 'other', 'label' => 'Other'),
						array('value' => 'timely', 'label' => 'Timely / On-trend'),
						array('value' => 'relevant', 'label' => 'Relevant to niche'),
						array('value' => 'well_researched', 'label' => 'Well-researched angle'),
						array('value' => 'engaging', 'label' => 'Engaging hook'),
						array('value' => 'original', 'label' => 'Original perspective'),
					),
					'rejectionCategories'         => array(
						array('value' => 'other', 'label' => 'Other'),
						array('value' => 'duplicate', 'label' => 'Duplicate'),
						array('value' => 'tone', 'label' => 'Tone'),
						array('value' => 'irrelevant', 'label' => 'Irrelevant'),
						array('value' => 'policy', 'label' => 'Policy'),
					),
					'loadingQueue'                => 'Loading queue...',
					'errorLoadingQueue'           => 'Error loading queue.',
					'noQueueTopics'               => 'No approved topics in the queue yet.',
					'author'                      => 'Author',
					'fieldNiche'                  => 'Field/Niche',
					'approvedDate'                => 'Approved Date',
					'notAvailable'                => 'N/A',
					'selectBulkAction'            => 'Please select a bulk action.',
					'noTopicsSelected'            => 'Please select at least one topic.',
					'comingSoon'                  => 'This feature is coming soon.',
					'invalidAction'               => 'Invalid action.',
					'confirmGenerateFromQueue'    => 'Generate posts now for %d selected topic(s)?',
					'postsGenerated'              => 'Posts generated successfully.',
					'execute'                     => 'Execute',
					'logViewerTitle'              => 'Topic History Log',
					'logViewerLoading'            => 'Loading logs...',
					'logViewerError'              => 'Error loading logs.',
					'noLogsFound'                 => 'No history found for this topic.',
					'logAction'                   => 'Action',
					'logUser'                     => 'User',
					'logDate'                     => 'Date',
					'logDetails'                  => 'Details',
					'processing'                  => 'Processing...',
					'approveWithFeedback'         => 'Approve with Feedback',
					'rejectWithFeedback'          => 'Reject with Feedback',
					'generateNow'                 => 'Generate Now',
					'confirmBulkGenerate'         => 'Are you sure you want to generate posts for %d topics?',
					'noFeedbackSelected'          => 'Please select at least one feedback item.',
					'errorBulkAction'             => 'Error executing bulk action.',
					'generatingPostsTitle'        => 'Generating Posts',
					'generatingPostsMessage'      => 'Please wait while your posts are being generated. This may take a few minutes.',
					'generationCompletePartial'   => '%d post(s) generated, %d failed.',
					'similarSuggestions'          => 'Similar Suggestions',
					'similarityLabel'             => 'Similarity',
					'lastFeedback'                => 'Last Feedback',
					'previouslyApproved'          => 'Previously Approved',
					'previouslyRejected'          => 'Previously Rejected',
					'potentialDuplicate'          => 'Potential Duplicate',
					'topicCountSingular'          => 'topic',
					'topicCountPlural'            => 'topics',
					'suggestAuthors'              => 'Suggest Authors',
					'suggestAuthorsTitle'         => 'Suggest Authors with AI',
					'siteNicheRequired'           => 'Site niche is required.',
					'generateSuggestions'         => 'Generate Suggestions',
					'generatingSuggestions'       => 'Generating suggestions...',
					'errorGeneratingSuggestions'  => 'Error generating author suggestions.',
					'importAuthor'                => 'Import Author',
					'importedAuthor'              => 'Imported Author',
					'importingAuthor'             => 'Importing...',
					'authorImported'              => 'Author imported successfully.',
					'errorImportingAuthor'        => 'Error importing author.',
					'voiceToneLabel'              => 'Voice/Tone',
					'writingStyleLabel'           => 'Writing Style',
					'topicPromptLabel'            => 'Topic Generation Prompt',
					'viewDetails'                 => 'View Details',
					'noFeedbackYet'               => 'No feedback yet.',
					'dateToday'                   => 'Today',
					'dateYesterday'               => 'Yesterday',
					'dateAM'                      => 'am',
					'datePM'                      => 'pm',
					'dateMonthNames'              => array(
						'January',
						'February',
						'March',
						'April',
						'May',
						'June',
						'July',
						'August',
						'September',
						'October',
						'November',
						'December',
					),
				);
			case 'templates':
				return array(
					'templateNameRequired'    => 'Template Name is required.',
					'contentPromptRequired'   => 'Content Prompt is required.',
					'draftSaved'              => 'Draft saved successfully.',
					'saveDraft'               => 'Save Draft',
					'autoGenerateFromContent' => 'Auto-generate from content',
					'featuredImageNo'         => 'No',
					'featuredImageYes'        => 'Yes (%s)',
					'clickToCopy'             => 'Click to copy',
					'exampleTopic'            => 'Example Topic',
					'failedToGeneratePreview' => 'Failed to generate preview. Please check that all required fields are filled.',
					'previewNetworkError'     => 'An error occurred while generating the preview. Please check your network connection and try again.',
				);
			case 'voices':
				return array(
					'addNewVoice'        => 'Add New Voice',
					'editVoice'          => 'Edit Voice',
					'saveVoice'          => 'Save Voice',
					'deleteVoiceConfirm' => 'Are you sure you want to delete this voice?',
				);
			case 'structures':
				return array(
					'deleteStructureConfirm' => 'Are you sure you want to delete this structure?',
					'saveStructureFailed'    => 'Failed to save structure.',
					'loadStructureFailed'    => 'Failed to load structure.',
					'deleteStructureFailed'  => 'Failed to delete structure.',
					'deleteSectionConfirm'   => 'Are you sure you want to delete this prompt section?',
					'saveSectionFailed'      => 'Failed to save prompt section.',
					'loadSectionFailed'      => 'Failed to load prompt section.',
					'deleteSectionFailed'    => 'Failed to delete prompt section.',
				);
			case 'schedule':
				return array(
					'runScheduleConfirm'             => 'Are you sure you want to run this schedule now? This will immediately generate posts.',
					'scheduleRunning'                => 'Running...',
					'scheduleTemplateRequired'       => 'Please select a Template to continue.',
					'addNewSchedule'                 => 'Add New Schedule',
					'editSchedule'                   => 'Edit Schedule',
					'cloneSchedule'                  => 'Clone Schedule',
					'saveSchedule'                   => 'Save Schedule',
					'scheduleSavedSuccess'           => 'Schedule saved successfully.',
					'startNow'                       => 'Now',
					'useDefault'                     => 'Use Default',
					'noTitle'                        => 'No title',
					'noneOption'                     => 'None',
					'yes'                            => 'Yes',
					'no'                             => 'No',
					'runNow'                         => 'Run Now',
					'cancel'                         => 'Cancel',
					'yesRunNow'                      => 'Yes, run now',
					'deleteScheduleConfirm'          => 'Are you sure you want to delete this schedule?',
					'selectAtLeastOneSchedule'       => 'Please select at least one schedule.',
					'deleteOneScheduleConfirm'       => 'Are you sure you want to delete 1 schedule?',
					'deleteMultipleSchedulesConfirm' => 'Are you sure you want to delete %d schedules?',
					'selectBulkAction'               => 'Please select a bulk action.',
					'selectAtLeastOne'               => 'Please select at least one schedule.',
					'failedToLoadHistory'            => 'Failed to load history.',
					'failedToDeleteSchedules'        => 'Failed to delete schedules.',
					'bulkRunFailed'                  => 'Bulk run failed.',
					'runSchedulesNow'                => 'Run Schedules Now',
					'runPostsConfirmSingular'        => 'This will generate an estimated 1 post. Are you sure?',
					'runPostsConfirmPlural'          => 'This will generate an estimated %d posts. Are you sure?',
					'runOneScheduleConfirm'          => 'This will run 1 schedule. Are you sure?',
					'runMultipleSchedulesConfirm'    => 'This will run %d schedules. Are you sure?',
					'deleteSchedulesHeading'         => 'Delete Schedules',
					'noDeletableSchedulesSelected'   => 'None of the selected schedules can be deleted.',
					'deleteSchedulesListIntro'       => 'The following schedules will be deleted:',
					'deleteSchedulesFinalConfirm'    => 'This action cannot be undone. Continue?',
					'deleteSchedulesSkipNotice'      => '%d selected schedule(s) cannot be deleted and will be skipped.',
				);
			case 'research':
				return array(
					'topicsSaved'             => 'topics saved for',
					'topTopics'               => 'Top 5 Topics:',
					'noTopicsFound'           => 'No topics match your search criteria.',
					'noTopicsFoundTitle'      => 'No Topics Found',
					'clearFilters'            => 'Clear Filters',
					'libraryEmpty'            => 'Your research library is empty.',
					'startResearch'           => 'Start Research',
					'clearSearch'             => 'Clear Search',
					'deleteTopicConfirm'      => 'Delete this topic?',
					'selectTopicSchedule'     => 'Please select at least one topic to schedule.',
					'researchError'           => 'An error occurred during research.',
					'schedulingError'         => 'An error occurred during scheduling.',
					'delete'                  => 'Delete',
					'generateSelected'        => 'Generate',
					'generateIdeas'           => 'Generate Ideas',
					'generatingIdeas'         => 'Generating...',
					'generatingPostsTitle'    => 'Generating Posts',
					'generatingPostsMessage'  => 'Please wait while your posts are being generated. This may take a few minutes.',
					'generateError'           => 'Error generating selected topics.',
					'loadingPosts'            => 'Loading posts...',
					'errorLoadingPosts'       => 'Error loading posts.',
					'noPostsFound'            => 'No posts found.',
					'postsGeneratedFrom'      => 'Posts Generated from Topic',
					'editPost'                => 'Edit Post',
					'viewPost'                => 'View Post',
					'notPublished'            => 'Not published',
					'postId'                  => 'Post ID',
					'postTitle'               => 'Post Title',
					'dateGenerated'           => 'Date Generated',
					'datePublished'           => 'Date Published',
					'actions'                 => 'Actions',
					'statusNew'               => 'New',
					'statusScheduled'         => 'Scheduled',
					'statusGenerated'         => 'Generated',
					'confirmGenerationTitle'  => 'Confirm Generation',
					'confirmGenerationMessage' => 'Generate %d post(s) immediately from selected topics?',
					'cancelButton'            => 'Cancel',
					'generateNowButton'       => 'Generate Now',
					'generatingButton'        => 'Generating...',
					'selectTemplateRequired'  => 'Please select a template before generating.',
				);
			case 'post_review':
				return array(
					'confirmPublish'       => 'Are you sure you want to publish this post?',
					'confirmBulkPublish'   => 'Are you sure you want to publish %d selected post(s)?',
					'confirmDelete'        => 'Are you sure you want to delete this post? This action cannot be undone.',
					'confirmBulkDelete'    => 'Are you sure you want to delete %d selected post(s)? This action cannot be undone.',
					'confirmRegenerate'    => 'Are you sure you want to regenerate this post? The current post will be deleted.',
					'confirmBulkRegenerate' => 'Are you sure you want to regenerate %d selected post(s)? The current posts will be deleted.',
					'publishSuccess'       => 'Post published successfully!',
					'bulkPublishSuccess'   => '%d posts published successfully!',
					'deleteSuccess'        => 'Post deleted successfully!',
					'bulkDeleteSuccess'    => '%d posts deleted successfully!',
					'regenerateSuccess'    => 'Post regeneration started!',
					'bulkRegenerateSuccess' => '%d posts regeneration started!',
					'publishError'         => 'Failed to publish post.',
					'deleteError'          => 'Failed to delete post.',
					'regenerateError'      => 'Failed to regenerate post.',
					'loadingError'         => 'Failed to load draft posts.',
					'loading'              => 'Loading...',
					'publish'              => 'Publish',
					'deleting'             => 'Deleting...',
					'delete'               => 'Delete',
					'regenerating'         => 'Regenerating...',
					'regenerate'           => 'Re-generate',
					'noPostsSelected'      => 'Please select at least one post.',
					'noDraftPosts'         => 'No Draft Posts',
					'noDraftPostsDesc'     => 'There are no draft posts waiting for review.',
					'previewTitle'         => 'Post Preview',
					'loadingPreview'       => 'Loading preview...',
					'previewError'         => 'Failed to load preview.',
				);
			case 'ai_edit':
				return array(
					'regenerate'          => 'Re-generate',
					'regenerating'        => 'Regenerating...',
					'regenerateAll'       => 'Regenerate All',
					'regeneratingAll'     => 'Regenerating all components...',
					'regenerateAllSuccess' => 'Components regenerated successfully.',
					'regenerateAllError'  => 'Failed to regenerate all components.',
					'regenerateSuccess'   => 'Component regenerated successfully!',
					'regenerateError'     => 'Failed to regenerate component.',
					'save'                => 'Save Changes',
					'saving'              => 'Saving...',
					'saveSuccess'         => 'Post updated successfully!',
					'saveError'           => 'Failed to update post.',
					'loadError'           => 'Failed to load post components.',
					'confirmClose'        => 'You have unsaved changes. Are you sure you want to close?',
					'noChanges'           => 'No changes to save.',
					'revisionAiGenerated' => 'AI Generated',
					'revisionManualEdit'  => 'Manual Edit',
					'revisionRestored'    => 'Restored Version',
					'revisionUnknown'     => 'Revision',
				);
			case 'history':
				return array(
					'loading'                => 'Loading…',
					'reloading'              => 'Reloading…',
					'loadingLogs'            => 'Loading logs…',
					'historyDetailsTitle'    => 'History Details',
					'historyContainerHeader' => 'History Container for ID: %d',
					'errorLoading'           => 'Error loading logs.',
					'errorReloading'         => 'Failed to reload history.',
					'logsModalTitle'         => 'Logs — %s',
					'logsHeading'            => 'Log Entries',
					'noLogsFound'            => 'No log entries found for this container.',
					'noResultsFound'         => 'No history containers match your current filters.',
					'labelContainerId'       => 'Container ID',
					'labelTitle'             => 'Title',
					'labelTemplate'          => 'Template',
					'labelStatus'            => 'Status',
					'labelCreated'           => 'Created',
					'labelCompleted'         => 'Completed',
					'labelError'             => 'Error',
					'labelPostId'            => 'Post',
					'labelDuration'          => 'Duration',
					'labelCreationMethod'    => 'Method',
					'editPostLabel'          => 'Edit',
					'filterAll'              => 'All',
					'filterByType'           => 'Filter:',
					'colTimestamp'           => 'Timestamp',
					'colType'                => 'Type',
					'colLogType'             => 'Log Type',
					'colDetails'             => 'Details',
					'showDetails'            => 'Show details',
					'hideDetails'            => 'Hide details',
					'copyDetails'            => 'Copy',
					'copiedDetails'          => 'Copied!',
					'confirmDelete'          => 'Delete this history container? This cannot be undone.',
					'confirmBulkDelete'      => 'Delete the selected history containers? This cannot be undone.',
					'confirmClearAll'        => 'Clear all history? This cannot be undone.',
					'confirmClearStatus'     => 'Clear all history entries with this status? This cannot be undone.',
					'confirmDeleteLabel'     => 'Yes, delete',
					'confirmClearLabel'      => 'Yes, clear',
					'cancelLabel'            => 'No, cancel',
					'deletedSuccess'         => 'Items deleted successfully.',
					'clearedSuccess'         => 'History cleared successfully.',
					'errorDeleting'          => 'Error deleting items.',
					'errorClearing'          => 'Error clearing history.',
					'deleting'               => 'Deleting…',
					'retrying'               => 'Retrying…',
					'errorRetrying'          => 'An error occurred. Please try again.',
				);
			case 'onboarding':
				return array(
					'confirmSkipOnboarding' => 'Skip the Onboarding Wizard? You can restart it later from System Status.',
				);
			case 'taxonomy':
				return array(
					'selectTaxonomyType' => 'Please select a taxonomy type.',
					'selectPost'         => 'Please select at least one post.',
					'selectAction'       => 'Please select an action.',
					'selectItem'         => 'Please select at least one item.',
					'confirmBulkAction'  => 'Are you sure you want to %s %d items?',
					'confirmDelete'      => 'Are you sure you want to delete this item?',
					'confirmCreateTerm'  => 'Create this term in WordPress?',
					'generating'         => 'Generating...',
					'generate'           => 'Generate',
					'actionFailed'       => 'Action failed.',
					'generationFailed'   => 'Generation failed.',
					'deleteFailed'       => 'Delete failed.',
					'termCreationFailed' => 'Term creation failed.',
					'updateFailed'       => 'Update failed.',
					'item'               => 'item',
					'items'              => 'items',
				);
			case 'sources':
				return array(
					'addNewSource'       => 'Add New Source',
					'editSource'         => 'Edit Source',
					'saveSource'         => 'Save Source',
					'saving'             => 'Saving…',
					'deleteConfirm'      => 'Are you sure you want to delete this source?',
					'saveFailed'         => 'Failed to save source.',
					'deleteFailed'       => 'Failed to delete source.',
					'toggleFailed'       => 'Failed to update source status.',
					'urlRequired'        => 'A URL is required.',
					'groupNameRequired'  => 'Please enter a group name.',
					'deleteGroupConfirm' => 'Delete this Source Group? Sources in this group will not be deleted.',
				);
			case 'system_status':
				return array(
					'hideDetails'  => 'Hide Details',
					'showDetails'  => 'Show Details',
					'resetSuccess' => 'Circuit reset. Reload the page to confirm.',
					'resetFailed'  => 'Reset failed.',
					'requestFailed' => 'Request failed. Please try again.',
				);
			case 'dashboard':
				return array(
					'chartPostsTitle'     => 'Post Generations by Day',
					'chartTopicsTitle'    => 'Topic Generations by Day',
					'chartErrorRateTitle' => 'AI Error Rate (%)',
					'chartCompletedLabel' => 'Completed',
					'chartFailedLabel'    => 'Failed',
					'chartTopicsLabel'    => 'Topics Generated',
					'chartErrorRateLabel' => 'Error Rate (%)',
					'chartUnavailable'    => 'Chart library failed to load.',
				);
			case 'telemetry':
				return array(
					'loading'                  => 'Loading…',
					'loadingDetails'           => 'Loading telemetry details…',
					'filterLabel'              => 'Filter',
					'resetFiltersLabel'        => 'Reset Filters',
					'requestFailed'            => 'Request failed. Please try again.',
					'detailsRequestFailed'     => 'Failed to load telemetry details. Please try again.',
					'telemetryPage'            => 'Page %1$s of %2$s',
					'telemetryTotal'           => '%s records',
					'telemetryNoRecords'       => 'No telemetry records found for the selected range.',
					'chartQueriesTitle'        => 'Queries Executed per Day',
					'chartMemoryTitle'         => 'Peak Memory per Day',
					'chartElapsedTitle'        => 'Average Elapsed Time per Day',
					'chartRequestsTitle'       => 'Requests Logged per Day',
					'chartQueriesLabel'        => 'Queries',
					'chartMemoryLabel'         => 'Peak Memory (MB)',
					'chartElapsedLabel'        => 'Average Elapsed (ms)',
					'chartRequestsLabel'       => 'Requests',
					'chartUnavailable'         => 'Chart library failed to load.',
					'rangeSummary'             => 'Showing telemetry from %1$s to %2$s.',
					'refreshLabel'             => 'Refresh',
					'refreshing'               => 'Refreshing…',
					'viewDetails'              => 'View Details',
					'detailsTitle'             => 'Telemetry Details #%s',
					'detailsIdLabel'           => 'ID',
					'detailsTypeLabel'         => 'Type',
					'detailsPageLabel'         => 'Page',
					'detailsCategoriesLabel'   => 'Categories',
					'detailsMethodLabel'       => 'Method',
					'detailsUserIdLabel'       => 'User ID',
					'detailsEventsLabel'       => 'Events',
					'detailsCacheCallsLabel'   => 'Cache Calls',
					'detailsCacheHitsLabel'    => 'Cache Hits',
					'detailsCacheMissesLabel'  => 'Cache Misses',
					'detailsQueriesLabel'      => 'Queries',
					'detailsSlowQueriesLabel'  => 'Slow Queries',
					'detailsDuplicateQueriesLabel' => 'Duplicate Queries',
					'detailsPeakMemoryLabel'   => 'Peak Memory',
					'detailsElapsedLabel'      => 'Elapsed',
					'detailsInsertedLabel'     => 'Inserted At',
					'detailsEventsSection'     => 'Events',
					'detailsEventSummarySection' => 'Event Summary',
					'detailsCacheSummarySection' => 'Cache Summary',
					'detailsQuerySummarySection' => 'Query Summary',
					'detailsEventsHelp'        => 'The full event list can be long. Expand to inspect each nested event object.',
					'detailsEventSummaryHelp'  => 'High-level telemetry counts grouped by bucket and event type.',
					'detailsCacheSummaryHelp'  => 'Cache activity grouped by operation and result.',
					'detailsQuerySummaryHelp'  => 'Query totals, slow queries, and duplicate query counts.',
					'detailsRawPayloadLabel'   => 'Raw Payload JSON',
					'detailsRawPayloadHelp'    => 'Review the structured payload summaries above, or expand the raw JSON below for the original object.',
					'detailsEventItemLabel'    => 'Event %s',
					'detailsItemLabel'         => 'Item %s',
					'expandLabel'              => 'Expand',
					'collapseLabel'            => 'Collapse',
					'insertedJustNow'          => 'just now',
					'insertedMinutesAgo'       => '%s minutes ago',
					'insertedMinuteAgo'        => '1 minute ago',
					'insertedHoursAgo'         => '%s hours ago',
					'insertedHourAgo'          => '1 hour ago',
					'insertedHoursMinutesAgo'  => '%1$s hours and %2$s minutes ago',
					'insertedYesterdayAt'      => 'yesterday at %s',
					'insertedAbsoluteDate'     => '%1$s %2$s',
					'payloadEmpty'             => 'No payload was stored for this telemetry row.',
					'eventsEmpty'              => '[]',
				);
			case 'internal_links':
				return array(
					'confirmDelete'        => 'Delete this suggestion? This cannot be undone.',
					'confirmClearIndex'    => 'Clear the entire index and all suggestions? This cannot be undone.',
					'indexingStarted'      => 'Indexing started. Posts will be processed in the background.',
					'indexingNotAvailable' => 'Embeddings are not available. Please configure AI Engine.',
					'generating'           => 'Generating…',
					'reindexing'           => 'Re-indexing…',
					'loading'              => 'Loading…',
					'noSuggestions'        => 'No suggestions found. Run indexing and generate suggestions to see results.',
					'errorLoading'         => 'Error loading suggestions.',
					'errorDeleting'        => 'Error deleting suggestion.',
					'statusUpdated'        => 'Status updated.',
					'anchorUpdated'        => 'Anchor text updated.',
					'statusUpdateFailed'   => 'Failed to update status.',
					'anchorUpdateFailed'   => 'Failed to update anchor text.',
					'invalidPostId'        => 'Please enter a valid post ID.',
					'requestFailed'        => 'Request failed. Please try again.',
					'acceptAction'         => 'Accept suggestion',
					'rejectAction'         => 'Reject suggestion',
					'accepted'             => 'Accepted',
					'rejected'             => 'Rejected',
					'pending'              => 'Pending',
					'inserted'             => 'Inserted',
					'insertLink'           => 'Insert Link',
					'loadingFailed'        => 'Failed to load post data. Please try again.',
					'noContent'            => '(No content)',
					'noInsertSuggestions'  => 'No accepted suggestions found for this post.',
					'insertBtn'            => 'Get Suggestions',
					'findingLocations'     => 'Finding insertion locations…',
					'locationsFailed'      => 'Failed to find insertion locations. Please try again.',
					'noLocations'          => 'No valid insertion locations could be shown for this suggestion.',
					'invalidLocationsHint' => 'The AI responded, but its suggestions rewrote the source text instead of bracketing an existing phrase.',
					'insertionLocationsLabel' => 'Insertion Locations',
					'returnedCountLabel'   => 'Showing %1$d valid of %2$d AI suggestions',
					'zeroSuggestionsReturned' => '0 valid suggestions',
					'aiSuggestionsReturned' => 'AI returned %d suggestion(s)',
					'reasonLabel'          => 'Reason',
					'originalSnippetLabel' => 'Original text',
					'withLinkLabel'        => 'With link inserted',
					'applyBtn'             => 'Apply',
					'applying'             => 'Applying…',
					'applied'              => 'Link inserted successfully.',
					'applyFailed'          => 'Failed to apply insertion. Please try again.',
					'editAnchorText'       => 'Edit anchor text',
					'deleteSuggestion'     => 'Delete suggestion',
					'anchorLabel'          => 'Anchor',
					'optionLabel'          => 'Option',
					'updatePostBtn'        => 'Update Post with Inserted Links',
					'updating'             => 'Updating…',
					'updateFailed'         => 'Failed to update post. Please try again.',
					'editInsertedLink'     => 'Edit anchor',
					'removeInsertedLink'   => 'Remove link',
					'alreadyApplied'       => 'This suggestion has already been applied to the preview.',
					'snippetNotFound'      => 'The selected text was not found in the content preview.',
					'pendingCountSingle'   => '%d pending insertion',
					'pendingCountPlural'   => '%d pending insertions',
				);
		}

		return array();
	}
}
