<?php
/**
 * Publish Linking Service (generation-time linking)
 *
 * When a post generated by AIPS is published, link it into the site in both
 * directions, in the background:
 *
 * - Outbound (optional): suggestions from the new post to related posts are
 *   queued on the Internal Links page. Generating them also indexes the new
 *   post's embedding, which makes semantic inbound candidates available.
 * - Inbound: older posts that should link to the new post are found with
 *   AIPS_Inbound_Links_Service and, in "apply" mode, links the policy
 *   approves are inserted; everything else waits for review.
 *
 * The inbound pass is recorded in the auto-link run history, so every link it
 * inserted can be undone at once from the Link Report.
 *
 * @package AI_Post_Scheduler
 * @since 3.7.6
 */

if (!defined('ABSPATH')) {
	exit;
}

/**
 * Class AIPS_Publish_Linking_Service
 */
class AIPS_Publish_Linking_Service {

	/**
	 * Cron hook for the background pass (arg: post ID).
	 */
	const CRON_HOOK = 'aips_publish_linking';

	/**
	 * Post meta set once a post has been linked (timestamp).
	 */
	const DONE_META = '_aips_publish_linked';

	/**
	 * Modes.
	 */
	const MODE_OFF    = 'off';
	const MODE_REVIEW = 'review';
	const MODE_APPLY  = 'apply';

	/**
	 * Seconds to wait after publishing, so the post is indexed first.
	 */
	const DELAY = 120;

	/**
	 * @var AIPS_Config
	 */
	private $config;

	/**
	 * @param AIPS_Config|null $config Config.
	 */
	public function __construct(?AIPS_Config $config = null) {
		$this->config = $config ?: AIPS_Config::get_instance();
	}

	/**
	 * Current mode (off | review | apply).
	 *
	 * @return string
	 */
	public function get_mode(): string {
		$mode = (string) $this->config->get_option('aips_publish_linking_mode', self::MODE_REVIEW);
		return in_array($mode, array(self::MODE_OFF, self::MODE_REVIEW, self::MODE_APPLY), true) ? $mode : self::MODE_REVIEW;
	}

	/**
	 * transition_post_status: an AIPS post was published (e.g. an approved
	 * draft or a scheduled post going live).
	 *
	 * @param string  $new_status New status.
	 * @param string  $old_status Old status.
	 * @param WP_Post $post       Post.
	 * @return void
	 */
	public function on_transition($new_status, $old_status, $post): void {
		if ($new_status !== 'publish' || $old_status === 'publish' || !$post instanceof WP_Post) {
			return;
		}

		$this->maybe_schedule((int) $post->ID);
	}

	/**
	 * aips_post_generated: covers posts published directly at generation
	 * (the generated-post meta is written after the status transition).
	 *
	 * @param int $post_id Post ID.
	 * @return void
	 */
	public function on_generated($post_id): void {
		$this->maybe_schedule((int) $post_id);
	}

	/**
	 * Schedule the background pass if this post qualifies and was not linked yet.
	 *
	 * @param int $post_id Post ID.
	 * @return bool Whether a pass was scheduled.
	 */
	public function maybe_schedule(int $post_id): bool {
		if ($post_id <= 0 || $this->get_mode() === self::MODE_OFF || !$this->qualifies($post_id)) {
			return false;
		}

		if (wp_next_scheduled(self::CRON_HOOK, array($post_id))) {
			return false;
		}

		return (bool) wp_schedule_single_event(time() + self::DELAY, self::CRON_HOOK, array($post_id));
	}

	/**
	 * Cron handler: link the post in both directions.
	 *
	 * @param int $post_id Post ID.
	 * @return array|WP_Error Summary (inbound run state, outbound count) or why it was skipped.
	 */
	public function process($post_id) {
		$post_id = (int) $post_id;
		$mode    = $this->get_mode();

		if ($mode === self::MODE_OFF) {
			return new WP_Error('aips_publish_linking_off', __('Generation-time linking is turned off.', 'ai-post-scheduler'));
		}

		if (!$this->qualifies($post_id)) {
			return new WP_Error('aips_publish_linking_skip', __('This post is not a published AIPS post in the link index, or it was already linked.', 'ai-post-scheduler'));
		}

		// Mark first so an overlapping cron request cannot run the pass twice.
		update_post_meta($post_id, self::DONE_META, time());

		$outbound = 0;
		if ((bool) $this->config->get_option('aips_publish_linking_outbound', true)) {
			$result = (new AIPS_Internal_Links_Service())->generate_suggestions_for_post($post_id);
			if (!is_wp_error($result)) {
				$outbound = count((array) $result);
			}
		}

		$user_id = $this->resolve_user($post_id);
		$run     = $this->run_service()->run_now(
			array($post_id),
			$mode === self::MODE_APPLY && $user_id > 0,
			$user_id,
			AIPS_Autolink_Run_Service::SCOPE_PUBLISH,
			array(
				'post_id'    => $post_id,
				'post_title' => get_the_title($post_id),
				'outbound'   => $outbound,
			)
		);

		/**
		 * Fires after a newly published AIPS post was linked into the site.
		 *
		 * @param int   $post_id  Post ID.
		 * @param array $run      Inbound run summary (applied, review, skipped, job_id).
		 * @param int   $outbound Outbound suggestions queued for review.
		 */
		do_action('aips_publish_linking_completed', $post_id, $run, $outbound);

		return array(
			'run'      => $run,
			'outbound' => $outbound,
		);
	}

	/**
	 * Whether a post should get generation-time linking.
	 *
	 * @param int $post_id Post ID.
	 * @return bool
	 */
	private function qualifies(int $post_id): bool {
		$post = get_post($post_id);
		if (!$post instanceof WP_Post || $post->post_status !== 'publish') {
			return false;
		}

		if (!get_post_meta($post_id, AIPS_Post_Manager::META_GENERATED_POST, true) || get_post_meta($post_id, self::DONE_META, true)) {
			return false;
		}

		$link_index = AIPS_Container::get_instance()->make(AIPS_Link_Index_Service::class);

		/**
		 * Filters whether a published post gets generation-time linking.
		 *
		 * @param bool    $qualifies Default: AIPS-generated, published, in the link index scope.
		 * @param WP_Post $post      Post.
		 */
		return (bool) apply_filters('aips_publish_linking_qualifies', $link_index->is_enabled() && $link_index->is_post_in_scope($post), $post);
	}

	/**
	 * User to act as when inserting links from cron. Content saved as an
	 * anonymous user is run through kses, which strips embeds, so links are
	 * only inserted as a user who may post unfiltered HTML.
	 *
	 * @param int $post_id Post ID.
	 * @return int User ID, or 0 when none qualifies (suggestions only).
	 */
	private function resolve_user(int $post_id): int {
		$author = (int) get_post_field('post_author', $post_id);
		if ($author > 0 && user_can($author, 'unfiltered_html') && user_can($author, 'edit_others_posts')) {
			return $author;
		}

		$admins = get_users(array(
			'role'    => 'administrator',
			'orderby' => 'ID',
			'order'   => 'ASC',
			'number'  => 1,
			'fields'  => 'ID',
		));

		$admin = !empty($admins) ? (int) $admins[0] : 0;

		/**
		 * Filters the user generation-time linking acts as.
		 *
		 * @param int $user_id User ID (0 = only create suggestions).
		 * @param int $post_id Published post ID.
		 */
		return (int) apply_filters('aips_publish_linking_user', ($admin > 0 && user_can($admin, 'unfiltered_html')) ? $admin : 0, $post_id);
	}

	/**
	 * @return AIPS_Autolink_Run_Service
	 */
	private function run_service(): AIPS_Autolink_Run_Service {
		return AIPS_Container::get_instance()->make(AIPS_Autolink_Run_Service::class);
	}
}
