<?php
/**
 * Post History UI integration.
 *
 * Adds History quick access links from native WP post list and post editor.
 *
 * @package AI_Post_Scheduler
 * @since 2.5.0
 */

if (!defined('ABSPATH')) {
	exit;
}

class AIPS_Post_History_UI {

	/**
	 * @var AIPS_History_Repository_Interface
	 */
	private $history_repository;

	/**
	 * Request-level cache of history objects keyed by post_id.
	 *
	 * @var array
	 */
	private $history_cache = array();

	/**
	 * @param AIPS_History_Repository_Interface|null $history_repository Optional repository override.
	 */
	public function __construct($history_repository = null) {
		$this->history_repository = $history_repository instanceof AIPS_History_Repository_Interface
			? $history_repository
			: new AIPS_History_Repository();

		add_filter('post_row_actions', array($this, 'add_post_row_action'), 10, 2);
		add_action('post_submitbox_misc_actions', array($this, 'render_submitbox_action'));
		add_filter('manage_post_posts_columns', array($this, 'add_post_columns'));
		add_action('manage_post_posts_custom_column', array($this, 'render_post_column'), 10, 2);
	}

	/**
	 * Add custom columns to native WP Posts list.
	 *
	 * @param array $columns Existing columns.
	 * @return array
	 */
	public function add_post_columns( $columns ) {
		$columns['aips_score'] = __('AI Score', 'ai-post-scheduler');
		return $columns;
	}

	/**
	 * Render custom column content for native WP Posts list.
	 *
	 * @param string $column  Column slug.
	 * @param int    $post_id Post ID.
	 * @return void
	 */
	public function render_post_column( $column, $post_id ) {
		if ( 'aips_score' !== $column ) {
			return;
		}

		$post = get_post( $post_id );
		if ( ! $post ) {
			return;
		}

		// Only show for posts generated by this plugin
		$component_statuses = get_post_meta( $post_id, 'aips_post_generation_component_statuses', true );
		if ( empty( $component_statuses ) ) {
			echo '—';
			return;
		}

		$score_status = get_post_meta( $post_id, '_aips_post_score_status', true );
		if ( 'pending' === $score_status ) {
			?>
			<div class="aips-score-badge-circle aips-score-pending" title="<?php esc_attr_e('Quality scoring in progress...', 'ai-post-scheduler'); ?>">
				<svg width="24" height="24" viewBox="0 0 36 36" class="aips-circular-chart">
					<path class="aips-circle-bg" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
					<path class="aips-circle" stroke-dasharray="25, 100" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
				</svg>
			</div>
			<?php
			return;
		}

		$score_data = get_post_meta( $post_id, '_aips_post_score', true );
		if ( is_array( $score_data ) && isset( $score_data['overall_score'] ) ) {
			$score = (float) $score_data['overall_score'];
			$threshold = (int) ($score_data['threshold'] ?? 70);
			$color_class = $score >= 80 ? 'aips-score-green' : ($score >= 70 ? 'aips-score-orange' : 'aips-score-red');
			?>
			<div class="aips-score-badge-circle" title="<?php printf(esc_attr__('Quality Score: %s%% (Pass: %s%%)', 'ai-post-scheduler'), $score, $threshold); ?>">
				<svg width="24" height="24" viewBox="0 0 36 36" class="aips-circular-chart <?php echo esc_attr($color_class); ?>">
					<path class="aips-circle-bg" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
					<path class="aips-circle" stroke-dasharray="<?php echo esc_attr($score); ?>, 100" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
					<text x="18" y="21.5" class="aips-percentage"><?php echo esc_html(round($score)); ?></text>
				</svg>
			</div>
			<?php
		} else {
			echo '<span class="aips-cell-source">' . esc_html__( 'Not Scored', 'ai-post-scheduler' ) . '</span>';
		}
	}

	/**
	 * Add History link to native post list row actions.
	 *
	 * @param array   $actions Existing row actions.
	 * @param WP_Post $post Current post object.
	 * @return array
	 */
	public function add_post_row_action($actions, $post) {
		if (!$this->can_render_for_post($post)) {
			return $actions;
		}

		$post_id = (int) $post->ID;
		$history = $this->get_cached_history($post_id);
		$history_id = (is_object($history) && !empty($history->id)) ? absint($history->id) : 0;

		if (!$history_id) {
			return $actions;
		}

		$history_url = $this->get_post_history_url($post_id);

		$actions['aips_history'] = sprintf(
			'<a href="%1$s" class="aips-open-history-modal" data-history-id="%2$s" data-post-id="%3$s">%4$s</a>',
			esc_url($history_url),
			esc_attr($history_id),
			esc_attr($post_id),
			esc_html__('History', 'ai-post-scheduler')
		);

		return $actions;
	}

	/**
	 * Render History link in post submit box.
	 *
	 * @return void
	 */
	public function render_submitbox_action() {
		global $post;

		if (!$this->can_render_for_post($post)) {
			return;
		}

		$post_id = (int) $post->ID;
		$history = $this->get_cached_history($post_id);
		$history_id = (is_object($history) && !empty($history->id)) ? absint($history->id) : 0;

		if (!$history_id) {
			return;
		}

		$history_url = $this->get_post_history_url($post_id);
		?>
		<div class="misc-pub-section aips-post-history-link">
			<span class="dashicons dashicons-backup" aria-hidden="true"></span>
			<a href="<?php echo esc_url($history_url); ?>"
			   class="aips-open-history-modal"
			   data-history-id="<?php echo esc_attr($history_id); ?>"
			   data-post-id="<?php echo esc_attr($post_id); ?>">
				<?php esc_html_e('View AI History', 'ai-post-scheduler'); ?>
			</a>
		</div>
		<?php
	}

	/**
	 * Return a cached history object for a given post, performing the DB
	 * lookup at most once per post per request.
	 *
	 * @param int $post_id Post ID.
	 * @return object|null
	 */
	private function get_cached_history($post_id) {
		$post_id = absint($post_id);
		if (!$post_id) {
			return null;
		}
		if (!array_key_exists($post_id, $this->history_cache)) {
			$this->history_cache[$post_id] = $this->history_repository->get_by_post_id($post_id);
		}
		return $this->history_cache[$post_id];
	}

	/**
	 * Build the History admin page URL for a post, including query args for
	 * deep-linking to the correct history entry.
	 *
	 * @param int $post_id Post ID.
	 * @return string
	 */
	private function get_post_history_url($post_id) {
		$post_id = absint($post_id);
		if (!$post_id) {
			return '';
		}

		$history = $this->get_cached_history($post_id);
		$args = array(
			'post_id' => $post_id,
		);

		if (is_object($history) && !empty($history->id)) {
			$args['history_id'] = absint($history->id);
		}

		return AIPS_Admin_Menu_Helper::get_page_url('history', $args);
	}

	/**
	 * Determine whether History UI should be shown for a post.
	 *
	 * @param WP_Post|mixed $post Post object.
	 * @return bool
	 */
	private function can_render_for_post($post) {
		if (!current_user_can('manage_options')) {
			return false;
		}

		if (!($post instanceof WP_Post)) {
			return false;
		}

		if ($post->post_type !== 'post') {
			return false;
		}

		return true;
	}
}
