<?php
/**
 * Stress Test Service
 *
 * Runs isolated end-to-end exercises against the configured AI provider so an
 * administrator can verify the whole generation stack — credentials, model
 * selection, prompt assembly, response parsing, and post creation — without
 * waiting for a scheduled run.
 *
 * Each case reports two values side by side:
 *   - ai_value:     what the provider returned, before the plugin touched it.
 *   - plugin_value: what the plugin produced after its own processing.
 *
 * That pairing is the point of the page: a case can pass at the transport level
 * and still be wrong after normalization, and the two columns make that visible.
 *
 * Cases that create posts mark them with the _aips_stress_test meta key so they
 * can be listed and removed afterwards; nothing here writes to a published post.
 *
 * @package AI_Post_Scheduler
 * @since 3.2.0
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Resilience configuration for interactive stress-test requests.
 *
 * The page is intended to validate the complete pipeline, so one transient
 * timeout or provider 503 should be retried quickly. Circuit-breaker and local
 * rate-limit settings continue to mirror the site's real configuration.
 */
class AIPS_Stress_Test_Resilience_Config {

    /** @var AIPS_Config */
    private $config;

    /**
     * @param AIPS_Config $config Site configuration.
     */
    public function __construct($config) {
        $this->config = $config;
    }

    /**
     * Use one short retry after the initial provider attempt.
     *
     * @return array<string,mixed>
     */
    public function get_retry_config() {
        return array(
            'enabled'       => true,
            'max_attempts'  => 2,
            'initial_delay' => 1,
            'exponential'   => true,
            'jitter'        => true,
        );
    }

    /** @return array<string,mixed> */
    public function get_circuit_breaker_config() {
        return $this->config->get_circuit_breaker_config();
    }

    /** @return array<string,mixed> */
    public function get_rate_limit_config() {
        return $this->config->get_rate_limit_config();
    }
}

/**
 * In-memory mapping store for integration stress-test cases.
 *
 * The Integration Manager loads a template's field mappings through a
 * repository; the stress test never persists mappings, so this stand-in hands
 * the manager a fixed set of mapping rows for any template id. It only needs to
 * satisfy the one method the manager calls, get_by_template().
 */
class AIPS_Stress_Test_Fixed_Mappings_Repository {

    /** @var array<int, object> */
    private $mappings;

    /**
     * @param array<int, object> $mappings Mapping rows to return for any template.
     */
    public function __construct(array $mappings) {
        $this->mappings = $mappings;
    }

    /**
     * @param int  $template_id Ignored; the same fixed set is always returned.
     * @param bool $active_only Ignored.
     * @return array<int, object>
     */
    public function get_by_template($template_id, $active_only = true) {
        return $this->mappings;
    }
}

class AIPS_Stress_Test_Service {

    /**
     * Post meta key marking a post created by this page.
     */
    const TEST_POST_META = '_aips_stress_test';

    /**
     * Attachment meta key marking an image created by this page.
     */
    const TEST_ATTACHMENT_META = '_aips_stress_test_attachment';

    /**
     * Throwaway custom post type used by the CPT generation case. Registered
     * for the duration of stress-test requests only (see register_test_post_type).
     */
    const TEST_POST_TYPE = 'aips_stress_cpt';

    /**
     * Synthetic template id used to satisfy the Integration Manager's
     * template-context guard; no such template row exists in the database.
     */
    const SYNTHETIC_TEMPLATE_ID = 900000000;

    /**
     * Number of posts generated by the bulk case.
     */
    const BULK_POST_COUNT = 3;

    /**
     * @var AIPS_AI_Service Dedicated service instance so its call log holds only
     *                      the calls made by the case currently running.
     */
    private $ai_service;

    /**
     * @var AIPS_Logger_Interface
     */
    private $logger;

    /**
     * @var AIPS_Generator|null Lazily built; construction pulls in the whole
     *                          prompt builder graph, which idle cases do not need.
     */
    private $generator = null;

    /**
     * @param AIPS_AI_Service|null       $ai_service Optional service override (tests).
     * @param AIPS_Logger_Interface|null $logger     Optional logger override.
     */
    public function __construct($ai_service = null, $logger = null) {
        $container = AIPS_Container::get_instance();

        $this->logger = $logger ?: ($container->has(AIPS_Logger_Interface::class) ? $container->make(AIPS_Logger_Interface::class) : new AIPS_Logger());

        if ($ai_service) {
            $this->ai_service = $ai_service;
        } else {
            $config             = AIPS_Config::get_instance();
            $resilience_config  = new AIPS_Stress_Test_Resilience_Config($config);
            $resilience_service = new AIPS_Resilience_Service($this->logger, $resilience_config);
            $this->ai_service   = new AIPS_AI_Service($this->logger, $config, $resilience_service);
        }

        $this->register_test_post_type();
    }

    /**
     * Register the throwaway CPT used by the custom-post-type case.
     *
     * Registered here (rather than globally) so it exists for every stress-test
     * request — the run that creates a CPT post and the later cleanup that
     * removes it — without adding a permanent post type to the site. It is kept
     * out of search UI but searchable so a `post_type => any` cleanup query
     * still finds its posts.
     *
     * @return void
     */
    private function register_test_post_type() {
        if (post_type_exists(self::TEST_POST_TYPE) || !function_exists('register_post_type')) {
            return;
        }

        register_post_type(self::TEST_POST_TYPE, array(
            'labels'              => array('name' => __('AIPS Stress Test CPT', 'ai-post-scheduler')),
            'public'              => false,
            'show_ui'             => false,
            'show_in_menu'        => false,
            'publicly_queryable'  => false,
            'exclude_from_search' => false,
            'has_archive'         => false,
            'rewrite'             => false,
            'supports'            => array('title', 'editor', 'excerpt', 'custom-fields', 'thumbnail'),
        ));
    }

    // -----------------------------------------------------------------------
    // Case catalogue
    // -----------------------------------------------------------------------

    /**
     * Definitions for every runnable case, in display order.
     *
     * @return array<int, array<string, mixed>>
     */
    public function get_cases() {
        $cases = array(
            array(
                'id'          => 'generate_title',
                'label'       => __('Generate a Title', 'ai-post-scheduler'),
                'description' => __('Sends a title prompt and compares the raw response with the cleaned title.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => false,
            ),
            array(
                'id'          => 'generate_content',
                'label'       => __('Generate Content', 'ai-post-scheduler'),
                'description' => __('Requests an article body and shows it before and after HTML normalization.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => false,
            ),
            array(
                'id'          => 'generate_excerpt',
                'label'       => __('Generate an Excerpt', 'ai-post-scheduler'),
                'description' => __('Summarizes a fixed article and reports the stored excerpt length.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => false,
            ),
            array(
                'id'          => 'generate_json',
                'label'       => __('Generate JSON', 'ai-post-scheduler'),
                'description' => __('Exercises structured output, including the text-extraction fallback.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => false,
            ),
            array(
                'id'          => 'generate_featured_image',
                'label'       => __('Generate a Featured Image', 'ai-post-scheduler'),
                'description' => __('Generates an image and uploads it to the media library.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => true,
            ),
            array(
                'id'          => 'save_post',
                'label'       => __('Generate & Save a Post', 'ai-post-scheduler'),
                'description' => __('Runs the full pipeline and saves one draft post.', 'ai-post-scheduler'),
                'group'       => 'pipeline',
                'creates'     => true,
            ),
            array(
                'id'          => 'bulk_posts',
                'label'       => sprintf(__('Generate & Save %d Posts', 'ai-post-scheduler'), self::BULK_POST_COUNT),
                'description' => __('Repeats the full pipeline to surface rate limits and circuit-breaker trips.', 'ai-post-scheduler'),
                'group'       => 'pipeline',
                'creates'     => true,
            ),
            array(
                'id'          => 'meta_fields_single',
                'label'       => __('Meta Field: Single Field', 'ai-post-scheduler'),
                'description' => __('Generates one native WordPress custom-field value through the Integration engine and writes it to a draft post, then reads it back.', 'ai-post-scheduler'),
                'group'       => 'integrations',
                'creates'     => true,
            ),
            array(
                'id'          => 'meta_fields_multi',
                'label'       => __('Meta Fields: Batched Multi-Field', 'ai-post-scheduler'),
                'description' => __('Generates three native custom-field values in a single batched request (the N-fields-to-one-call path) and verifies every field was written.', 'ai-post-scheduler'),
                'group'       => 'integrations',
                'creates'     => true,
            ),
            array(
                'id'          => 'meta_fields_cpt',
                'label'       => __('Meta Fields on a Custom Post Type', 'ai-post-scheduler'),
                'description' => __('Runs the full pipeline into a custom post type (not "post"), then generates and writes native custom fields onto that CPT post.', 'ai-post-scheduler'),
                'group'       => 'integrations',
                'creates'     => true,
            ),
        );

        if ($this->acf_available()) {
            $cases[] = array(
                'id'          => 'meta_fields_acf',
                'label'       => __('Meta Fields: ACF Field Group', 'ai-post-scheduler'),
                'description' => __('Registers a temporary ACF field group, generates values for its fields through the Integration engine, and reads them back via ACF.', 'ai-post-scheduler'),
                'group'       => 'integrations',
                'creates'     => true,
            );
        }

        return $cases;
    }

    /**
     * Whether the ACF integration adapter is registered and its plugin active.
     *
     * @return bool
     */
    private function acf_available() {
        if (!class_exists('AIPS_Integration_Registry')) {
            return false;
        }

        $adapter = AIPS_Integration_Registry::get('acf');

        return $adapter instanceof AIPS_Integration_Interface && $adapter->is_available();
    }

    /**
     * Whether a case id is known.
     *
     * @param string $case_id Case identifier.
     * @return bool
     */
    public function has_case($case_id) {
        foreach ($this->get_cases() as $case) {
            if ($case['id'] === $case_id) {
                return true;
            }
        }

        return false;
    }

    /**
     * Look up a case definition.
     *
     * @param string $case_id Case identifier.
     * @return array<string, mixed>|null
     */
    private function get_case($case_id) {
        foreach ($this->get_cases() as $case) {
            if ($case['id'] === $case_id) {
                return $case;
            }
        }

        return null;
    }

    // -----------------------------------------------------------------------
    // Runner
    // -----------------------------------------------------------------------

    /**
     * Run a single case and return a normalized result.
     *
     * Never throws: an unexpected exception anywhere in the stack is reported as
     * a failed case so one broken provider cannot take down the whole page.
     *
     * @param string $case_id Case identifier.
     * @return array<string, mixed>
     */
    public function run($case_id) {
        $case = $this->get_case($case_id);

        if ($case === null) {
            return $this->fail($case_id, __('Unknown test case.', 'ai-post-scheduler'), 0.0);
        }

        if (!$this->ai_service->is_available()) {
            return $this->fail($case_id, __('No AI provider is available. Check the provider settings.', 'ai-post-scheduler'), 0.0);
        }

        // Isolate the call log so the expanded view shows only this case's traffic.
        $this->ai_service->clear_call_log();

        $started = microtime(true);

        try {
            switch ($case_id) {
                case 'generate_title':
                    $result = $this->case_generate_title();
                    break;
                case 'generate_content':
                    $result = $this->case_generate_content();
                    break;
                case 'generate_excerpt':
                    $result = $this->case_generate_excerpt();
                    break;
                case 'generate_json':
                    $result = $this->case_generate_json();
                    break;
                case 'generate_featured_image':
                    $result = $this->case_generate_featured_image();
                    break;
                case 'save_post':
                    $result = $this->case_save_post();
                    break;
                case 'bulk_posts':
                    $result = $this->case_bulk_posts();
                    break;
                case 'meta_fields_single':
                    $result = $this->case_meta_fields_single();
                    break;
                case 'meta_fields_multi':
                    $result = $this->case_meta_fields_multi();
                    break;
                case 'meta_fields_cpt':
                    $result = $this->case_meta_fields_cpt();
                    break;
                case 'meta_fields_acf':
                    $result = $this->case_meta_fields_acf();
                    break;
                default:
                    $result = array('status' => 'failed', 'error' => __('Case is not implemented.', 'ai-post-scheduler'));
            }
        } catch (Throwable $e) {
            // Throwable, not Exception: a TypeError deep in a provider adapter
            // should still render as a failed row rather than a fatal page.
            $this->logger->log('Stress test case threw: ' . $e->getMessage(), 'error', array('case' => $case_id));

            $result = array(
                'status' => 'failed',
                'error'  => sprintf(
                    /* translators: 1: exception class, 2: message */
                    __('%1$s: %2$s', 'ai-post-scheduler'),
                    get_class($e),
                    $e->getMessage()
                ),
            );
        }

        $duration_ms = (microtime(true) - $started) * 1000;

        return array_merge(
            array(
                'case'         => $case_id,
                'label'        => $case['label'],
                'description'  => $case['description'],
                'group'        => $case['group'],
                'status'       => 'failed',
                'summary'      => '',
                'ai_value'     => null,
                'plugin_value' => null,
                'error'        => null,
                'artifacts'    => array(),
            ),
            $result,
            array(
                'duration_ms' => (int) round($duration_ms),
                'ai_calls'    => $this->collect_ai_calls(),
            )
        );
    }

    /**
     * Build a failed-result envelope.
     *
     * @param string $case_id     Case identifier.
     * @param string $error       Error message.
     * @param float  $duration_ms Elapsed milliseconds.
     * @return array<string, mixed>
     */
    private function fail($case_id, $error, $duration_ms) {
        $case = $this->get_case($case_id);

        return array(
            'case'         => $case_id,
            'label'        => $case ? $case['label'] : $case_id,
            'description'  => $case ? $case['description'] : '',
            'group'        => $case ? $case['group'] : '',
            'status'       => 'failed',
            'summary'      => $error,
            'ai_value'     => null,
            'plugin_value' => null,
            'error'        => $error,
            'artifacts'    => array(),
            'duration_ms'  => (int) round($duration_ms),
            'ai_calls'     => array(),
        );
    }

    /**
     * Normalize the AI service call log into serializable request/response pairs.
     *
     * Data URIs are truncated: a base64 image can be several megabytes and would
     * otherwise be pushed through the AJAX response into the browser.
     *
     * @return array<int, array<string, mixed>>
     */
    private function collect_ai_calls() {
        $calls = array();

        foreach ($this->ai_service->get_call_log() as $entry) {
            $response = isset($entry['response']) ? $entry['response'] : array();
            $content  = isset($response['content']) ? $response['content'] : null;

            $calls[] = array(
                'type'     => isset($entry['type']) ? $entry['type'] : '',
                'time'     => isset($entry['timestamp']) ? $entry['timestamp'] : '',
                'request'  => array(
                    'prompt'  => isset($entry['request']['prompt']) ? (string) $entry['request']['prompt'] : '',
                    'options' => isset($entry['request']['options']) ? $this->scrub_options($entry['request']['options']) : array(),
                ),
                'response' => array(
                    'success' => !empty($response['success']),
                    'content' => $this->shorten_data_uri($content),
                    'error'   => isset($response['error']) ? $response['error'] : null,
                ),
            );
        }

        return $calls;
    }

    /**
     * Remove credentials and non-serializable values from logged options.
     *
     * @param mixed $options Logged options.
     * @return array<string, mixed>
     */
    private function scrub_options($options) {
        if (!is_array($options)) {
            return array();
        }

        unset($options['api_key']);

        foreach ($options as $key => $value) {
            if (is_object($value)) {
                $options[$key] = '[' . get_class($value) . ']';
            }
        }

        return $options;
    }

    /**
     * Replace the body of a long data URI with a placeholder.
     *
     * @param mixed $value Possibly a data URI.
     * @return mixed
     */
    private function shorten_data_uri($value) {
        if (!is_string($value) || strpos($value, 'data:') !== 0 || strlen($value) <= 120) {
            return $value;
        }

        return substr($value, 0, 100) . sprintf('… [%s truncated]', size_format(strlen($value)));
    }

    // -----------------------------------------------------------------------
    // Cases
    // -----------------------------------------------------------------------

    /**
     * Title generation: raw response versus the cleaned title.
     *
     * @return array<string, mixed>
     */
    private function case_generate_title() {
        $context = $this->build_context();
        $result  = $this->get_generator()->generate_title_for_context($context, $this->sample_article());

        if (is_wp_error($result)) {
            return array('status' => 'failed', 'error' => $result->get_error_message(), 'summary' => $result->get_error_message());
        }

        $raw = $this->last_ai_response_text();

        if (trim((string) $result) === '') {
            return array(
                'status'   => 'failed',
                'error'    => __('The provider returned an empty title.', 'ai-post-scheduler'),
                'summary'  => __('Empty title returned.', 'ai-post-scheduler'),
                'ai_value' => $raw,
            );
        }

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: %d: character count */
                __('Title generated (%d characters).', 'ai-post-scheduler'),
                mb_strlen($result)
            ),
            'ai_value'     => $raw,
            'plugin_value' => $result,
        );
    }

    /**
     * Content generation: raw response versus normalized post HTML.
     *
     * @return array<string, mixed>
     */
    private function case_generate_content() {
        $context   = $this->build_context();
        $generator = $this->get_generator();

        // Deliberately not generate_preview(): that runs title and excerpt too,
        // which would duplicate the other cases and triple this one's cost. Drive
        // the content step alone so the row measures exactly what it claims to.
        $builder         = new AIPS_Prompt_Builder();
        $content_prompt  = $builder->build_content_prompt($context);
        $content_context = $builder->build_content_context($context);

        $options = array();

        if ($content_context !== '') {
            $options['context'] = $content_context;
        }

        $raw = $generator->generate_content($content_prompt, $options, 'content');

        if (is_wp_error($raw)) {
            return array('status' => 'failed', 'error' => $raw->get_error_message(), 'summary' => $raw->get_error_message());
        }

        $content = $generator->normalize_generated_content_for_wordpress($raw);

        if (trim($content) === '') {
            return array(
                'status'   => 'failed',
                'error'    => __('The provider returned no usable article body.', 'ai-post-scheduler'),
                'summary'  => __('Empty content returned.', 'ai-post-scheduler'),
                'ai_value' => $raw,
            );
        }

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: 1: word count, 2: character count */
                __('%1$d words / %2$d characters after normalization.', 'ai-post-scheduler'),
                str_word_count(wp_strip_all_tags($content)),
                mb_strlen($content)
            ),
            'ai_value'     => $raw,
            'plugin_value' => $content,
        );
    }

    /**
     * Excerpt generation against a fixed article.
     *
     * @return array<string, mixed>
     */
    private function case_generate_excerpt() {
        $article = $this->sample_article();
        $excerpt = $this->get_generator()->generate_excerpt(
            __('Testing the AI Post Scheduler Pipeline', 'ai-post-scheduler'),
            $article,
            null,
            $this->sample_topic()
        );

        $raw = $this->last_ai_response_text();

        if (trim((string) $excerpt) === '') {
            return array(
                'status'   => 'failed',
                'error'    => __('The provider returned an empty excerpt.', 'ai-post-scheduler'),
                'summary'  => __('Empty excerpt returned.', 'ai-post-scheduler'),
                'ai_value' => $raw,
            );
        }

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: 1: word count, 2: character count */
                __('%1$d words / %2$d characters stored.', 'ai-post-scheduler'),
                str_word_count($excerpt),
                mb_strlen($excerpt)
            ),
            'ai_value'     => $raw,
            'plugin_value' => $excerpt,
        );
    }

    /**
     * Structured JSON output, including the text-extraction fallback path.
     *
     * @return array<string, mixed>
     */
    private function case_generate_json() {
        $schema = array(
            'type'       => 'object',
            'properties' => array(
                'topics' => array(
                    'type'  => 'array',
                    'items' => array('type' => 'string'),
                ),
            ),
            'required'   => array('topics'),
        );

        $prompt = __('List exactly three blog post topics about sustainable home gardening. Respond with a single JSON object shaped as {"topics": ["first", "second", "third"]} and nothing else.', 'ai-post-scheduler');

        $result = $this->ai_service->generate_json($prompt, array(
            'json_schema' => $schema,
            // Reasoning-capable models count hidden thought tokens against the
            // output budget. Leave enough headroom for the requested JSON value.
            'max_tokens'  => 1200,
            'temperature' => 0.1,
        ));

        $raw = $this->last_ai_response_text();

        if (is_wp_error($result)) {
            return array('status' => 'failed', 'error' => $result->get_error_message(), 'summary' => $result->get_error_message(), 'ai_value' => $raw);
        }

        $topics = (isset($result['topics']) && is_array($result['topics'])) ? $result['topics'] : array();

        if (empty($topics)) {
            return array(
                'status'       => 'failed',
                'error'        => __('JSON parsed but contained no "topics" array.', 'ai-post-scheduler'),
                'summary'      => __('Response did not match the requested schema.', 'ai-post-scheduler'),
                'ai_value'     => $raw,
                'plugin_value' => $result,
            );
        }

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: %d: number of topics */
                __('Parsed %d topics from structured output.', 'ai-post-scheduler'),
                count($topics)
            ),
            'ai_value'     => $raw,
            'plugin_value' => $result,
        );
    }

    /**
     * Image generation plus media library upload.
     *
     * @return array<string, mixed>
     */
    private function case_generate_featured_image() {
        $prompt = __('A bright flat-lay photograph of a wooden desk with a notebook, a cup of coffee, and a small potted plant.', 'ai-post-scheduler');

        $image_service = new AIPS_Image_Service($this->ai_service);
        $attachment_id = $image_service->generate_and_upload_featured_image($prompt, __('AIPS Stress Test Image', 'ai-post-scheduler'));

        $raw = $this->last_ai_response_text();

        if (is_wp_error($attachment_id)) {
            return array('status' => 'failed', 'error' => $attachment_id->get_error_message(), 'summary' => $attachment_id->get_error_message(), 'ai_value' => $raw);
        }

        update_post_meta($attachment_id, self::TEST_ATTACHMENT_META, 1);

        $url = wp_get_attachment_url($attachment_id);

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: %d: attachment ID */
                __('Image uploaded as attachment #%d.', 'ai-post-scheduler'),
                $attachment_id
            ),
            'ai_value'     => $raw,
            'plugin_value' => array(
                'attachment_id' => (int) $attachment_id,
                'url'           => $url,
            ),
            'artifacts'    => array(
                'attachment_ids' => array((int) $attachment_id),
                'preview_url'    => $url,
            ),
        );
    }

    /**
     * Full pipeline through to a saved draft post.
     *
     * @return array<string, mixed>
     */
    private function case_save_post() {
        $post_id = $this->generate_and_mark_post();

        if (is_wp_error($post_id)) {
            return array('status' => 'failed', 'error' => $post_id->get_error_message(), 'summary' => $post_id->get_error_message());
        }

        $post = get_post($post_id);

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: %d: post ID */
                __('Draft post #%d created.', 'ai-post-scheduler'),
                $post_id
            ),
            'ai_value'     => $this->first_ai_response_text(),
            'plugin_value' => array(
                'post_id' => (int) $post_id,
                'title'   => $post ? $post->post_title : '',
                'excerpt' => $post ? $post->post_excerpt : '',
                'status'  => $post ? $post->post_status : '',
                'edit_url' => get_edit_post_link($post_id, 'raw'),
            ),
            'artifacts'    => array(
                'post_ids' => array((int) $post_id),
            ),
        );
    }

    /**
     * Repeat the full pipeline to surface rate limits and circuit-breaker trips.
     *
     * A partial run still reports failure but keeps the posts it did create, so
     * the artifacts stay available for inspection and cleanup.
     *
     * @return array<string, mixed>
     */
    private function case_bulk_posts() {
        $post_ids = array();
        $errors   = array();

        for ($i = 0; $i < self::BULK_POST_COUNT; $i++) {
            $post_id = $this->generate_and_mark_post($i + 1);

            if (is_wp_error($post_id)) {
                $errors[] = sprintf('#%d: %s', $i + 1, $post_id->get_error_message());
                continue;
            }

            $post_ids[] = (int) $post_id;
        }

        $created = count($post_ids);
        $summary = sprintf(
            /* translators: 1: created count, 2: requested count */
            __('%1$d of %2$d posts created.', 'ai-post-scheduler'),
            $created,
            self::BULK_POST_COUNT
        );

        return array(
            'status'       => ($created === self::BULK_POST_COUNT) ? 'passed' : 'failed',
            'summary'      => $summary,
            'error'        => empty($errors) ? null : implode(' | ', $errors),
            'ai_value'     => $this->first_ai_response_text(),
            'plugin_value' => array(
                'created'  => $created,
                'expected' => self::BULK_POST_COUNT,
                'post_ids' => $post_ids,
                'errors'   => $errors,
            ),
            'artifacts'    => array(
                'post_ids' => $post_ids,
            ),
        );
    }

    // -----------------------------------------------------------------------
    // Integration (meta field) cases
    // -----------------------------------------------------------------------

    /**
     * One native custom field generated and written through the engine.
     *
     * @return array<string, mixed>
     */
    private function case_meta_fields_single() {
        $post_id = $this->create_stub_post('post');

        if (is_wp_error($post_id)) {
            return array('status' => 'failed', 'error' => $post_id->get_error_message(), 'summary' => $post_id->get_error_message());
        }

        $specs = array(
            array(
                'field_key'     => 'aips_stress_summary',
                'field_type'    => 'freeform_long_text',
                'field_label'   => __('Summary', 'ai-post-scheduler'),
                'custom_prompt' => __('Write a concise 1–2 sentence summary of the article for this custom field.', 'ai-post-scheduler'),
            ),
        );

        $captured = $this->run_integration_fields($post_id, 'native_meta', 'post', $specs);

        return $this->summarize_field_results($post_id, 'native_meta', $specs, $captured, true);
    }

    /**
     * Several native custom fields generated in one batched request.
     *
     * @return array<string, mixed>
     */
    private function case_meta_fields_multi() {
        $post_id = $this->create_stub_post('post');

        if (is_wp_error($post_id)) {
            return array('status' => 'failed', 'error' => $post_id->get_error_message(), 'summary' => $post_id->get_error_message());
        }

        $specs = array(
            array(
                'field_key'     => 'aips_stress_headline',
                'field_type'    => 'freeform_short_text',
                'field_label'   => __('Headline', 'ai-post-scheduler'),
                'custom_prompt' => __('Write a punchy one-line headline of no more than eight words.', 'ai-post-scheduler'),
            ),
            array(
                'field_key'     => 'aips_stress_summary',
                'field_type'    => 'freeform_long_text',
                'field_label'   => __('Summary', 'ai-post-scheduler'),
                'custom_prompt' => __('Write a 1–2 sentence summary of the article.', 'ai-post-scheduler'),
            ),
            array(
                'field_key'     => 'aips_stress_cta',
                'field_type'    => 'freeform_short_text',
                'field_label'   => __('Call to action', 'ai-post-scheduler'),
                'custom_prompt' => __('Write a short call-to-action phrase for the end of the article.', 'ai-post-scheduler'),
            ),
        );

        $captured = $this->run_integration_fields($post_id, 'native_meta', 'post', $specs);

        return $this->summarize_field_results($post_id, 'native_meta', $specs, $captured, true);
    }

    /**
     * Full pipeline into a custom post type, then native custom fields on it.
     *
     * @return array<string, mixed>
     */
    private function case_meta_fields_cpt() {
        $this->register_test_post_type();

        // Full generation into the CPT proves post_type support end to end.
        $post_id = $this->generate_and_mark_post(0, self::TEST_POST_TYPE);

        if (is_wp_error($post_id)) {
            return array('status' => 'failed', 'error' => $post_id->get_error_message(), 'summary' => $post_id->get_error_message());
        }

        $post         = get_post($post_id);
        $created_type = $post ? $post->post_type : '';

        if ($created_type !== self::TEST_POST_TYPE) {
            return array(
                'status'       => 'failed',
                'summary'      => __('The custom post type was not applied to the generated post.', 'ai-post-scheduler'),
                'error'        => sprintf(
                    /* translators: 1: expected post type, 2: actual post type */
                    __('Expected post type "%1$s" but the generated post was "%2$s".', 'ai-post-scheduler'),
                    self::TEST_POST_TYPE,
                    $created_type
                ),
                'ai_value'     => $this->first_ai_response_text(),
                'plugin_value' => array('post_id' => (int) $post_id, 'post_type' => $created_type),
                'artifacts'    => array('post_ids' => array((int) $post_id)),
            );
        }

        $specs = array(
            array(
                'field_key'     => 'aips_stress_summary',
                'field_type'    => 'freeform_long_text',
                'field_label'   => __('Summary', 'ai-post-scheduler'),
                'custom_prompt' => __('Write a 1–2 sentence summary of the article.', 'ai-post-scheduler'),
            ),
            array(
                'field_key'     => 'aips_stress_keywords',
                'field_type'    => 'freeform_short_text',
                'field_label'   => __('Keywords', 'ai-post-scheduler'),
                'custom_prompt' => __('List three comma-separated keywords for the article.', 'ai-post-scheduler'),
            ),
        );

        $captured = $this->run_integration_fields($post_id, 'native_meta', self::TEST_POST_TYPE, $specs);
        $result   = $this->summarize_field_results($post_id, 'native_meta', $specs, $captured, false);

        $result['plugin_value'] = array(
            'post_id'   => (int) $post_id,
            'post_type' => $created_type,
            'fields'    => isset($result['plugin_value']) ? $result['plugin_value'] : array(),
        );
        $result['summary'] = sprintf(
            /* translators: 1: post type slug, 2: field-write summary */
            __('CPT "%1$s" post generated. %2$s', 'ai-post-scheduler'),
            $created_type,
            $result['summary']
        );

        return $result;
    }

    /**
     * Register a temporary ACF field group, generate its fields, read them back.
     *
     * @return array<string, mixed>
     */
    private function case_meta_fields_acf() {
        if (!$this->acf_available()) {
            return array(
                'status'  => 'failed',
                'error'   => __('ACF is not active on this site.', 'ai-post-scheduler'),
                'summary' => __('ACF is not active on this site.', 'ai-post-scheduler'),
            );
        }

        $group_key      = 'group_aips_stress_test';
        $field_headline = 'field_aips_stress_headline';
        $field_summary  = 'field_aips_stress_summary';

        if (function_exists('acf_add_local_field_group')) {
            acf_add_local_field_group(array(
                'key'      => $group_key,
                'title'    => 'AIPS Stress Test',
                'fields'   => array(
                    array('key' => $field_headline, 'label' => 'Headline', 'name' => 'aips_stress_acf_headline', 'type' => 'text'),
                    array('key' => $field_summary, 'label' => 'Summary', 'name' => 'aips_stress_acf_summary', 'type' => 'textarea'),
                ),
                'location' => array(
                    array(
                        array('param' => 'post_type', 'operator' => '==', 'value' => 'post'),
                    ),
                ),
            ));
        }

        $post_id = $this->create_stub_post('post');

        if (is_wp_error($post_id)) {
            return array('status' => 'failed', 'error' => $post_id->get_error_message(), 'summary' => $post_id->get_error_message());
        }

        $specs = array(
            array(
                'field_key'     => $field_headline,
                'field_type'    => 'text',
                'field_label'   => __('Headline', 'ai-post-scheduler'),
                'custom_prompt' => __('Write a punchy one-line headline of no more than eight words.', 'ai-post-scheduler'),
            ),
            array(
                'field_key'     => $field_summary,
                'field_type'    => 'textarea',
                'field_label'   => __('Summary', 'ai-post-scheduler'),
                'custom_prompt' => __('Write a 1–2 sentence summary of the article.', 'ai-post-scheduler'),
            ),
        );

        $captured = $this->run_integration_fields($post_id, 'acf', $group_key, $specs);

        return $this->summarize_field_results($post_id, 'acf', $specs, $captured, true);
    }

    /**
     * Create a lightweight draft post (no AI) to serve as a write target for
     * the integration cases, seeded with the sample article so field prompts
     * have real context to summarize.
     *
     * @param string $post_type Target post type.
     * @return int|WP_Error
     */
    private function create_stub_post($post_type = 'post') {
        $post_id = wp_insert_post(array(
            'post_type'    => $post_type,
            'post_status'  => 'draft',
            'post_title'   => __('AIPS Stress Test — Custom Fields', 'ai-post-scheduler'),
            'post_content' => $this->sample_article(),
            'post_author'  => get_current_user_id(),
        ), true);

        if (is_wp_error($post_id)) {
            return $post_id;
        }

        update_post_meta($post_id, self::TEST_POST_META, 1);

        return $post_id;
    }

    /**
     * Drive the real Integration Manager for a set of field mappings and return
     * the per-field outcome it reports.
     *
     * The manager is wired to this service's AI service, so its generate_json /
     * generate_text calls land in the same call log the results panel reads,
     * and to a fixed in-memory mapping store so nothing is persisted.
     *
     * @param int    $post_id        Target post ID.
     * @param string $integration_id Integration identifier ('native_meta'|'acf').
     * @param string $source_key     Group/source key (post type for native meta).
     * @param array  $field_specs    List of ['field_key','field_type','field_label','custom_prompt'].
     * @return array<string, true|WP_Error> field_key => outcome.
     */
    private function run_integration_fields($post_id, $integration_id, $source_key, array $field_specs) {
        $mappings = array();

        foreach ($field_specs as $spec) {
            $mappings[] = (object) array(
                'template_id'    => self::SYNTHETIC_TEMPLATE_ID,
                'integration_id' => $integration_id,
                'source_key'     => $source_key,
                'field_key'      => $spec['field_key'],
                'field_label'    => isset($spec['field_label']) ? $spec['field_label'] : $spec['field_key'],
                'field_type'     => $spec['field_type'],
                'custom_prompt'  => isset($spec['custom_prompt']) ? $spec['custom_prompt'] : '',
                'is_active'      => 1,
            );
        }

        $repo    = new AIPS_Stress_Test_Fixed_Mappings_Repository($mappings);
        $manager = new AIPS_Integration_Manager($repo, $this->ai_service, null, $this->logger);

        $post_type     = get_post_type($post_id) ?: 'post';
        $context       = $this->build_context(0, $post_type, self::SYNTHETIC_TEMPLATE_ID);
        $template_stub  = (object) array('id' => self::SYNTHETIC_TEMPLATE_ID);

        $captured = array();
        $collector = function ($applied_post_id, $applied_integration_id, $results) use (&$captured, $post_id, $integration_id) {
            if ((int) $applied_post_id === (int) $post_id && $applied_integration_id === $integration_id) {
                $captured = $results;
            }
        };

        add_action('aips_integration_fields_applied', $collector, 10, 3);
        $manager->handle_post_generated($post_id, $template_stub, null, $context);
        remove_action('aips_integration_fields_applied', $collector, 10);

        return $captured;
    }

    /**
     * Turn per-field outcomes plus the written values into a case result.
     *
     * A field only counts as passing when the engine reported success AND a
     * non-empty value is actually readable back from storage.
     *
     * @param int    $post_id        Target post ID.
     * @param string $integration_id Integration identifier.
     * @param array  $field_specs    The specs that were generated.
     * @param array  $captured       field_key => true|WP_Error from the manager.
     * @param bool   $mention_calls  Append the AI-call count to the summary.
     * @return array<string, mixed>
     */
    private function summarize_field_results($post_id, $integration_id, $field_specs, $captured, $mention_calls = false) {
        $written   = array();
        $errors    = array();
        $non_empty = 0;

        foreach ($field_specs as $spec) {
            $key     = $spec['field_key'];
            $outcome = isset($captured[$key]) ? $captured[$key] : null;

            if (is_wp_error($outcome)) {
                $errors[] = $key . ': ' . $outcome->get_error_message();
                $written[$key] = null;
                continue;
            }

            $value         = $this->read_back_field($post_id, $integration_id, $key);
            $written[$key] = $value;

            $flat = is_array($value) ? wp_json_encode($value) : (string) $value;

            if (trim((string) $flat) !== '') {
                $non_empty++;
            }
        }

        $expected = count($field_specs);
        $passed   = empty($errors) && $non_empty === $expected;

        $summary = sprintf(
            /* translators: 1: fields written, 2: fields expected */
            __('%1$d of %2$d fields generated and written.', 'ai-post-scheduler'),
            $non_empty,
            $expected
        );

        if ($mention_calls) {
            $call_count = count($this->ai_service->get_call_log());
            $summary   .= ' ' . sprintf(
                /* translators: %d: number of AI calls */
                _n('%d AI call.', '%d AI calls.', $call_count, 'ai-post-scheduler'),
                $call_count
            );
        }

        return array(
            'status'       => $passed ? 'passed' : 'failed',
            'summary'      => $summary,
            'error'        => empty($errors) ? null : implode(' | ', $errors),
            'ai_value'     => $this->first_ai_response_text(),
            'plugin_value' => $written,
            'artifacts'    => array('post_ids' => array((int) $post_id)),
        );
    }

    /**
     * Read a written field value back from storage for verification.
     *
     * @param int    $post_id        Target post ID.
     * @param string $integration_id Integration identifier.
     * @param string $field_key      Field/meta key.
     * @return mixed
     */
    private function read_back_field($post_id, $integration_id, $field_key) {
        if ($integration_id === 'acf' && function_exists('get_field')) {
            return get_field($field_key, $post_id);
        }

        return get_post_meta($post_id, $field_key, true);
    }

    // -----------------------------------------------------------------------
    // Shared fixtures
    // -----------------------------------------------------------------------

    /**
     * Lazily construct the generator.
     *
     * It is wired to this service's own AI service instance so every provider
     * call the generator makes lands in the call log the results panel reads.
     *
     * @return AIPS_Generator
     */
    private function get_generator() {
        if ($this->generator === null) {
            $this->generator = new AIPS_Generator($this->logger, $this->ai_service);
        }

        return $this->generator;
    }

    /**
     * Topic used by every case, so runs stay comparable.
     *
     * @return string
     */
    private function sample_topic() {
        /**
         * Filters the topic the stress test generates against.
         *
         * @since 3.2.0
         *
         * @param string $topic Default sample topic.
         */
        return (string) apply_filters('aips_stress_test_topic', __('Practical tips for starting a balcony herb garden', 'ai-post-scheduler'));
    }

    /**
     * A synthetic template context so the page works on a site with no templates.
     *
     * @param int    $index       Optional run index, used to vary bulk-run topics.
     * @param string $post_type   Target post type. Defaults to 'post'.
     * @param int    $template_id Synthetic template id exposed via the context.
     * @return AIPS_Template_Context
     */
    private function build_context($index = 0, $post_type = 'post', $template_id = 0) {
        $topic = $this->sample_topic();

        if ($index > 0) {
            $topic .= sprintf(' (%d)', $index);
        }

        $template = (object) array(
            'id'                      => $template_id,
            'name'                    => __('AIPS Stress Test', 'ai-post-scheduler'),
            'prompt_template'         => __('Write a short, practical article of roughly 300 words about {{topic}}. Use two <h2> sections.', 'ai-post-scheduler'),
            'title_prompt'            => __('Write a clear, specific title. No colons, no clickbait.', 'ai-post-scheduler'),
            'image_prompt'            => '',
            'generate_featured_image' => false,
            'post_status'             => 'draft',
            'post_type'               => $post_type,
            'post_category'           => '',
            'post_tags'               => '',
            'post_author'             => get_current_user_id(),
            'article_structure_id'    => null,
            'include_sources'         => false,
            'source_group_ids'        => '',
        );

        /**
         * Filters the synthetic template used by the stress test.
         *
         * @since 3.2.0
         *
         * @param object $template Template stand-in.
         * @param string $topic    Topic being generated.
         */
        $template = apply_filters('aips_stress_test_template', $template, $topic);

        return new AIPS_Template_Context($template, null, $topic, 'manual');
    }

    /**
     * Run the full pipeline and tag the resulting post as test data.
     *
     * @param int    $index     Optional run index for bulk runs.
     * @param string $post_type Target post type. Defaults to 'post'.
     * @return int|WP_Error Post ID or error.
     */
    private function generate_and_mark_post($index = 0, $post_type = 'post') {
        $post_id = $this->get_generator()->generate_post($this->build_context($index, $post_type));

        if (!is_wp_error($post_id)) {
            update_post_meta($post_id, self::TEST_POST_META, 1);
        }

        return $post_id;
    }

    /**
     * Fixed article body used by cases that summarize rather than generate.
     *
     * @return string
     */
    private function sample_article() {
        return '<p>' . __('Balcony herb gardens work best when you start with the light you actually have rather than the herbs you want. South-facing rails carry rosemary and thyme through a full season; a shaded corner will do better with mint, parsley, and chives.', 'ai-post-scheduler') . '</p>'
            . '<h2>' . __('Choosing containers', 'ai-post-scheduler') . '</h2>'
            . '<p>' . __('Depth matters more than width for most culinary herbs. A twenty-centimetre pot holds enough soil to buffer temperature swings, which is what actually kills balcony plants in midsummer.', 'ai-post-scheduler') . '</p>'
            . '<h2>' . __('Watering rhythm', 'ai-post-scheduler') . '</h2>'
            . '<p>' . __('Containers dry from the top down, so surface soil is a poor indicator. Push a finger to the second knuckle before watering, and water until it runs from the base.', 'ai-post-scheduler') . '</p>';
    }

    /**
     * Text of the most recent successful AI response.
     *
     * @return string|null
     */
    private function last_ai_response_text() {
        $log = $this->ai_service->get_call_log();

        for ($i = count($log) - 1; $i >= 0; $i--) {
            if (!empty($log[$i]['response']['success'])) {
                return $this->shorten_data_uri($log[$i]['response']['content']);
            }
        }

        return null;
    }

    /**
     * Text of the first successful AI response.
     *
     * Multi-call cases make several requests; the first is the one whose raw
     * output the plugin then transformed, so that is what belongs beside the
     * final value.
     *
     * @return string|null
     */
    private function first_ai_response_text() {
        foreach ($this->ai_service->get_call_log() as $entry) {
            if (!empty($entry['response']['success'])) {
                return $this->shorten_data_uri($entry['response']['content']);
            }
        }

        return null;
    }

    // -----------------------------------------------------------------------
    // Test data management
    // -----------------------------------------------------------------------

    /**
     * Count posts and attachments created by this page.
     *
     * @return array{posts: int, attachments: int}
     */
    public function count_test_data() {
        return array(
            'posts'       => count($this->get_test_post_ids()),
            'attachments' => count($this->get_test_attachment_ids()),
        );
    }

    /**
     * IDs of posts created by this page.
     *
     * @return int[]
     */
    private function get_test_post_ids() {
        return $this->collect_test_ids('any', self::TEST_POST_META);
    }

    /**
     * IDs of attachments created by this page.
     *
     * @return int[]
     */
    private function get_test_attachment_ids() {
        return $this->collect_test_ids('attachment', self::TEST_ATTACHMENT_META);
    }

    /**
     * Collect all marked object IDs in batches.
     *
     * @param string $post_type Post type to query.
     * @param string $meta_key  Meta key marker.
     * @return int[]
     */
    private function collect_test_ids($post_type, $meta_key) {
        $ids = array();
        $offset = 0;
        $batch_size = 200;

        while (true) {
            $batch = get_posts(array(
                'post_type'        => $post_type,
                'post_status'      => 'any',
                'numberposts'      => $batch_size,
                'offset'           => $offset,
                'orderby'          => 'ID',
                'order'            => 'ASC',
                'fields'           => 'ids',
                'meta_key'         => $meta_key,
                'suppress_filters' => false,
            ));

            if (empty($batch)) {
                break;
            }

            $ids = array_merge($ids, $batch);
            $offset += count($batch);
        }

        return $ids;
    }

    /**
     * Permanently delete everything this page created.
     *
     * @return array{posts: int, attachments: int}
     */
    public function cleanup_test_data() {
        $deleted_posts = 0;
        $deleted_media = 0;

        foreach ($this->get_test_post_ids() as $post_id) {
            // Bypass the trash: these are disposable fixtures, and leaving them in
            // the trash would keep them counted as existing test data.
            if (wp_delete_post($post_id, true)) {
                $deleted_posts++;
            }
        }

        foreach ($this->get_test_attachment_ids() as $attachment_id) {
            if (wp_delete_attachment($attachment_id, true)) {
                $deleted_media++;
            }
        }

        $this->logger->log('Stress test data cleaned up', 'info', array(
            'posts'       => $deleted_posts,
            'attachments' => $deleted_media,
        ));

        return array('posts' => $deleted_posts, 'attachments' => $deleted_media);
    }

    /**
     * Snapshot of the environment shown above the results.
     *
     * @return array<string, mixed>
     */
    public function get_environment() {
        $config   = AIPS_Config::get_instance();
        $provider = AIPS_AI_Provider_Factory::create();

        return array(
            'provider'        => $provider->get_label(),
            'provider_id'     => $provider->get_id(),
            'available'       => $provider->is_available(),
            'reason'          => $provider->is_available() ? '' : $provider->get_unavailable_reason(),
            'model'           => (string) $config->get_option('aips_ai_model'),
            'native_json'     => $provider->supports_native_json(),
            'conversation'    => $provider->supports_conversation(),
            'conversational'  => (bool) $config->get_option('aips_conversational_generation'),
            'metadata_turn'   => (bool) $config->get_option('aips_conversational_metadata_turn'),
        );
    }
}
