<?php
/**
 * Stress Test Service
 *
 * Runs isolated end-to-end exercises against the configured AI provider so an
 * administrator can verify the whole generation stack — credentials, model
 * selection, prompt assembly, response parsing, and post creation — without
 * waiting for a scheduled run.
 *
 * Each case reports two values side by side:
 *   - ai_value:     what the provider returned, before the plugin touched it.
 *   - plugin_value: what the plugin produced after its own processing.
 *
 * That pairing is the point of the page: a case can pass at the transport level
 * and still be wrong after normalization, and the two columns make that visible.
 *
 * Cases that create posts mark them with the _aips_stress_test meta key so they
 * can be listed and removed afterwards; nothing here writes to a published post.
 *
 * @package AI_Post_Scheduler
 * @since 3.2.0
 */

if (!defined('ABSPATH')) {
    exit;
}

class AIPS_Stress_Test_Service {

    /**
     * Post meta key marking a post created by this page.
     */
    const TEST_POST_META = '_aips_stress_test';

    /**
     * Attachment meta key marking an image created by this page.
     */
    const TEST_ATTACHMENT_META = '_aips_stress_test_attachment';

    /**
     * Number of posts generated by the bulk case.
     */
    const BULK_POST_COUNT = 3;

    /**
     * @var AIPS_AI_Service Dedicated service instance so its call log holds only
     *                      the calls made by the case currently running.
     */
    private $ai_service;

    /**
     * @var AIPS_Logger_Interface
     */
    private $logger;

    /**
     * @var AIPS_Generator|null Lazily built; construction pulls in the whole
     *                          prompt builder graph, which idle cases do not need.
     */
    private $generator = null;

    /**
     * @param AIPS_AI_Service|null       $ai_service Optional service override (tests).
     * @param AIPS_Logger_Interface|null $logger     Optional logger override.
     */
    public function __construct($ai_service = null, $logger = null) {
        $container = AIPS_Container::get_instance();

        $this->logger     = $logger ?: ($container->has(AIPS_Logger_Interface::class) ? $container->make(AIPS_Logger_Interface::class) : new AIPS_Logger());
        $this->ai_service = $ai_service ?: new AIPS_AI_Service();
    }

    // -----------------------------------------------------------------------
    // Case catalogue
    // -----------------------------------------------------------------------

    /**
     * Definitions for every runnable case, in display order.
     *
     * @return array<int, array<string, mixed>>
     */
    public function get_cases() {
        return array(
            array(
                'id'          => 'generate_title',
                'label'       => __('Generate a Title', 'ai-post-scheduler'),
                'description' => __('Sends a title prompt and compares the raw response with the cleaned title.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => false,
            ),
            array(
                'id'          => 'generate_content',
                'label'       => __('Generate Content', 'ai-post-scheduler'),
                'description' => __('Requests an article body and shows it before and after HTML normalization.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => false,
            ),
            array(
                'id'          => 'generate_excerpt',
                'label'       => __('Generate an Excerpt', 'ai-post-scheduler'),
                'description' => __('Summarizes a fixed article and reports the stored excerpt length.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => false,
            ),
            array(
                'id'          => 'generate_json',
                'label'       => __('Generate JSON', 'ai-post-scheduler'),
                'description' => __('Exercises structured output, including the text-extraction fallback.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => false,
            ),
            array(
                'id'          => 'generate_featured_image',
                'label'       => __('Generate a Featured Image', 'ai-post-scheduler'),
                'description' => __('Generates an image and uploads it to the media library.', 'ai-post-scheduler'),
                'group'       => 'components',
                'creates'     => true,
            ),
            array(
                'id'          => 'save_post',
                'label'       => __('Generate & Save a Post', 'ai-post-scheduler'),
                'description' => __('Runs the full pipeline and saves one draft post.', 'ai-post-scheduler'),
                'group'       => 'pipeline',
                'creates'     => true,
            ),
            array(
                'id'          => 'bulk_posts',
                'label'       => sprintf(__('Generate & Save %d Posts', 'ai-post-scheduler'), self::BULK_POST_COUNT),
                'description' => __('Repeats the full pipeline to surface rate limits and circuit-breaker trips.', 'ai-post-scheduler'),
                'group'       => 'pipeline',
                'creates'     => true,
            ),
        );
    }

    /**
     * Whether a case id is known.
     *
     * @param string $case_id Case identifier.
     * @return bool
     */
    public function has_case($case_id) {
        foreach ($this->get_cases() as $case) {
            if ($case['id'] === $case_id) {
                return true;
            }
        }

        return false;
    }

    /**
     * Look up a case definition.
     *
     * @param string $case_id Case identifier.
     * @return array<string, mixed>|null
     */
    private function get_case($case_id) {
        foreach ($this->get_cases() as $case) {
            if ($case['id'] === $case_id) {
                return $case;
            }
        }

        return null;
    }

    // -----------------------------------------------------------------------
    // Runner
    // -----------------------------------------------------------------------

    /**
     * Run a single case and return a normalized result.
     *
     * Never throws: an unexpected exception anywhere in the stack is reported as
     * a failed case so one broken provider cannot take down the whole page.
     *
     * @param string $case_id Case identifier.
     * @return array<string, mixed>
     */
    public function run($case_id) {
        $case = $this->get_case($case_id);

        if ($case === null) {
            return $this->fail($case_id, __('Unknown test case.', 'ai-post-scheduler'), 0.0);
        }

        if (!$this->ai_service->is_available()) {
            return $this->fail($case_id, __('No AI provider is available. Check the provider settings.', 'ai-post-scheduler'), 0.0);
        }

        // Isolate the call log so the expanded view shows only this case's traffic.
        $this->ai_service->clear_call_log();

        $started = microtime(true);

        try {
            switch ($case_id) {
                case 'generate_title':
                    $result = $this->case_generate_title();
                    break;
                case 'generate_content':
                    $result = $this->case_generate_content();
                    break;
                case 'generate_excerpt':
                    $result = $this->case_generate_excerpt();
                    break;
                case 'generate_json':
                    $result = $this->case_generate_json();
                    break;
                case 'generate_featured_image':
                    $result = $this->case_generate_featured_image();
                    break;
                case 'save_post':
                    $result = $this->case_save_post();
                    break;
                case 'bulk_posts':
                    $result = $this->case_bulk_posts();
                    break;
                default:
                    $result = array('status' => 'failed', 'error' => __('Case is not implemented.', 'ai-post-scheduler'));
            }
        } catch (Throwable $e) {
            // Throwable, not Exception: a TypeError deep in a provider adapter
            // should still render as a failed row rather than a fatal page.
            $this->logger->log('Stress test case threw: ' . $e->getMessage(), 'error', array('case' => $case_id));

            $result = array(
                'status' => 'failed',
                'error'  => sprintf(
                    /* translators: 1: exception class, 2: message */
                    __('%1$s: %2$s', 'ai-post-scheduler'),
                    get_class($e),
                    $e->getMessage()
                ),
            );
        }

        $duration_ms = (microtime(true) - $started) * 1000;

        return array_merge(
            array(
                'case'         => $case_id,
                'label'        => $case['label'],
                'description'  => $case['description'],
                'group'        => $case['group'],
                'status'       => 'failed',
                'summary'      => '',
                'ai_value'     => null,
                'plugin_value' => null,
                'error'        => null,
                'artifacts'    => array(),
            ),
            $result,
            array(
                'duration_ms' => (int) round($duration_ms),
                'ai_calls'    => $this->collect_ai_calls(),
            )
        );
    }

    /**
     * Build a failed-result envelope.
     *
     * @param string $case_id     Case identifier.
     * @param string $error       Error message.
     * @param float  $duration_ms Elapsed milliseconds.
     * @return array<string, mixed>
     */
    private function fail($case_id, $error, $duration_ms) {
        $case = $this->get_case($case_id);

        return array(
            'case'         => $case_id,
            'label'        => $case ? $case['label'] : $case_id,
            'description'  => $case ? $case['description'] : '',
            'group'        => $case ? $case['group'] : '',
            'status'       => 'failed',
            'summary'      => $error,
            'ai_value'     => null,
            'plugin_value' => null,
            'error'        => $error,
            'artifacts'    => array(),
            'duration_ms'  => (int) round($duration_ms),
            'ai_calls'     => array(),
        );
    }

    /**
     * Normalize the AI service call log into serializable request/response pairs.
     *
     * Data URIs are truncated: a base64 image can be several megabytes and would
     * otherwise be pushed through the AJAX response into the browser.
     *
     * @return array<int, array<string, mixed>>
     */
    private function collect_ai_calls() {
        $calls = array();

        foreach ($this->ai_service->get_call_log() as $entry) {
            $response = isset($entry['response']) ? $entry['response'] : array();
            $content  = isset($response['content']) ? $response['content'] : null;

            $calls[] = array(
                'type'     => isset($entry['type']) ? $entry['type'] : '',
                'time'     => isset($entry['timestamp']) ? $entry['timestamp'] : '',
                'request'  => array(
                    'prompt'  => isset($entry['request']['prompt']) ? (string) $entry['request']['prompt'] : '',
                    'options' => isset($entry['request']['options']) ? $this->scrub_options($entry['request']['options']) : array(),
                ),
                'response' => array(
                    'success' => !empty($response['success']),
                    'content' => $this->shorten_data_uri($content),
                    'error'   => isset($response['error']) ? $response['error'] : null,
                ),
            );
        }

        return $calls;
    }

    /**
     * Remove credentials and non-serializable values from logged options.
     *
     * @param mixed $options Logged options.
     * @return array<string, mixed>
     */
    private function scrub_options($options) {
        if (!is_array($options)) {
            return array();
        }

        unset($options['api_key']);

        foreach ($options as $key => $value) {
            if (is_object($value)) {
                $options[$key] = '[' . get_class($value) . ']';
            }
        }

        return $options;
    }

    /**
     * Replace the body of a long data URI with a placeholder.
     *
     * @param mixed $value Possibly a data URI.
     * @return mixed
     */
    private function shorten_data_uri($value) {
        if (!is_string($value) || strpos($value, 'data:') !== 0 || strlen($value) <= 120) {
            return $value;
        }

        return substr($value, 0, 100) . sprintf('… [%s truncated]', size_format(strlen($value)));
    }

    // -----------------------------------------------------------------------
    // Cases
    // -----------------------------------------------------------------------

    /**
     * Title generation: raw response versus the cleaned title.
     *
     * @return array<string, mixed>
     */
    private function case_generate_title() {
        $context = $this->build_context();
        $result  = $this->get_generator()->generate_title_for_context($context, $this->sample_article());

        if (is_wp_error($result)) {
            return array('status' => 'failed', 'error' => $result->get_error_message(), 'summary' => $result->get_error_message());
        }

        $raw = $this->last_ai_response_text();

        if (trim((string) $result) === '') {
            return array(
                'status'   => 'failed',
                'error'    => __('The provider returned an empty title.', 'ai-post-scheduler'),
                'summary'  => __('Empty title returned.', 'ai-post-scheduler'),
                'ai_value' => $raw,
            );
        }

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: %d: character count */
                __('Title generated (%d characters).', 'ai-post-scheduler'),
                mb_strlen($result)
            ),
            'ai_value'     => $raw,
            'plugin_value' => $result,
        );
    }

    /**
     * Content generation: raw response versus normalized post HTML.
     *
     * @return array<string, mixed>
     */
    private function case_generate_content() {
        $context   = $this->build_context();
        $generator = $this->get_generator();

        // Deliberately not generate_preview(): that runs title and excerpt too,
        // which would duplicate the other cases and triple this one's cost. Drive
        // the content step alone so the row measures exactly what it claims to.
        $builder         = new AIPS_Prompt_Builder();
        $content_prompt  = $builder->build_content_prompt($context);
        $content_context = $builder->build_content_context($context);

        $options = array();

        if ($content_context !== '') {
            $options['context'] = $content_context;
        }

        $raw = $generator->generate_content($content_prompt, $options, 'content');

        if (is_wp_error($raw)) {
            return array('status' => 'failed', 'error' => $raw->get_error_message(), 'summary' => $raw->get_error_message());
        }

        $content = $generator->normalize_generated_content_for_wordpress($raw);

        if (trim($content) === '') {
            return array(
                'status'   => 'failed',
                'error'    => __('The provider returned no usable article body.', 'ai-post-scheduler'),
                'summary'  => __('Empty content returned.', 'ai-post-scheduler'),
                'ai_value' => $raw,
            );
        }

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: 1: word count, 2: character count */
                __('%1$d words / %2$d characters after normalization.', 'ai-post-scheduler'),
                str_word_count(wp_strip_all_tags($content)),
                mb_strlen($content)
            ),
            'ai_value'     => $raw,
            'plugin_value' => $content,
        );
    }

    /**
     * Excerpt generation against a fixed article.
     *
     * @return array<string, mixed>
     */
    private function case_generate_excerpt() {
        $article = $this->sample_article();
        $excerpt = $this->get_generator()->generate_excerpt(
            __('Testing the AI Post Scheduler Pipeline', 'ai-post-scheduler'),
            $article,
            null,
            $this->sample_topic()
        );

        $raw = $this->last_ai_response_text();

        if (trim((string) $excerpt) === '') {
            return array(
                'status'   => 'failed',
                'error'    => __('The provider returned an empty excerpt.', 'ai-post-scheduler'),
                'summary'  => __('Empty excerpt returned.', 'ai-post-scheduler'),
                'ai_value' => $raw,
            );
        }

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: 1: word count, 2: character count */
                __('%1$d words / %2$d characters stored.', 'ai-post-scheduler'),
                str_word_count($excerpt),
                mb_strlen($excerpt)
            ),
            'ai_value'     => $raw,
            'plugin_value' => $excerpt,
        );
    }

    /**
     * Structured JSON output, including the text-extraction fallback path.
     *
     * @return array<string, mixed>
     */
    private function case_generate_json() {
        $schema = array(
            'type'       => 'object',
            'properties' => array(
                'topics' => array(
                    'type'  => 'array',
                    'items' => array('type' => 'string'),
                ),
            ),
            'required'   => array('topics'),
        );

        $prompt = __('List exactly three blog post topics about sustainable home gardening. Respond with a single JSON object shaped as {"topics": ["first", "second", "third"]} and nothing else.', 'ai-post-scheduler');

        $result = $this->ai_service->generate_json($prompt, array(
            'json_schema' => $schema,
            'max_tokens'  => 300,
        ));

        $raw = $this->last_ai_response_text();

        if (is_wp_error($result)) {
            return array('status' => 'failed', 'error' => $result->get_error_message(), 'summary' => $result->get_error_message(), 'ai_value' => $raw);
        }

        $topics = (isset($result['topics']) && is_array($result['topics'])) ? $result['topics'] : array();

        if (empty($topics)) {
            return array(
                'status'       => 'failed',
                'error'        => __('JSON parsed but contained no "topics" array.', 'ai-post-scheduler'),
                'summary'      => __('Response did not match the requested schema.', 'ai-post-scheduler'),
                'ai_value'     => $raw,
                'plugin_value' => $result,
            );
        }

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: %d: number of topics */
                __('Parsed %d topics from structured output.', 'ai-post-scheduler'),
                count($topics)
            ),
            'ai_value'     => $raw,
            'plugin_value' => $result,
        );
    }

    /**
     * Image generation plus media library upload.
     *
     * @return array<string, mixed>
     */
    private function case_generate_featured_image() {
        $prompt = __('A bright flat-lay photograph of a wooden desk with a notebook, a cup of coffee, and a small potted plant.', 'ai-post-scheduler');

        $image_service = new AIPS_Image_Service($this->ai_service);
        $attachment_id = $image_service->generate_and_upload_featured_image($prompt, __('AIPS Stress Test Image', 'ai-post-scheduler'));

        $raw = $this->last_ai_response_text();

        if (is_wp_error($attachment_id)) {
            return array('status' => 'failed', 'error' => $attachment_id->get_error_message(), 'summary' => $attachment_id->get_error_message(), 'ai_value' => $raw);
        }

        update_post_meta($attachment_id, self::TEST_ATTACHMENT_META, 1);

        $url = wp_get_attachment_url($attachment_id);

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: %d: attachment ID */
                __('Image uploaded as attachment #%d.', 'ai-post-scheduler'),
                $attachment_id
            ),
            'ai_value'     => $raw,
            'plugin_value' => array(
                'attachment_id' => (int) $attachment_id,
                'url'           => $url,
            ),
            'artifacts'    => array(
                'attachment_ids' => array((int) $attachment_id),
                'preview_url'    => $url,
            ),
        );
    }

    /**
     * Full pipeline through to a saved draft post.
     *
     * @return array<string, mixed>
     */
    private function case_save_post() {
        $post_id = $this->generate_and_mark_post();

        if (is_wp_error($post_id)) {
            return array('status' => 'failed', 'error' => $post_id->get_error_message(), 'summary' => $post_id->get_error_message());
        }

        $post = get_post($post_id);

        return array(
            'status'       => 'passed',
            'summary'      => sprintf(
                /* translators: %d: post ID */
                __('Draft post #%d created.', 'ai-post-scheduler'),
                $post_id
            ),
            'ai_value'     => $this->first_ai_response_text(),
            'plugin_value' => array(
                'post_id' => (int) $post_id,
                'title'   => $post ? $post->post_title : '',
                'excerpt' => $post ? $post->post_excerpt : '',
                'status'  => $post ? $post->post_status : '',
                'edit_url' => get_edit_post_link($post_id, 'raw'),
            ),
            'artifacts'    => array(
                'post_ids' => array((int) $post_id),
            ),
        );
    }

    /**
     * Repeat the full pipeline to surface rate limits and circuit-breaker trips.
     *
     * A partial run still reports failure but keeps the posts it did create, so
     * the artifacts stay available for inspection and cleanup.
     *
     * @return array<string, mixed>
     */
    private function case_bulk_posts() {
        $post_ids = array();
        $errors   = array();

        for ($i = 0; $i < self::BULK_POST_COUNT; $i++) {
            $post_id = $this->generate_and_mark_post($i + 1);

            if (is_wp_error($post_id)) {
                $errors[] = sprintf('#%d: %s', $i + 1, $post_id->get_error_message());
                continue;
            }

            $post_ids[] = (int) $post_id;
        }

        $created = count($post_ids);
        $summary = sprintf(
            /* translators: 1: created count, 2: requested count */
            __('%1$d of %2$d posts created.', 'ai-post-scheduler'),
            $created,
            self::BULK_POST_COUNT
        );

        return array(
            'status'       => ($created === self::BULK_POST_COUNT) ? 'passed' : 'failed',
            'summary'      => $summary,
            'error'        => empty($errors) ? null : implode(' | ', $errors),
            'ai_value'     => $this->first_ai_response_text(),
            'plugin_value' => array(
                'created'  => $created,
                'expected' => self::BULK_POST_COUNT,
                'post_ids' => $post_ids,
                'errors'   => $errors,
            ),
            'artifacts'    => array(
                'post_ids' => $post_ids,
            ),
        );
    }

    // -----------------------------------------------------------------------
    // Shared fixtures
    // -----------------------------------------------------------------------

    /**
     * Lazily construct the generator.
     *
     * It is wired to this service's own AI service instance so every provider
     * call the generator makes lands in the call log the results panel reads.
     *
     * @return AIPS_Generator
     */
    private function get_generator() {
        if ($this->generator === null) {
            $this->generator = new AIPS_Generator($this->logger, $this->ai_service);
        }

        return $this->generator;
    }

    /**
     * Topic used by every case, so runs stay comparable.
     *
     * @return string
     */
    private function sample_topic() {
        /**
         * Filters the topic the stress test generates against.
         *
         * @since 3.2.0
         *
         * @param string $topic Default sample topic.
         */
        return (string) apply_filters('aips_stress_test_topic', __('Practical tips for starting a balcony herb garden', 'ai-post-scheduler'));
    }

    /**
     * A synthetic template context so the page works on a site with no templates.
     *
     * @param int $index Optional run index, used to vary bulk-run topics.
     * @return AIPS_Template_Context
     */
    private function build_context($index = 0) {
        $topic = $this->sample_topic();

        if ($index > 0) {
            $topic .= sprintf(' (%d)', $index);
        }

        $template = (object) array(
            'id'                      => 0,
            'name'                    => __('AIPS Stress Test', 'ai-post-scheduler'),
            'prompt_template'         => __('Write a short, practical article of roughly 300 words about {{topic}}. Use two <h2> sections.', 'ai-post-scheduler'),
            'title_prompt'            => __('Write a clear, specific title. No colons, no clickbait.', 'ai-post-scheduler'),
            'image_prompt'            => '',
            'generate_featured_image' => false,
            'post_status'             => 'draft',
            'post_type'               => 'post',
            'post_category'           => '',
            'post_tags'               => '',
            'post_author'             => get_current_user_id(),
            'article_structure_id'    => null,
            'include_sources'         => false,
            'source_group_ids'        => '',
        );

        /**
         * Filters the synthetic template used by the stress test.
         *
         * @since 3.2.0
         *
         * @param object $template Template stand-in.
         * @param string $topic    Topic being generated.
         */
        $template = apply_filters('aips_stress_test_template', $template, $topic);

        return new AIPS_Template_Context($template, null, $topic, 'manual');
    }

    /**
     * Run the full pipeline and tag the resulting post as test data.
     *
     * @param int $index Optional run index for bulk runs.
     * @return int|WP_Error Post ID or error.
     */
    private function generate_and_mark_post($index = 0) {
        $post_id = $this->get_generator()->generate_post($this->build_context($index));

        if (!is_wp_error($post_id)) {
            update_post_meta($post_id, self::TEST_POST_META, 1);
        }

        return $post_id;
    }

    /**
     * Fixed article body used by cases that summarize rather than generate.
     *
     * @return string
     */
    private function sample_article() {
        return '<p>' . __('Balcony herb gardens work best when you start with the light you actually have rather than the herbs you want. South-facing rails carry rosemary and thyme through a full season; a shaded corner will do better with mint, parsley, and chives.', 'ai-post-scheduler') . '</p>'
            . '<h2>' . __('Choosing containers', 'ai-post-scheduler') . '</h2>'
            . '<p>' . __('Depth matters more than width for most culinary herbs. A twenty-centimetre pot holds enough soil to buffer temperature swings, which is what actually kills balcony plants in midsummer.', 'ai-post-scheduler') . '</p>'
            . '<h2>' . __('Watering rhythm', 'ai-post-scheduler') . '</h2>'
            . '<p>' . __('Containers dry from the top down, so surface soil is a poor indicator. Push a finger to the second knuckle before watering, and water until it runs from the base.', 'ai-post-scheduler') . '</p>';
    }

    /**
     * Text of the most recent successful AI response.
     *
     * @return string|null
     */
    private function last_ai_response_text() {
        $log = $this->ai_service->get_call_log();

        for ($i = count($log) - 1; $i >= 0; $i--) {
            if (!empty($log[$i]['response']['success'])) {
                return $this->shorten_data_uri($log[$i]['response']['content']);
            }
        }

        return null;
    }

    /**
     * Text of the first successful AI response.
     *
     * Multi-call cases make several requests; the first is the one whose raw
     * output the plugin then transformed, so that is what belongs beside the
     * final value.
     *
     * @return string|null
     */
    private function first_ai_response_text() {
        foreach ($this->ai_service->get_call_log() as $entry) {
            if (!empty($entry['response']['success'])) {
                return $this->shorten_data_uri($entry['response']['content']);
            }
        }

        return null;
    }

    // -----------------------------------------------------------------------
    // Test data management
    // -----------------------------------------------------------------------

    /**
     * Count posts and attachments created by this page.
     *
     * @return array{posts: int, attachments: int}
     */
    public function count_test_data() {
        return array(
            'posts'       => count($this->get_test_post_ids()),
            'attachments' => count($this->get_test_attachment_ids()),
        );
    }

    /**
     * IDs of posts created by this page.
     *
     * @return int[]
     */
    private function get_test_post_ids() {
        return get_posts(array(
            'post_type'        => 'any',
            'post_status'      => 'any',
            'numberposts'      => 200,
            'fields'           => 'ids',
            'meta_key'         => self::TEST_POST_META,
            'suppress_filters' => false,
        ));
    }

    /**
     * IDs of attachments created by this page.
     *
     * @return int[]
     */
    private function get_test_attachment_ids() {
        return get_posts(array(
            'post_type'        => 'attachment',
            'post_status'      => 'any',
            'numberposts'      => 200,
            'fields'           => 'ids',
            'meta_key'         => self::TEST_ATTACHMENT_META,
            'suppress_filters' => false,
        ));
    }

    /**
     * Permanently delete everything this page created.
     *
     * @return array{posts: int, attachments: int}
     */
    public function cleanup_test_data() {
        $deleted_posts = 0;
        $deleted_media = 0;

        foreach ($this->get_test_post_ids() as $post_id) {
            // Bypass the trash: these are disposable fixtures, and leaving them in
            // the trash would keep them counted as existing test data.
            if (wp_delete_post($post_id, true)) {
                $deleted_posts++;
            }
        }

        foreach ($this->get_test_attachment_ids() as $attachment_id) {
            if (wp_delete_attachment($attachment_id, true)) {
                $deleted_media++;
            }
        }

        $this->logger->log('Stress test data cleaned up', 'info', array(
            'posts'       => $deleted_posts,
            'attachments' => $deleted_media,
        ));

        return array('posts' => $deleted_posts, 'attachments' => $deleted_media);
    }

    /**
     * Snapshot of the environment shown above the results.
     *
     * @return array<string, mixed>
     */
    public function get_environment() {
        $config   = AIPS_Config::get_instance();
        $provider = AIPS_AI_Provider_Factory::create();

        return array(
            'provider'        => $provider->get_label(),
            'provider_id'     => $provider->get_id(),
            'available'       => $provider->is_available(),
            'reason'          => $provider->is_available() ? '' : $provider->get_unavailable_reason(),
            'model'           => (string) $config->get_option('aips_ai_model'),
            'native_json'     => $provider->supports_native_json(),
            'conversation'    => $provider->supports_conversation(),
            'conversational'  => (bool) $config->get_option('aips_conversational_generation'),
            'metadata_turn'   => (bool) $config->get_option('aips_conversational_metadata_turn'),
        );
    }
}
