<?php
/**
 * Post Review Repository
 *
 * Database abstraction layer for post review operations.
 * Handles queries for draft posts generated by the AI Post Scheduler.
 *
 * @package AI_Post_Scheduler
 * @since 1.8.0
 */

if (!defined('ABSPATH')) {
	exit;
}

/**
 * Class AIPS_Post_Review_Repository
 *
 * Repository for querying and managing draft posts that need review.
 */
class AIPS_Post_Review_Repository {
	
	/**
	 * @var string The history table name (with prefix)
	 */
	private $table_name;
	
	/**
	 * @var wpdb WordPress database abstraction object
	 */
	private $wpdb;
	
	/**
	 * Initialize the repository.
	 */
	public function __construct() {
		global $wpdb;
		$this->wpdb = $wpdb;
		$this->table_name = $wpdb->prefix . 'aips_history';
	}
	
	/**
	 * Get paginated draft posts with optional filtering.
	 *
	 * @param array $args {
	 *     Optional. Query arguments.
	 *
	 *     @type int    $per_page    Number of items per page. Default 20.
	 *     @type int    $page        Current page number. Default 1.
	 *     @type string $search      Search term for title. Default empty.
	 *     @type int    $template_id Filter by template ID. Default 0.
	 *     @type string $orderby     Column to order by. Default 'created_at'.
	 *     @type string $order       Order direction (ASC/DESC). Default 'DESC'.
	 * }
	 * @return array {
	 *     @type array $items        Array of draft post items.
	 *     @type int   $total        Total number of items.
	 *     @type int   $pages        Total number of pages.
	 *     @type int   $current_page Current page number.
	 * }
	 */
	public function get_draft_posts($args = array()) {
		$defaults = array(
			'per_page' => 20,
			'page' => 1,
			'search' => '',
			'template_id' => 0,
			'orderby' => 'created_at',
			'order' => 'DESC',
		);
		
		$args = wp_parse_args($args, $defaults);
		
		$offset = ($args['page'] - 1) * $args['per_page'];

		// Build where clauses
		$where_clauses = array("1=1");
		$where_args = array();
		
		// Only get completed generations that have a post_id
		$where_clauses[] = "h.status = 'completed'";
		$where_clauses[] = "h.post_id IS NOT NULL";
		
		// Join with wp_posts to check post_status
		$where_clauses[] = "p.post_status = 'draft'";
		
		if (!empty($args['template_id'])) {
			$where_clauses[] = "h.template_id = %d";
			$where_args[] = $args['template_id'];
		}

		if (!empty($args['search'])) {
			$where_clauses[] = "(h.generated_title LIKE %s OR p.post_title LIKE %s)";
			$search_term = '%' . $this->wpdb->esc_like($args['search']) . '%';
			$where_args[] = $search_term;
			$where_args[] = $search_term;
		}
		
		$where_sql = implode(' AND ', $where_clauses);

		// Validate orderby and order
		$orderby = in_array($args['orderby'], array('created_at', 'completed_at', 'post_title')) ? $args['orderby'] : 'created_at';
		$order = strtoupper($args['order']) === 'ASC' ? 'ASC' : 'DESC';
		
		// For post_title ordering, use p.post_title
		if ($orderby === 'post_title') {
			$orderby_sql = "p.post_title $order";
		} else {
			$orderby_sql = "h.$orderby $order";
		}
		
		$templates_table = $this->wpdb->prefix . 'aips_templates';
		$posts_table = $this->wpdb->posts;
		
		// Query for items
		$query_args = $where_args;
		$query_args[] = $args['per_page'];
		$query_args[] = $offset;

		$results = $this->wpdb->get_results($this->wpdb->prepare("
			SELECT 
				h.*,
				t.name as template_name,
				p.post_title,
				p.post_modified,
				p.post_author as wp_post_author
			FROM {$this->table_name} h
			LEFT JOIN {$templates_table} t ON h.template_id = t.id
			INNER JOIN {$posts_table} p ON h.post_id = p.ID
			WHERE $where_sql
			ORDER BY $orderby_sql
			LIMIT %d OFFSET %d
		", $query_args));
		
		// Query for total count
		if (!empty($where_args)) {
			$count_args = array_slice($where_args, 0, count($where_args) - 2); // Remove LIMIT and OFFSET
			$total = $this->wpdb->get_var($this->wpdb->prepare(
				"SELECT COUNT(*) FROM {$this->table_name} h 
				INNER JOIN {$posts_table} p ON h.post_id = p.ID
				WHERE $where_sql",
				$count_args
			));
		} else {
			$total = $this->wpdb->get_var(
				"SELECT COUNT(*) FROM {$this->table_name} h 
				INNER JOIN {$posts_table} p ON h.post_id = p.ID
				WHERE $where_sql"
			);
		}
		
		return array(
			'items' => $results,
			'total' => (int) $total,
			'pages' => ceil($total / $args['per_page']),
			'current_page' => $args['page'],
		);
	}
	
	/**
	 * Get count of draft posts.
	 *
	 * @return int Number of draft posts.
	 */
	public function get_draft_count() {
		$posts_table = $this->wpdb->posts;
		
		$count = $this->wpdb->get_var("
			SELECT COUNT(*) 
			FROM {$this->table_name} h
			INNER JOIN {$posts_table} p ON h.post_id = p.ID
			WHERE h.status = 'completed' 
			AND h.post_id IS NOT NULL 
			AND p.post_status = 'draft'
		");
		
		return (int) $count;
	}
}
