<?php
/**
 * Post Review Repository
 *
 * Database abstraction layer for post review operations.
 * Handles queries for draft posts generated by the AI Post Scheduler.
 *
 * @package AI_Post_Scheduler
 * @since 1.8.0
 */

if (!defined('ABSPATH')) {
	exit;
}

/**
 * Class AIPS_Post_Review_Repository
 *
 * Repository for querying and managing draft posts that need review.
 */
class AIPS_Post_Review_Repository {
	
	/**
	 * @var string The history table name (with prefix)
	 */
	private $table_name;
	
	/**
	 * @var wpdb WordPress database abstraction object
	 */
	private $wpdb;
	
	/**
	 * Initialize the repository.
	 */
	public function __construct() {
		global $wpdb;
		$this->wpdb = $wpdb;
		$this->table_name = $wpdb->prefix . 'aips_history';
	}
	
	/**
	 * Get paginated draft posts with optional filtering.
	 *
	 * @param array $args {
	 *     Optional. Query arguments.
	 *
	 *     @type int    $per_page    Number of items per page. Default 20.
	 *     @type int    $page        Current page number. Default 1.
	 *     @type string $search      Search term for title. Default empty.
	 *     @type int    $template_id Filter by template ID. Default 0.
	 *     @type string $orderby     Column to order by. Default 'created_at'.
	 *     @type string $order       Order direction (ASC/DESC). Default 'DESC'.
	 * }
	 * @return array {
	 *     @type array $items        Array of draft post items.
	 *     @type int   $total        Total number of items.
	 *     @type int   $pages        Total number of pages.
	 *     @type int   $current_page Current page number.
	 * }
	 */
	public function get_draft_posts($args = array()) {
		$defaults = array(
			'per_page' => 20,
			'page' => 1,
			'search' => '',
			'template_id' => 0,
			'post_type' => '',
			'orderby' => 'created_at',
			'order' => 'DESC',
		);
		
		$args = wp_parse_args($args, $defaults);
		
		$offset = ($args['page'] - 1) * $args['per_page'];

		// Build where clauses
		$where_clauses = array("1=1");
		$where_args = array();
		
		// Only get completed generations that have a post_id
		$where_clauses[] = "h.status = 'completed'";
		$where_clauses[] = "h.post_id IS NOT NULL";
		
		// Join with wp_posts to check post_status
		$where_clauses[] = "p.post_status = 'draft'";
		
		if (!empty($args['template_id'])) {
			$where_clauses[] = "h.template_id = %d";
			$where_args[] = $args['template_id'];
		}

		if (!empty($args['post_type'])) {
			// Filter on the joined wp_posts row rather than h.post_type: the
			// post always exists here (INNER JOIN on post_status = 'draft'),
			// so this is authoritative regardless of history backfill timing.
			$where_clauses[] = "p.post_type = %s";
			$where_args[] = sanitize_key($args['post_type']);
		}

		if (!empty($args['search'])) {
			$where_clauses[] = "(h.generated_title LIKE %s OR p.post_title LIKE %s)";
			$search_term = '%' . $this->wpdb->esc_like($args['search']) . '%';
			$where_args[] = $search_term;
			$where_args[] = $search_term;
		}
		
		$where_sql = implode(' AND ', $where_clauses);

		// Validate orderby and order
		$orderby = in_array($args['orderby'], array('created_at', 'completed_at', 'post_title')) ? $args['orderby'] : 'created_at';
		$order = strtoupper($args['order']) === 'ASC' ? 'ASC' : 'DESC';
		
		// For post_title ordering, use p.post_title
		if ($orderby === 'post_title') {
			$orderby_sql = "p.post_title $order";
		} else {
			$orderby_sql = "h.$orderby $order";
		}
		
		$templates_table = $this->wpdb->prefix . 'aips_templates';
		$posts_table = $this->wpdb->posts;
		
		// Query for items
		$query_args = $where_args;
		$query_args[] = $args['per_page'];
		$query_args[] = $offset;

		$results = $this->wpdb->get_results($this->wpdb->prepare("
			SELECT 
				h.*,
				t.name as template_name,
				p.post_title,
				p.post_modified,
				p.post_author as wp_post_author
			FROM {$this->table_name} h
			LEFT JOIN {$templates_table} t ON h.template_id = t.id
			INNER JOIN {$posts_table} p ON h.post_id = p.ID
			WHERE $where_sql
			ORDER BY $orderby_sql
			LIMIT %d OFFSET %d
		", $query_args));
		
		// Query for total count
		if (!empty($where_args)) {
			$total = $this->wpdb->get_var($this->wpdb->prepare(
				"SELECT COUNT(*) FROM {$this->table_name} h 
				INNER JOIN {$posts_table} p ON h.post_id = p.ID
				WHERE $where_sql",
				$where_args
			));
		} else {
			$total = $this->wpdb->get_var(
				"SELECT COUNT(*) FROM {$this->table_name} h 
				INNER JOIN {$posts_table} p ON h.post_id = p.ID
				WHERE $where_sql"
			);
		}
		
		return array(
			'items' => $results,
			'total' => (int) $total,
			'pages' => ceil($total / $args['per_page']),
			'current_page' => $args['page'],
		);
	}

	/** Paginate completed generated posts across every WordPress post status. */
	public function get_generated_posts($args = array()) {
		$args = wp_parse_args($args, array('page' => 1, 'per_page' => 20, 'feedback' => '', 'search' => '', 'author_id' => 0, 'template_id' => 0, 'campaign_id' => 0));
		// If the feedback table has not been installed yet (schema migration
		// pending), fall back to an empty listing rather than joining a missing
		// table. The caller renders the unfiltered list instead when this returns.
		$feedback_table = $this->wpdb->prefix . 'aips_post_feedback';
		if ($this->wpdb->get_var($this->wpdb->prepare('SHOW TABLES LIKE %s', $feedback_table)) !== $feedback_table) {
			return array('items' => array(), 'total' => 0, 'pages' => 0, 'current_page' => absint($args['page']));
		}
		$where = array("h.status = 'completed'", 'h.post_id IS NOT NULL');
		$values = array();
		if ($args['search']) { $where[] = '(h.generated_title LIKE %s OR p.post_title LIKE %s)'; $like = '%' . $this->wpdb->esc_like($args['search']) . '%'; $values[] = $like; $values[] = $like; }
		foreach (array('author_id', 'template_id', 'campaign_id') as $key) { if (!empty($args[$key])) { $where[] = 'h.' . $key . ' = %d'; $values[] = absint($args[$key]); } }
		$feedback_join = "LEFT JOIN {$this->wpdb->prefix}aips_post_feedback f ON f.id = (SELECT MAX(f2.id) FROM {$this->wpdb->prefix}aips_post_feedback f2 WHERE f2.post_id = h.post_id)";
		if ('liked' === $args['feedback'] || 'disliked' === $args['feedback']) { $where[] = 'f.reaction = %s'; $values[] = $args['feedback']; }
		if ('unrated' === $args['feedback']) { $where[] = "(f.id IS NULL OR f.reaction = 'cleared')"; }
		$where_sql = implode(' AND ', $where);
		$total_sql = "SELECT COUNT(*) FROM {$this->table_name} h INNER JOIN {$this->wpdb->posts} p ON p.ID = h.post_id $feedback_join WHERE $where_sql";
		$total = (int) (empty($values) ? $this->wpdb->get_var($total_sql) : $this->wpdb->get_var($this->wpdb->prepare($total_sql, $values)));
		$query_values = $values; $query_values[] = max(1, absint($args['per_page'])); $query_values[] = max(0, (absint($args['page']) - 1) * absint($args['per_page']));
		$sql = "SELECT h.*, p.post_title, p.post_status, f.reaction feedback_reaction, f.reason_category feedback_reason_category, f.comment feedback_comment, f.user_id feedback_user_id, f.created_at feedback_created_at FROM {$this->table_name} h INNER JOIN {$this->wpdb->posts} p ON p.ID = h.post_id $feedback_join WHERE $where_sql ORDER BY h.created_at DESC LIMIT %d OFFSET %d";
		return array('items' => $this->wpdb->get_results($this->wpdb->prepare($sql, $query_values)), 'total' => $total, 'pages' => (int) ceil($total / max(1, absint($args['per_page']))), 'current_page' => absint($args['page']));
	}
	
	/**
	 * Get count of draft posts.
	 *
	 * @return int Number of draft posts.
	 */
	public function get_draft_count() {
		$posts_table = $this->wpdb->posts;
		
		$count = $this->wpdb->get_var("
			SELECT COUNT(*) 
			FROM {$this->table_name} h
			INNER JOIN {$posts_table} p ON h.post_id = p.ID
			WHERE h.status = 'completed' 
			AND h.post_id IS NOT NULL 
			AND p.post_status = 'draft'
		");
		
		return (int) $count;
	}
}
