<?php
/**
 * Scenario Test: Post Review and Publishing Workflow
 *
 * Tests the workflow from draft post creation through review and publishing.
 *
 * @package AI_Post_Scheduler
 */

class Test_Scenario_Post_Review_And_Publishing extends WP_UnitTestCase {

	use Trait_Database_Assertions;

	private $post_id;
	private $author_id;

	/**
	 * Set up test fixtures
	 */
	public function setUp(): void {
		parent::setUp();

		// Create test author
		$this->author_id = $this->factory->user->create( array(
			'role' => 'author',
		) );
	}

	/**
	 * Test: Create and retrieve draft posts
	 *
	 * Verifies:
	 * 1. Draft post can be created
	 * 2. Post status is 'draft'
	 * 3. Post can be retrieved
	 */
	public function test_create_and_retrieve_draft_post() {
		// Create a draft post
		$this->post_id = wp_insert_post( array(
			'post_type'    => 'post',
			'post_title'   => 'Test Draft Post',
			'post_content' => 'This is test content for a draft post.',
			'post_status'  => 'draft',
			'post_author'  => $this->author_id,
		) );

		$this->assertNotFalse( $this->post_id, 'Post should be created' );

		// Verify post exists in database
		$this->assertDatabaseHas(
			'posts',
			array(
				'ID'          => $this->post_id,
				'post_status' => 'draft',
				'post_author' => $this->author_id,
			)
		);

		// Retrieve post
		$post = get_post( $this->post_id );
		$this->assertNotNull( $post, 'Post should be retrievable' );
		$this->assertEquals( 'draft', $post->post_status );
		$this->assertEquals( 'Test Draft Post', $post->post_title );
	}

	/**
	 * Test: Draft post can have generation history metadata
	 *
	 * Verifies:
	 * 1. Post metadata can be attached
	 * 2. History ID can be stored in post meta
	 * 3. Metadata is retrievable
	 */
	public function test_draft_post_with_history_metadata() {
		// Create a draft post
		$this->post_id = wp_insert_post( array(
			'post_type'    => 'post',
			'post_title'   => 'Generated Draft Post',
			'post_content' => 'Content generated by AI.',
			'post_status'  => 'draft',
			'post_author'  => $this->author_id,
		) );

		// Add history metadata
		$history_id = 123;
		update_post_meta( $this->post_id, '_aips_history_id', $history_id );

		// Verify metadata was stored
		$this->assertPostMeta( $this->post_id, '_aips_history_id', $history_id );

		// Verify can retrieve
		$retrieved_history_id = get_post_meta( $this->post_id, '_aips_history_id', true );
		$this->assertEquals( $history_id, $retrieved_history_id );
	}

	/**
	 * Test: Publish a draft post
	 *
	 * Verifies:
	 * 1. Draft post can be transitioned to published
	 * 2. Post status changes to 'publish'
	 * 3. Published post is publicly accessible
	 */
	public function test_publish_draft_post() {
		// Create a draft post
		$this->post_id = wp_insert_post( array(
			'post_type'    => 'post',
			'post_title'   => 'Post to Publish',
			'post_content' => 'This post will be published.',
			'post_status'  => 'draft',
			'post_author'  => $this->author_id,
		) );

		// Verify initial status is draft
		$this->assertDatabaseHas(
			'posts',
			array(
				'ID'          => $this->post_id,
				'post_status' => 'draft',
			)
		);

		// Publish the post
		wp_update_post( array(
			'ID'          => $this->post_id,
			'post_status' => 'publish',
		) );

		// Verify status changed
		$this->assertDatabaseHas(
			'posts',
			array(
				'ID'          => $this->post_id,
				'post_status' => 'publish',
			)
		);

		// Verify no longer draft
		$this->assertDatabaseMissing(
			'posts',
			array(
				'ID'          => $this->post_id,
				'post_status' => 'draft',
			)
		);

		// Verify post_date is set
		$post = get_post( $this->post_id );
		$this->assertNotEmpty( $post->post_date );
	}

	/**
	 * Test: Multiple draft posts and selective publishing
	 *
	 * Verifies:
	 * 1. Multiple draft posts can coexist
	 * 2. Individual posts can be published independently
	 * 3. Other drafts remain unpublished
	 */
	public function test_multiple_drafts_selective_publishing() {
		// Create multiple draft posts
		$draft_ids = array();
		for ( $i = 1; $i <= 3; $i++ ) {
			$draft_ids[] = wp_insert_post( array(
				'post_type'    => 'post',
				'post_title'   => "Draft Post $i",
				'post_content' => "Content for draft $i.",
				'post_status'  => 'draft',
				'post_author'  => $this->author_id,
			) );
		}

		// Verify all are drafts
		foreach ( $draft_ids as $id ) {
			$this->assertDatabaseHas(
				'posts',
				array(
					'ID'          => $id,
					'post_status' => 'draft',
				)
			);
		}

		// Publish only the second post
		wp_update_post( array(
			'ID'          => $draft_ids[1],
			'post_status' => 'publish',
		) );

		// Verify first and third remain draft
		$this->assertDatabaseHas(
			'posts',
			array(
				'ID'          => $draft_ids[0],
				'post_status' => 'draft',
			)
		);

		$this->assertDatabaseHas(
			'posts',
			array(
				'ID'          => $draft_ids[2],
				'post_status' => 'draft',
			)
		);

		// Verify second is published
		$this->assertDatabaseHas(
			'posts',
			array(
				'ID'          => $draft_ids[1],
				'post_status' => 'publish',
			)
		);
	}

	/**
	 * Test: Post review workflow with metadata preservation
	 *
	 * Verifies:
	 * 1. Draft post metadata is preserved during review
	 * 2. Publishing doesn't lose metadata
	 * 3. All metadata remains accessible after publishing
	 */
	public function test_post_review_with_metadata_preservation() {
		// Create draft with multiple metadata fields
		$this->post_id = wp_insert_post( array(
			'post_type'    => 'post',
			'post_title'   => 'Review Post',
			'post_content' => 'Content to review.',
			'post_status'  => 'draft',
			'post_author'  => $this->author_id,
		) );

		// Add multiple metadata fields (simulating generation info)
		$metadata = array(
			'_aips_history_id'  => 456,
			'_aips_template_id' => 789,
			'_aips_schedule_id' => 321,
		);

		foreach ( $metadata as $key => $value ) {
			update_post_meta( $this->post_id, $key, $value );
		}

		// Verify metadata before publishing
		foreach ( $metadata as $key => $value ) {
			$this->assertPostMeta( $this->post_id, $key, $value );
		}

		// Publish the post
		wp_update_post( array(
			'ID'          => $this->post_id,
			'post_status' => 'publish',
		) );

		// Verify metadata is preserved after publishing
		foreach ( $metadata as $key => $value ) {
			$this->assertPostMeta( $this->post_id, $key, $value );
		}

		// Verify post is published
		$this->assertDatabaseHas(
			'posts',
			array(
				'ID'          => $this->post_id,
				'post_status' => 'publish',
			)
		);
	}

	/**
	 * Test: Draft post filtering
	 *
	 * Verifies:
	 * 1. Can query for draft posts only
	 * 2. Published posts are excluded
	 * 3. Count is accurate
	 */
	public function test_draft_post_filtering() {
		// Create mix of drafts and published posts
		$draft_ids = array();
		$published_ids = array();

		for ( $i = 1; $i <= 2; $i++ ) {
			$draft_ids[] = wp_insert_post( array(
				'post_type'    => 'post',
				'post_title'   => "Draft $i",
				'post_status'  => 'draft',
				'post_author'  => $this->author_id,
			) );
		}

		for ( $i = 1; $i <= 2; $i++ ) {
			$published_ids[] = wp_insert_post( array(
				'post_type'    => 'post',
				'post_title'   => "Published $i",
				'post_status'  => 'publish',
				'post_author'  => $this->author_id,
			) );
		}

		// Query for drafts
		global $wpdb;
		$draft_count = $wpdb->get_var( $wpdb->prepare(
			"SELECT COUNT(*) FROM $wpdb->posts WHERE post_type = %s AND post_status = %s AND post_author = %d",
			'post',
			'draft',
			$this->author_id
		) );

		// Should have at least 2 drafts (may have more from other tests)
		$this->assertGreaterThanOrEqual( 2, $draft_count );

		// Query for published
		$published_count = $wpdb->get_var( $wpdb->prepare(
			"SELECT COUNT(*) FROM $wpdb->posts WHERE post_type = %s AND post_status = %s AND post_author = %d",
			'post',
			'publish',
			$this->author_id
		) );

		// Should have at least 2 published
		$this->assertGreaterThanOrEqual( 2, $published_count );
	}
}
